### ISSUE TITLE
put operation fails for Sets and Maps with non-comparable members/keys

### ISSUE THREAD

**Issue by SVMBrown** [xtdb/xtdb#1001]
Cannot insert maps whose keys cannot be cast to `java.lang.Comparable` or sets whose members cannot be cast to `java.lang.Comparable`.
This occurs regardless of how the offending map or set is wrapped or nested.

Minimal reproduction:
```clojure
;; Set
(crux/submit-tx *db* 
  [[:crux.tx/put {:crux.db/id :failed-set
                  :my/set #{#{:foo} #{:bar}}}]])
;; Map
(crux/submit-tx *db* 
  [[:crux.tx/put {:crux.db/id :failed-map
                  :my/map {{:id :foo} :foo 
                           {:id :bar} :bar}}]])
```

This was encountered while trying to persist a map containing a destructuring form, but I'm sure that it could occur in many other cases. (e.g. sets of lists.)

I suspect that the issue lies in the sorting logic in `crux.codec` where the `nippy/IFreezable1` protocol is extended, as `crux.codec/sorted-kv-seq/reify` and `taoensso.nippy/write-kvs`  appear in the stacktrace for offending maps.

**Comment by jarohen** [comment]
Thanks Scot - we'll get on to this one.

(note to self - #362 for the historical context)
