### ISSUE TITLE
Generate JavaDoc and add to Public Docs

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#102]
The Java files with public API lives here:
https://github.com/juxt/crux/tree/master/src/crux/api

We also have `crux.ByteUtils` in Java but this is an internal class and should not be included.

**Comment by hraberg** [comment]
Added this now, but needs to be incorporated properly into the actual website.

**Comment by hraberg** [comment]
Handing over to @jonpither to integrate into documentation website.

**Comment by jonpither** [comment]
I've put up the javadocs here: https://juxt.pro/crux/javadoc/index.html

Thanks @hraberg for the recent commits. This issue should remain open until I've analysed a way to neatly fit the Javadocs into the Crux website, and whether this makes sense, i.e. with the use of an iframe.

**Comment by jonpither** [comment]
Should also ponder if there's a way we can easily auto publish both docs and the javadocs.

We can look at javadocs auto-building with a commit hook of sorts.

**Comment by hraberg** [comment]
For reference, I did add a javadoc building target to the Makefile a while back. It does delegate to `lein` to get the classpath.

**Comment by jonpither** [comment]
Done - we have a make target to build the docs
