### ISSUE TITLE
Fix CI 'create-artifacts'

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1020]
https://app.circleci.com/pipelines/github/juxt/crux/1239/workflows/7b06e443-c2b7-478a-84f4-89bf75ec46a6/jobs/5385

> Allocating a remote Docker Engine
> Requesting version: default
> Specified using docker layer caching, but it is only available for Performance Plan.
> Upgrade to Performance Plan to use docker layer caching.
> 
> Got error while creating host: failed to create host: rpc error: code = Unknown desc = An internal error occurred when  provisioning resources for this job. Provisioning Service returned status code: 403
> We had an unexpected error preparing a VM for this build, potentially due to our infrastructure or cloud provider.  Please retry the build in a few minutes

**Comment by danmason** [comment]
Pushed a fix to remove docker-layer-caching - should prevent this issue, but perhaps we should leave this card open until we've ran through our next release?

**Comment by danmason** [comment]
Post https://app.circleci.com/pipelines/github/juxt/crux/1323/workflows/0271f499-126f-41b8-aa42-010050621892 -  the layer caching wasnt the actual cause of the problem. Rather, seemingly, using `setup_remote_docker` twice (in both of the `create-artifacts` steps) causes the problem (as can also be seen in the original report)

For now, going to remove `crux-sql` build/deploy from the build as it's not being uploaded anywhere, currently, anyway - still, need to find a proper fix if we do, indeed, plan to build/release multiple JARs/docker images.
