### ISSUE TITLE
Console style changes 2020-08-14

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1036]
- [x] Don't collapse query editor on run
- [x] Click on recent query to edit, cursor: pointer, remove edit/run
- [x] Recent query bin over to the right
- [x] Remove recent queries temporary storage message
- [x] Remove `"` on server title
- [x] Remove home page, `/` links directly to query
- [x] Status to a tab on the console with sub-tabs
- [x] Flatten top-right nav - 'Documentation', 'Zulip Chat', 'Email support'
- [x] Enable metrics on the demo console (?)
- [x] Reduce padding between vt/tt
- [x] Vertical bar between CSV | TSV, remove 'download results as'
- [x] Drop 'Found' in 'Found X results'
- [x] Query results has an internal scrollbar but only on mobile - needs removing.
- [x] Clicking a link from attribute cardinalities doesn't run the query - creates weird broken state.

Slightly more involved, in terms of figuring out exactly what to have:
- [x] "Welcome to Crux console" in the query editor - should figure out what information we should have in this initial state - and what should be done as contextual help.
- [x] Add contextual help (for queries, metrics, valid-time, transaction-time etc) linking to docs.

**Comment by danmason** [comment]
Further points for discussion:

- [ ] Prevent scrolling to the top of the page every time a tab is clicked
- [ ] Make timestamps in the history pane easier to read - currently quite far.
- [ ] Date/time picker button to reset to default
- [ ] Switching between tabs clears the state of the various editors/inputs (would be nice to not lose comments in the editor, or be able to edit a query, switch tab and come back to your edits)
- [ ] Decide - open recent query in editor and run, or just open query in the editor?
- [ ] Discuss various styling points: particularly, the status pages and usages/styling of icons and various navbar links.
