### ISSUE TITLE
Explicit height on images in docs

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1037]
I'm reasonably sure that the lack of explicit heights is causing jumps when linking to an anchor, eg https://opencrux.com/reference/configuration.html#metrics

**Comment by danmason** [comment]
Pushed a commit to set explicit heights/widths on images - although as discussed, I believe a larger issue to be the code highlighting script loading and changing the height of code blocks.

(This particular issue, however, is fixed)
