### ISSUE TITLE
Stops re-indexing after every 100 transactions

### ISSUE THREAD

**Issue by jacobobryant** [xtdb/xtdb#1052]
I'm working on upgrading from `20.05-1.8.4-alpha` to `20.08-1.10.1-beta`. After deleting the kv store directory, I start the app and it begins re-indexing. I get a bunch of log messages like `19:44:14.070 [crux-standalone-tx-ingest-1] DEBUG crux.tx - Indexing tx-id: 52`. But when `tx-id` hits 99, it hangs (I'm calling `crux/sync` right after `crux/start-node`; I'm guessing the indexing just stops and so the hanging comes from `sync` blocking). If I kill the process and restart, it resumes re-indexing from tx-id 100... and then hangs at 199. and so forth. Unfortunately I have some 1M transactions in the event log, so re-indexing this way would take a while....

This is using the following (haven't tried it with my production postgres event log):
```clojure
(let [node (crux/start-node
             {:crux.kv/db-dir "..."
              :crux.node/topology '[crux.standalone/topology
                                    crux.kv.rocksdb/kv-store]
              :crux.standalone/event-log-dir "..."
              :crux.standalone/event-log-kv-store 'crux.kv.rocksdb/kv})]
  (crux/sync node)
  ...)
```

**Comment by jarohen** [comment]
Thanks for raising this one, @jacobobryant - will raise a PR shortly.
