### ISSUE TITLE
Users can search the doc site

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1059]
Couple of options, worth a quick consideration of methods/benefits/tradeoffs:

* Algolia
* `antora-lunr`
* others?

Thoughts?

**Comment by armincerf** [comment]
Just noting that I've already applied for Algolia's docsearch program, it doesn't commit us to anything, just saying in case anyone else was going to.

I've used Algolia on personal projects and can recommend it, and I think the analytics around what search terms people are using etc could really help to improve the docs.

They've set a very high standard with their instant search component and I think the amount of work it would take for us to achieve a similar result ourselves is quite high.

**Comment by refset** [comment]
xtdb.com now uses https://typesense.org/ (including for docs)
