### ISSUE TITLE
JDBC transaction times not returned consistently for nodes in different TZs

### ISSUE THREAD

**Issue by tolitius** [xtdb/xtdb#1071]
(original report by @tolitius below)

For some JDBC backends, transaction times are being stored in local-datetime column types.

* H2, MSSQL, Postgres are affected, MySQL, SQLite are unaffected.
* Crux clusters where all the nodes have the same TZ are unaffected, on the surface - the tx-log contains local dates but these are converted in and out of JDBC by the same offset.
* Crux clusters where the nodes have different TZs are vulnerable - the tx-times are converted with one TZ on the way in and a different TZ on the way out
* Valid times, and other times in users' documents, are unaffected - these are encoded to Nippy before entering the database, and so aren't subject to JDBC's arcane TZ handling. Valid times do default to transaction time where they're omitted, so these _are_ affected, but any fix to the transaction time will fix the errant valid-times too.

This manifested itself as a transaction that was ingested on one TZ not immediately appearing in a node in another TZ, because the tx-time appeared to be in the future, and was hence excluded from any queries.

---- 

(original report)

# facts created on Linux ignored on OS/X

## given

topology: `crux-jdbc` on top of `crux-rocksdb` k/v index:

```clojure
    (cx/start-node {:crux.node/topology '[crux.jdbc/topology
                                          crux.kv.rocksdb/kv-store]
                    :crux.jdbc/dbtype adapter
                    :crux.jdbc/dbname dbname
                    :crux.jdbc/host host
                    :crux.jdbc/user username
                    :crux.jdbc/password password
                    :crux.jdbc/minimumIdle min-db-pool
                    :crux.kv/db-dir (str (io/file index-dir "lennon-indexes"))})))
```

3 crux nodes on linux (centos): running remotely.
1 node crux on os/x running from within REPL locally.

## problem

when updating / inserting `:crux.tx/put` facts from os/x node they are visible / accessible from all 4 nodes with `entity/`entity-history`/etc.

when updating / inserting `:crux.tx/put` facts from any of the linux nodes they are only visible from other linux nodes, but _not visible_ / accessible from the os/x node.

which makes it quite difficult to develop with crux (on macs).

### os/x

```clojure
=> (crux/submit-tx cx/db [[:crux.tx/put {:crux.db/id :music/legend/beatles :first "john" :last "lennon"}]])
=> (crux/submit-tx cx/db [[:crux.tx/put {:crux.db/id :music/legend/beatles :first "john" :last "lennon" :age 80}]])
```

### linux

```clojure
=> (pprint (crux/entity-history (crux/db cx/db) :music/legend/beatles :asc {:with-docs? true}))
[{:crux.tx/tx-time #inst "2020-09-01T20:11:44.113-00:00",
  :crux.tx/tx-id 124021,
  :crux.db/valid-time #inst "2020-09-01T20:11:44.113-00:00",
  :crux.db/content-hash
  #crux/id "53076b5ff4a30ba206fb95c3f0d60daf16b65100",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles, :first "john", :last "lennon"}}
 {:crux.tx/tx-time #inst "2020-09-01T20:13:15.072-00:00",
  :crux.tx/tx-id 124023,
  :crux.db/valid-time #inst "2020-09-01T20:13:15.072-00:00",
  :crux.db/content-hash
  #crux/id "e47989c79bc8289585d3b5d88d79cf0caceaa096",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles,
   :first "john",
   :last "lennon",
   :age 80}}]
```

at this point history is consistent on both "sides", by all the nodes.

now we'll insert an additional fact about Lennon, but from linux side:

```clojure
=> (crux/submit-tx cx/db [[:crux.tx/put {:crux.db/id :music/legend/beatles :first "john" :last "lennon" :age 80 :first-band "The Quarrymen"}]])
#:crux.tx{:tx-id 124025, :tx-time #inst "2020-09-02T00:14:47.517-00:00"}
```

### mismatch

history is good on ALL linux nodes:

#### linux

```clojure
=> (pprint (crux/entity-history (crux/db cx/db) :music/legend/beatles :asc {:with-docs? true}))
[{:crux.tx/tx-time #inst "2020-09-01T20:11:44.113-00:00",
  :crux.tx/tx-id 124021,
  :crux.db/valid-time #inst "2020-09-01T20:11:44.113-00:00",
  :crux.db/content-hash
  #crux/id "53076b5ff4a30ba206fb95c3f0d60daf16b65100",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles, :first "john", :last "lennon"}}
 {:crux.tx/tx-time #inst "2020-09-01T20:13:15.072-00:00",
  :crux.tx/tx-id 124023,
  :crux.db/valid-time #inst "2020-09-01T20:13:15.072-00:00",
  :crux.db/content-hash
  #crux/id "e47989c79bc8289585d3b5d88d79cf0caceaa096",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles,
   :first "john",
   :last "lennon",
   :age 80}}
 {:crux.tx/tx-time #inst "2020-09-02T00:14:47.517-00:00",
  :crux.tx/tx-id 124025,
  :crux.db/valid-time #inst "2020-09-02T00:14:47.517-00:00",
  :crux.db/content-hash
  #crux/id "240c0bd8bf7d312dad1026ed2dadff9ae22ebd23",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles,
   :first "john",
   :last "lennon",
   :age 80,
   :first-band "The Quarrymen"}}]
```

but still at the second fact on the os/x node (missing the 3rd fact about `The Quarrymen`):

#### os/x

```clojure
=> (pprint (crux/entity-history (crux/db cx/db) :music/legend/beatles :asc {:with-docs? true}))
[{:crux.tx/tx-time #inst "2020-09-02T00:11:44.113-00:00",
  :crux.tx/tx-id 124021,
  :crux.db/valid-time #inst "2020-09-02T00:11:44.113-00:00",
  :crux.db/content-hash
  #crux/id "53076b5ff4a30ba206fb95c3f0d60daf16b65100",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles, :first "john", :last "lennon"}}
 {:crux.tx/tx-time #inst "2020-09-02T00:13:15.072-00:00",
  :crux.tx/tx-id 124023,
  :crux.db/valid-time #inst "2020-09-02T00:13:15.072-00:00",
  :crux.db/content-hash
  #crux/id "e47989c79bc8289585d3b5d88d79cf0caceaa096",
  :crux.db/doc
  {:crux.db/id :music/legend/beatles,
   :first "john",
   :last "lennon",
   :age 80}}]
```

## index data

attaching:

* the SQL dump from the DB (postgres)
* index data from linux side and os/x side:

```bash
$ tree crux-index-mismatch
crux-index-mismatch
├── linux
│   └── lennon-indexes
│       ├── 000006.log
│       ├── 000007.sst
│       ├── CURRENT
│       ├── IDENTITY
│       ├── LOCK
│       ├── LOG
│       ├── MANIFEST-000008
│       └── OPTIONS-000005
└── osx
    └── lennon-indexes
        ├── 000006.log
        ├── 000007.sst
        ├── CURRENT
        ├── IDENTITY
        ├── LOCK
        ├── LOG
        ├── MANIFEST-000008
        └── OPTIONS-000005

4 directories, 16 files
```

you'll notice that even though `000006.log` files on both platforms are the same size their hexdumps differ.

my hunch is that everything works as it should on the linux side. 

* I replayed these indices on other linux nodes and they all see the history fine.
* replaying these indices on os/x side result in the same problem: missing the 3rd fact
* I see that the index _was written_ into index files on os/x on _linux_ fact insert

I believe the way that os/x updates rocksdb index OR the way that crux index reads that index on os/x with [argona](https://github.com/real-logic/Agrona) is off. cause it is there, it is just not read properly / ignored.

[crux-index-mismatch.tar.gz](https://github.com/juxt/crux/files/5159368/crux-index-mismatch.tar.gz)
[tx_events.sql.tar.gz](https://github.com/juxt/crux/files/5159430/tx_events.sql.tar.gz)

**Comment by jarohen** [comment]
Just spotted - the valid-times/tx-times between the two nodes are different :disappointed: When you took out a DB on the machine with the later times in its indices, the data might well have been in the future for that node, so would have been excluded from entity-history - I suspect if you were to go query those indices now, you'd get all three.

It's likely caused by two nodes in different TZs, and one of them using local time instead of UTC somewhere, rather than OSX vs Linux (which I guess is somewhat fortunate, because I don't have easy access to an OSX machine).

Now to narrow down a cause...

Could you let me know what SQL dialect you're using?

**Comment by tolitius** [comment]
huh, you might be right
it was a throw away example, just wanted to use prod servers to make sure the infra is the same

it is `PostgreSQL`

I'll monitor how the index behaves with time to see whether timezone is what prevents these entries to be seen.

If that's really the issue (which I hope it is, since it is way simpler than looking into argona): is there a way to "put" records _without_ a "valid time"? i.e. I did not specify it in puts, hence have not thought about a "sneaked in" valid time )

**Comment by tolitius** [comment]
... or maybe to set crux node to always read/write index in UTC

**Comment by jarohen** [comment]
Thanks @tolitius - I've updated the issue above. Postgres is indeed one of the affected backends.

> is there a way to "put" records without a "valid time"? i.e. I did not specify it in puts, hence have not thought about a "sneaked in" valid time )

Records put without a valid-time default the valid-time to the transaction-time (this is quite a common use-case), but this default uses the transaction-time _after_ coming back through JDBC (i.e. the correct tx-time, with the offset negated). Thankfully, this means any fix to the transaction times will also fix the defaulted valid times.

> ... or maybe to set crux node to always read/write index in UTC

Indeed - the fix I'm working on ensures that Crux creates JDBC tables that store their dates in UTC. We'll unfortunately need to ask users to migrate existing JDBC transaction logs to use the correct column types :disappointed:
