### ISSUE TITLE
Users can select their language in the docs site

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1074]
* When the user selects a dialect, that setting is preserved throughout the site (local storage?)

**Comment by danmason** [comment]
Wonder if, within asciidoctor, we can use some form of logic to display a user's selected language - need to look further into it, but appears to have `ifdef`, `ifdef` and `ifeval` (see [here](https://asciidoctor.org/docs/user-manual/#conditional-preprocessor-directives)) which may be useful?

**Comment by danmason** [comment]
Note: May well have to do the logic for this, if possible, within the asciidoc itself - will have to take a look through the docs (https://asciidoctor.org/docs/user-manual/#example-extensions)

Had also wondered about having tabbed source code blocks  - seems like there are extensions for this in Antora. See: 
- https://gitlab.com/antora/antora-asciidoctor-extensions/tree/master/tabs-block
- How can I have code examples in different languages side-by-side in separate tabs?' in https://www.ahus1.de/post/cdc-antora-live#_questions_and_answers
- https://docs.couchbase.com/home/contribute/tabs.html
