### ISSUE TITLE
Datalog Range Queries

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#11]
Range queries should use the underlying indexes to scan the data.

**Comment by hraberg** [comment]
This requires a binary encoding of the keys that respect the order. It also likely requires type tags in the keys for the supported range types. Initially we probably want to support long, double, instant and string.

This is used when a query contains a range predicate, but a variable pointing to an attribute isn't yet bound to a real value via an entity. When the value exists, it's likely easier to use normal predicates, though care is needed to ensure they result in the same order as the binary encoding.

**Comment by hraberg** [comment]
Range queries are easier to do if the secondary indexes don't know about time, so one can scan by simply advancing the underlying KV iterator / cursor.

Some queries might also be best done by moving the cursor backwards. You can also encode the index itself in ascending or descending order depending on how it's expected to be used, but that's an optimisation.

**Comment by hraberg** [comment]
We want to support the normal operators, `<` `<=` `>` `>=`.

**Comment by jonpither** [comment]
Think we do?

**Comment by hraberg** [comment]
I mean using the indexes, looks like range right now supports `<` and `>`.

**Comment by hraberg** [comment]
How this works will change a bit once we have #40.

**Comment by hraberg** [comment]
All the range operators are now supported.
