### ISSUE TITLE
OpenCrux look-n-feel 2020-09-17

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1108]
* Top nav menu
* Hero image
* Fonts/Font colors
* Add current architecture diagram to home page

If it's easy:
* 3D graphics

**Comment by jonpither** [comment]
Also - move current architecture diagram on to the main page for this iteration

**Comment by jarohen** [comment]
Thanks @jonpither, have updated the description (and feel free to do the same, btw)
