### ISSUE TITLE
Investigate variance in crux-bench runs

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1133]
**Tried so far:**

> Check whether we're close to the boundaries of the Fargate resources 
> Check whether doubling the size of the Fargate resources (without doubling the size of the JVM) fixes the issue

Both of the above somewhat linked - increasing memory and CPU provided to a single task didn't see, particularly, much in the way of a decrease in overall various - and we appear far from the fargate boundaries.

> Check whether anyone else is having these issues

After a cursory check, can't find much to suggest that anyone is having particular issues with consistency on Fargate - still, much more research to be done there.

**To check:**
- Investigate moving it to EC2 (hopefully with 'lights-out' policy)

**Comment by danmason** [comment]
_(Porting across some previous discussions on the topic)_

 - Try moving to EC2 from ECS?
 - Sample size too small?
 - Warm up (run a number of pre-queries)
 - Individual queries taking a long time can skew

**Comment by danmason** [comment]
My own personal thoughts on the matter, so far:



I'd be willing to bet that using ECS Fargate is likely going to be a big contributor to our variance - I'd say investigating a move away from Fargate (as mentioned, potentially to EC2) would be well worth the time.

Looking through the benchmarks - I find it somewhat relieving that performance variance is more of a problem between seperate runs - and less of an issue between the various tasks in a bench run (ie - if one is taking longer than before, it seems that the rest all follow that trend). Certainly suggests, to me, variance between the hardware/environment that the benchmark is being ran on.

May also be worth checking how we have our tasks set up - in case there are any issues there, too.

Another thing that comes to mind (I doubt it would cause any problems, but it's worth mentioning) is the fact we uberjar and dockerize the benchmarks. (I mainly doubt this would cause issues as, if I recall correctly, we've seen consistently that benchmark variance even continues between two separate runs of the same master build/container)

After some preliminary tests, running through the bench on my own local machine multiple times, I found the variance between
the runs to be around 5 seconds (as opposed to the higher variance we do see on Fargate) - so as the card suggests I'm going to start by investigating issues with performance variance on Fargate and see if/how configuring it differently might help reduce the variance we see.

**Comment by jarohen** [comment]
@danmason was that local (lack of) variance over a whole bench run, btw?

**Comment by danmason** [comment]
Ahhh, fair point - no, that 5 seconds was over a single test (ts-devices, on standalone-rocksdb) in a bench run. (Still - far lower than the variance we've seen there)
