### ISSUE TITLE
History API

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#12]
It should be possible to read the entire history for a set of entities.

This does not necessarily mean that we need to support queries over the history database.

**Comment by hraberg** [comment]
There's a simple entity history API for doc.

**Comment by hraberg** [comment]
This is actually exposed on Datasource, you can get the entire history for a single entity, closing this for MVP. We'll revisit for more sophisticated support.

**Comment by cfeckardt** [comment]
Any news on supporting this?

My use case is to produce view of an audit trail for all documents belonging to a customer. I.e all documents that have (or had) `customer-id` set to a given value.

cc: @hraberg

**Comment by refset** [comment]
After some discussion on the Clojurians Slack #crux channel I think we have resolved a solution for @cfeckardt, which is to more explicitly associate "events" to entities prior to submission (potentially using a transaction function).

However, a more general solution could involve a new history API supported by a combination of reversed `ecav` and `entity+vt+tt+tx-id->content-hash` indexes that efficiently solve the requirement: "show me all the entities and times where a given av is found". We have no immediate plans to create such indexes but it would be interesting to know if there are more use-cases.

**Comment by bortexz** [comment]
Hi @refset , I would be interested to know more about the solution mentioned above about associating events to entities prior to submission, I think it might be what I need.

 In my use case, I want to backtest and audit trading algorithms, and it would be very useful to get a query that returns me updates for things like orders and position, sorted by valid-time. I find that currently, xtdb is great at getting a "current state at time X" using valid-time if you use an approach where 1 order = 1 entity, but I can't find a simple way to get updates for such entities as valid-time moves forward, unless I do it in a discrete way (give me state at X, X+1, X+2,..) or getting history for individual entities.

It seems that having events for each entity could work for the situation where you want to stream things as they happened moving forward, 

Would this be the current best approach for audit trails? Does an event contain all info about the entity, like a duplication with it's own entity-id?

**Comment by refset** [comment]
Hi @bertofer - please feel free to email me if you'd like to talk this through sometime (jdt@juxt.pro) - the solution I alluded to previously might look something like:
```clojure
(xt/submit-tx node [[::xt/put {:xt/id :order-foo :state :unconfirmed} #inst "2021-11-06"]
                    [::xt/put {:xt/id :event-log-1 :modified #{:order-foo}}  #inst "2021-11-06"]
                    [::xt/put {:xt/id :position-bar :state :open} #inst "2021-11-07"]
                    [::xt/put {:xt/id :event-log-1 :modified #{:position-bar}}  #inst "2021-11-07"]
```
You can then use the `entity-history` API with `:event-log-1` and pass the `:modified` IDs into one or more point-in-time queries to perform joins. You may also be interested to see the patterns at play in this test namespace:
https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/bench/src/xtdb/bench/ts_devices.clj#L187-L253

The ability to expose all bitemporal data for first-class querying is very actively on the roadmap, but it's not ready for a wide audience just yet.
