### ISSUE TITLE
Improve Rules Docs

### ISSUE THREAD

**Issue by naomijub** [xtdb/xtdb#1203]
I understand that rules were created after issue https://github.com/juxt/crux/issues/10. However, from the [docs](https://www.opencrux.com/reference/queries.html#rules) context I cannot understand which is their purpose. 

For me this is important so I can maximize transistor's compatibility with rust types https://github.com/naomijub/transistor/issues/70.

**Comment by refset** [comment]
Hi @naomijub - @AlistairONeill did some great work on improving the query docs earlier this year, including deeper explanation on how rules are structured and can be used. Is there anything still missing in your opinion?

**Comment by naomijub** [comment]
Hi @refset I will take a look after my vacations. Thanks
