### ISSUE TITLE
Latest 'crux.api/entity' does not coerce 'eid' parameter to valid Entity Id.

### ISSUE THREAD

**Issue by jplodge-pro** [xtdb/xtdb#1208]
Hi Team, 

We are upgrading to the latest from an old version (a big jump too) and noticed that `crux.api/entity` no longer coerces the `eid` to an Entity Id. I found nothing in the Release Notes between the versions indicating functionality has been removed and the docstring still infers coercion. So, it looks like a regression to me, but I am happy to be corrected on this.

Old CRUX Version: `[juxt/crux-core "20.03-1.7.1-alpha"]`
New CRUX Version: `[juxt/crux-core "20.09-1.12.1-beta"]`

To reproduce:
```clojure
(def node (atom nil))

(defn db-setup [f]
  ;; For old Crux Version, use the following node creation.
  ;; (reset! node (crux/start-node {:crux.node/topology :crux.standalone/topology}))
  (reset! node (crux.api/start-node {}))
  (f)
  (.close @node)
  (reset! node nil))

(use-fixtures :each db-setup)

(deftest crux-investigation-test
  (let [[e1 :as data] [{:crux.db/id :one :value "ONE"}]
        tx (mapv #(vector :crux.tx/put %) data)
        tx-rpt (crux.api/submit-tx @node tx)]
    (crux.api/await-tx @node tx-rpt)

    (testing "verify that `entity` using eid succeeds"
      (is (= e1
             (crux.api/entity (crux.api/db @node) :one))))

    (testing "verify that `entity` using coercible eid returns nil"
      (is (nil? (crux.api/entity (crux.api/db @node) ":one"))))))
```

**Comment by refset** [comment]
Hi @jplodge-pro,

Indeed we do still describe coercion in the docstring. For reference:
```clojure
(entity [db eid]
    "queries a document map for an entity.
    eid is an object which can be coerced into an entity id.
    returns the entity document map.")
```

Unfortunately though it seems that the changes made to add support for string IDs (released in https://github.com/juxt/crux/releases/tag/20.07-1.10.0) overrode this particular `string -> keyword` coercion path, which didn't get reflected in the docs or release notes - sorry about that!

Are you able to work around the issue? We might be able to devise some options for ~restoring the old behaviour, if necessary.

**Comment by jplodge-pro** [comment]
Hi @refset ,
It's not a problematic issue for us. 
In fact, it was some Crux proving tests that were affected, and thus brought the issue to light, post-upgrade.  I raised this issue in case it was a regression, or the docstring needed updating. Either resolution is fine by me.

**Comment by refset** [comment]
Ah, good to know. I've added a card to the board to review coercion behaviours and make sure the docstrings are sufficiently accurate. Thanks for bringing it to our attention!
