### ISSUE TITLE
open-tx-log includes the tx specified by after-tx-id

### ISSUE THREAD

**Issue by jacobobryant** [xtdb/xtdb#1210]
I just upgraded to 20.09-1.12.0-beta, and I noticed that when calling `open-tx-log` with a non-nil `after-tx-id`, the results include the transaction with the ID I gave instead of starting right after it. Here's a snippet from my app:

```clojure
(defn tx-log* [{:keys [node after-tx with-ops]
                :or {after-tx nil with-ops false}}]
  (let [ret (crux/open-tx-log node (some-> after-tx long) with-ops)]
    (u/pprint [:tx-log* (some-> after-tx long) with-ops (iterator-seq ret)])
    ret))
```
Output:
```
[:tx-log*
 45
 false
 ({:crux.tx/tx-id 45,
   :crux.tx/tx-time #inst "2020-10-28T22:30:30.972-00:00",
   :crux.tx.event/tx-events
   [[:crux.tx/put
     #crux/id "3b605bd3386c5030aab5d3f139fdcb6bfa9153c9"
     #crux/id "34da7275cd259204fa1760fad11b3f218df140ca"]]}
  {:crux.tx/tx-id 46,
   :crux.tx/tx-time #inst "2020-10-28T22:31:37.800-00:00",
   :crux.tx.event/tx-events
   [[:crux.tx/put
     #crux/id "3b605bd3386c5030aab5d3f139fdcb6bfa9153c9"
     #crux/id "8449fe413c4535bce00f7ec22cfae36b5dcea624"]]})]
```

Including the specified tx would be fine too; the docs would just need to be updated in that case (perhaps call the param `start-tx-id` instead of `after-tx-id`).

**Comment by refset** [comment]
Hey! I think this is the same as a known issue with 1.12.0. See the release notes for 1.12.1 and please give it a try: https://github.com/juxt/crux/releases/tag/20.09-1.12.1

**Comment by jacobobryant** [comment]
Ah, perfect. That fixed it, thanks.
