### ISSUE TITLE
Slow queries NPE

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1223]
slow-queries has been throwing an async NPE, recently become visible due to #1217

https://app.circleci.com/pipelines/github/juxt/crux/1567/workflows/82ce975e-ab3c-416d-93ef-01c17d725b05/jobs/6286

**Comment by danmason** [comment]
Seems to be a fairly intermittent issue - I've yet to see the problem locally, and not seen it as a constant on CI. In terms of what appears to be happening, issue lies on this line:
`(Duration/between (.toInstant ^Date started-at) (.toInstant ^Date finished-at))`

Leads me to believe that for some reason, a query going into `slow-query?` doesn't have one of these keys set/it's returning nil.

`slow-query?` is called inside of `swap-finished-query`, and gets passed a query which is a merge between a completed/failed query and it's `in-progress` values (containing the query itself, and the `started-at` value) - makes me wonder if `swap-finished-query!` is getting called on a query which has already been removed from `in-progress`? A fix might be to check if `(get-in queries [:in-progress query-id])` actually returns anything before checking if it is a slow query - though really we should try to figure out why `swap-finished-query!` is getting called on something no longer in `in-progress` anyway.

**Comment by jarohen** [comment]
Reasonably confident that this would also be resolved by the fix in #1228, will close for now.
