### ISSUE TITLE
Upgrade Kafka (client and embedded) to 2.6.0 

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1231]
(original note by @refset)

* read changelog
* run tests, check against soak
* ensure that 2.3.0 Kafka topics are still readable with 2.6.0 (they _should_ be, but please explicitly check)

**Comment by danmason** [comment]
Useful place to sanity check for big changes: https://kafka.apache.org/26/documentation.html#upgrade

**Comment by danmason** [comment]
Current status on this:
- Need to pick through changelog more thoroughly, but I can't say anything particularly problematic lurking in their on an initial scan.
- There was one things within the changelog that impacted our usage of the API, though this caused us to fail tests and has been fixed
- Running through soak on an upgraded kafka now - checking all appears to work fine.
- Ingested some data on the dev node with 2.3.0 kafka, then upgraded the node, everything seems to read out just fine.
