### ISSUE TITLE
Bump to Nippy 3.1

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1232]
* Check changelog
* Check tx-logs written under Nippy < 3.x are still readable with Nippy >= 3.x

**Comment by danmason** [comment]
To summarize what we read earlier: upgrade to Nippy changes semantics of freezing, so freeze allows everything by default and thaw is restrictive. I think we should basically set the freeze allow list) to be equal to that of the current  thaw list, but im not sure how best to go about that

In direct calls to `nippy/freeze` or `nippy/thaw you` can pass that in as an option -  though in most places we do use nippy, we use lower level nippy functions or fast-freeze/fast-thaw where you'd have to rebind the var or something like that yourself instead.

One option I could see is completely overriding the var in nippy (using, say, alter-var-root) but not sure on where that should live or if thats a good thing to be doing. Could alternatively replace all usages of nippy freeze calls to crux-codec/crux-io functions calling down to nippy on their behalf where we do the necessary rebinding, though I imagine that could wind up taking a lot of time across all those calls

**Comment by danmason** [comment]
Made a quick draft PR on the bump change so far - added a call to `alter-var-root` to set the freeze allow-list to the thaw allow-list, plus a subsequent quick fix to a test.
