### ISSUE TITLE
Do not check whether docs already exist prior to index write

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#1251]
Currently the `KvIndexStore` in `index-docs` checks to see if docs exist prior to writing. 

Testing locally with a microbench, we can observe the deduping is tax, but it signifcantlly rises based on data-volumes. When a node is substantially loaded up, we've observed a 2X speed up by removing this check - courtesy of @refset. 

It is worth considering that in real usage of Crux, the deduplication in the Crux code won't buy us much, as users will likely not often be submitting duplicate documents. It's also worth considering that Rocks itself could a better deduplication job than we can.

To remove our duplication isn't trivial however, as the stats rely on us knowing what unique docs have been added. Therefore we need a substitute mechanism for computing stats. 

I can see we need unique-docs, for both `bytes-indexed` and `attribute-stats`.

**Comment by jarohen** [comment]
marked blocked on #1252

**Comment by jarohen** [comment]
fixed in ac6514ce6c7e8e274fcabf134ccfa7637cd326a1, for #1683
