### ISSUE TITLE
Deprecated metadata incorrectly set in crux.api

### ISSUE THREAD

**Issue by SevereOverfl0w** [xtdb/xtdb#1293]
https://github.com/juxt/crux/blob/62e11dd5123c5571737c51a3e81c02860e4ad6b3/crux-core/src/crux/api.clj#L39 is not valid, should be `^{:deprecated true :tag crux.api.ICruxDatasource}` instead.

**Comment by jarohen** [comment]
happy to update, although enlighten me why it's not valid?  :)

**Comment by SevereOverfl0w** [comment]
My mistake, I thought codox gave me the raw metadata.  But that's perfectly valid syntax (which for some reason I thought it wasn't!).  codox actually does a select-keys and removes the `:tag` which is what confused me.
