### ISSUE TITLE
Improve the join order with index stats

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1296]
- keeping stats on the number of distinct values for an attribute

**Comment by jarohen** [comment]
to discuss current situation with @hraberg

**Comment by hraberg** [comment]
There are a couple of issues / approaches:

1. Start by fixing the stat writing we have.
2. Move to HLL for unique counts instead. There's an issue on where to store these.
3. Maybe also add CountMin for frequency and intersection estimates.

There are several other ideas in this space, but maybe to unblock this, we can start with the above.
