### ISSUE TITLE
Document cloud deployment scripts

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#131]
If @megakorre can make rough notes, I can work into the official documentaiton.

The idea is to give users the tools to deploy their own Crux stacks.

**Comment by jonpither** [comment]
Relates to xtdb/xtdb#1992

**Comment by megakorre** [comment]
renamed since we now are using a kubernetes setup.

**Comment by jarohen** [comment]
incorporating in xtdb/xtdb#386
