### ISSUE TITLE
Rocks JNR requires further defensive copies

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1330]
(from @hraberg) 

This backend doesn't currently work, as it requires defensive copies in `crux.kv.index-store` after calls to `key-suffix`. as the underlying buffers are only valid until the next call on the same iterator.

**Comment by hraberg** [comment]
This is a long standing question if we should support these JNR backends, `crux.rockdb.jnr` and `crux.lmdb.jnr` or not. The LMDB one doesn't have any practical benefits except removing the dependency on LWJGL, it behaves like the normal `crux.lmdb` backend more or less.

The general idea once was this: as Rocks JNR is faster than RocksJava, and we use JNR anyway, we could standardise on the JNR backends, and remove the LWJGL dependency and the official RocksJava JNI backend (though still depend on it for the native library), and hence consolidate on a JNR backend for both Rocks and LMDB.

IIRC buffers are valid throughout the iterators on LMDB, which is much easier to use in a zero-copy fashion, as one doesn't have to be defensive before one closes the iterators. In Rocks JNR one has to copy the buffer before using the iterator again, as the memory is tied to the iterator instance, not the underlying store (roughly). In LMDB, you more or less get a pointer straight into the underlying file.

So the wider issue here is kind of "should we drop the JNR backends once and for all?"

**Comment by hraberg** [comment]
It's also somewhat related to the regions discussion, as we would in theory want to be able to do as many defensive copies cheaply as we wish, and we often use `crux.memory/copy-to-unpooled-buffer` at any point we are worried there might be some buffer escaping from its scope and hence tying up the entire underlying chunk from being freed.

For this reason, we kind of don't want to add a (cheap) `crux.memory/copy-buffer` to all necessary places in `crux.kv.index-store`, at least not without spending time looking at memory usage. Using `crux,memory/copy-to-unpooled-buffer` there would be unnecessary slow. That said, this is the (current) approach involved making this work for JNR.

**Comment by refset** [comment]
JNR backends were removed in https://github.com/xtdb/xtdb/pull/1765
