### ISSUE TITLE
Lucene predicate function limited to 1000 results

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#1336]
This is before bitemp filtering/resolution. This may lead to some unpredictable query behavour.

**Comment by refset** [comment]
Another problematic aspect with the current default limit behaviour is that query times are longer than necessary for cases where the user only wants to take the first handful of results (via `:limit` or `open-q`) from a large result set (e.g. always pulling 1000 values out of Lucene when only the first 5 are ever needed/used). This could be viewed as an independent problem with it's own solution, but is relevant to think about should we consider adding a `limit` parameter to the Lucene predicates.
