### ISSUE TITLE
Not seeing latest value in query

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#135]
From Arne on the advisory group:

> Hi all,
> 
> I found a bit more time to try out Crux, here's an example where it inserts an entity, and then updates it at a later business time.
> 
> Querying using explicit business time works as I would expect, but when omitting the business time instead of getting the latest version, I'm getting the first version.
> 
> https://gist.github.com/plexus/1592a2cf5eb9b3cef5e080de0706c530
> 
> Is this expected, due to caching? How can I make sure the data I'm getting is up to date?
> 
> Thanks a lot,
> Arne

**Comment by hraberg** [comment]
I've tried Arne's gist and didn't manage to reproduce this myself. Also replied to the mailing list.

**Comment by jonpither** [comment]
@plexus I get "Picasso the great" for the last query in your gist. Is it worth ensuring you have the most recent Crux version etc? Try also a restart... see if that helps?

**Comment by plexus** [comment]
Thanks for checking, I'm also failing to reproduce it now. Will let you know if I encounter anything else that seems off.

**Comment by hraberg** [comment]
We're closing this issue for now until we have a way to reproduce it. Will create a new issue or reopen as soon as we do.
