### ISSUE TITLE
Talk / presentation request

### ISSUE THREAD

**Issue by amirouche** [xtdb/xtdb#1371]
Hello!

I am the organizer of the [FoundationDB meetup](https://www.meetup.com/fr-FR/FoundationDB-Paris-Meetup/). I would like to invite an expert about `crux` to present a talk at the meetup about `crux` in the coming months.

We gather around 19h00 [CET](https://time.is/fr/CET). If it is not practical for you to present live on google meet, we can gather questions in advance, and you can record the talk with something like [obs studio](https://obsproject.com/).

Let me know if you are interested :-)

**Comment by refset** [comment]
Hi :)

Thanks for reaching out - I would be delighted to present at your meetup in the near future.

I've already done some basic research on the possibility of using FDB as a KV index-store backend for Crux, and it's definitely a possibility though I suspect the query performance penalties would be quite large (compared to using Crux with embedded KV stores like RocksDB).

Using FDB as a document store or tx-log is definitely very plausible though, and I'm sure a discussion about bitemporal graph queries would be interesting to such an audience in any case.

Please send me an email to coordinate further, jdt@juxt.pro
