### ISSUE TITLE
Social media share buttons on blog posts

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1395]
* No social network scripts/trackers - most of them allow sharing by sending the user to a well-known URL
* Possible networks: Twitter, Reddit, LinkedIn, HN?
* I recall these being included as part of the original designs, will dig them out if required

**Comment by danmason** [comment]
Worth deciding on extra data we want to send on these links - for example, via the twitter 'intents' (https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent) you can provide various other parameters than just a share link (such as a `via`, to link to our social accounts, or `hashtags` etc)
