### ISSUE TITLE
Crux-lucene fails to index old stores

### ISSUE THREAD

**Issue by deobald** [xtdb/xtdb#1399]
https://opencrux.com/reference/21.01-1.14.0/lucene.html#_setup states that it is possible to "wipe the index directories for the Crux node and restart" to add `crux-lucene` to an existing database. This still seems to cause the `Lucene store latest tx mismatch` exception, however.

## Steps to reproduce:

1. Configure a Crux node without Lucene:

```clojure
  (letfn [(kv-store [dir]
            {:kv-store {:crux/module 'crux.rocksdb/->kv-store
	                      :db-dir      (io/file "data/dev/" dir)
                        :sync?       true}})]
    (crux/start-node
     {:crux/tx-log              (kv-store "tx-log")
	    :crux/document-store      (kv-store "doc-store")
      :crux/index-store         (kv-store "index-store")
      :crux.http-server/server  {:port 9999}}))
```

2. Add a record to the database with `(put record)`
3. Shut down the server
4. Add the `crux-lucene` dep: `[juxt/crux-lucene "21.01-1.14.0-alpha"]` ... update deps as appropriate (lein, etc.)
5. Add the `crux-lucene` config: `:crux.lucene/lucene-store {:db-dir "lucene-dir"}`
6. Wipe the index directory using `rm -rf ./data/dev/index-store`
7. Restart the service.
   * This will still produce `Lucene store latest tx mismatch`

**Comment by deobald** [comment]
A quick note: This also seems to occur when switching to the multi-field indexer (`:indexer 'crux.lucene.multi-field/->indexer`) from the default indexer. Deleting both the `index-store` and `lucene-store` still results in a `Lucene store latest tx mismatch` error after the switch.

**Comment by Aleksion** [comment]
Just hit this as well. 
I tried wiping the store as well, and that worked, until it got out of sync for some reason, leaving me right back where I started.
