### ISSUE TITLE
Lucene: `lucene-text-search` raises an ugly error when Crux node contains zero docs

### ISSUE THREAD

**Issue by deobald** [xtdb/xtdb#1401]
## Steps to reproduce

1. Configure a Crux node with Lucene in "multi-field" mode:

```clojure
:crux.lucene/lucene-store {:db-dir "lucene-dir"
                                 :indexer 'crux.lucene.multi-field/->indexer}
```

2. Search using `lucene-text-search`:

```clojure
'{:find [?e]
                     :in [?match]
	                   :where [[(lucene-text-search "filename:%s" ?match) [[?e]]]
	                           [?e :crux.db/id]]}
```

3. Lucene will throw an exception, complaining about "no segments" because there are no indexes yet:

`no segments* file found in MMapDirectory@/service-goes-here/data/dev/lucene-dir lockFactory=org.apache.lucene.store.NativeFSLockFactory@400bc6ce: files: []`

## Expected behaviour

It would be nice if the `lucene-text-search` behaviour was symmetrical with `text-search` and `wildcard-text-search` (simply returning zero results). Alternatively, `lucene-text-search` could throw an exception which makes the bad state (zero documents) more obvious and Crux-specific.

**Comment by jonpither** [comment]
Returning zero seems sensible! Will look to make this change soon.

**Comment by jonpither** [comment]
Not sure whether to catch the IndexNotFoundException or to index something into the store when we first fire up the module.
