### ISSUE TITLE
Documentation (reference) issue: DataScript -> Datalog ?

### ISSUE THREAD

**Issue by cocevk** [xtdb/xtdb#1402]
In the document about queries (https://opencrux.com/reference/queries.html) you mention DataScript, but (IMHO) it should really be Datalog?

**Comment by jarohen** [comment]
Hey @cocevk - thanks for getting in touch :wave: In this case, we are talking about differences specifically from DataScript's flavour of EDN Datalog, rather than Datalog as a whole - we could certainly make the distinction clearer, though.

Cheers,

James
