### ISSUE TITLE
Asychronous indexing for crux-lucene

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#1426]
The behaviour of crux-lucene currently relies on synchronous indexing alongside the main KV index store, where both stores are updated at the ~same time within the ingestion thread. This is a pragmatic design and the strong consistency behaviour is often desirable, but it limits the maximum ingestion throughput.

Asynchronous indexing could enable:
- (re)building of search indexes without also requiring rebuilding of the main KV index store
- delayed local I/O to avoid contention with the indexing thread
- use of networked/distributed search indexes

New API options would be necessary to allow the user to specify whether a query should:
1. tolerate stale Lucene indexes if there is a lag (which is likely), or
2. block until the index is sufficiently caught up (subject to a timeout), or
3. abort entirely if there is any lag (perhaps within some bound?)

The pattern for this could inform other kinds of secondary indexes in future, and might even be relevant when thinking about the possibilities for multi-instance queries.

**Comment by nivekuil** [comment]
+1, one use case that would be unlocked here is adding additional fields to the Lucene doc based off of out-of-band information (e.g. popularity). And as an example of one of those other kinds of secondary indexes, one might want to keep track of aggregations like association counts, stored as some sketch data structure (https://datasketches.apache.org/) while making use of other crux facilities like checkpoints.
