### ISSUE TITLE
Remove Dependency on com.stuartsierra/dependency

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#143]
This is a 161 line library we use to help calculate the join order. Should be easy to rewrite the parts we need (probably 50 lines or so). There's nothing urgent about this, but it's a needless dependency. It was added to get some sanity in the join order way back when it was more complex than it is now. To be fair, some of that complexity is dealt with by this library.

**Comment by hraberg** [comment]
Also, see this issue, not sure if that is directly relevant to us though:
https://github.com/stuartsierra/dependency/issues/6

But it implies that this fork is somewhat more evolved:
https://github.com/weavejester/dependency

**Comment by hraberg** [comment]
These are also potentially relevant, in case we can leverage more of them somehow:
https://github.com/aysylu/loom
https://github.com/Engelberg/ubergraph

But no reason to do that just for the sake of it.

**Comment by hraberg** [comment]
The matrix spike doesn't use this, so it might go away by itself at some point, so closing this. Not worth fighting with.

**Comment by SevereOverfl0w** [comment]
Clip has an implementation of Tarjan's algorithm which is copyrighted to JUXT. https://github.com/juxt/clip/blob/fb7ed99d455923279c608aadd3477ec62b639adb/src/juxt/clip/impl/core.cljc#L4-L62

This can be used for finding the topologically sorted order of a graph, and at the same time detecting whether they are cyclic. They are cyclic if a strongly-connected component is >2. You can probably tweak the algorithm to throw immediately upon inserting into a strongly connected group.
