### ISSUE TITLE
Improve basic :in arg query performance

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#1446]
Bound `:in` arguments should ideally be as fast as literals embedded in queries.

Failing slowdown test showing ~50% performance hit: https://github.com/refset/crux/commit/617079c58d368de1c667bbc9d4684abc3bd83fef#diff-6c6576892a723f0244c94ef6f4ce3132aa1d8e6280f07a59e2d90c7580eef6a4R3721-R3748

**Comment by jarohen** [comment]
@refset looks like this slowdown goes away if you run the queries in the opposite order? suggests the difference is the caches being warmed up on the latter query - might be worth trying this on two fresh nodes

**Comment by refset** [comment]
Ah yes, good point - that would probably explain it!

> might be worth trying this on two fresh nodes

Definitely, and we should probably refactor the other slowdown tests similarly (I pretty much just copied the structure of one of the existing tests).

**Comment by refset** [comment]
Having reviewed the other existing slowdown tests I don't think this warm-cache effect would invalidate any of the results, given both the low result counts and large discrepancies involved, so I'm close this for now as there's nothing urgent to be done. Introducing a new fixture and/or `query_slowdown_test.clj` to mitigate the effect is perhaps worthwhile in future.
