### ISSUE TITLE
Sync extremly slow when jdbc used

### ISSUE THREAD

**Issue by beetleman** [xtdb/xtdb#1463]
I using crux in this configuration:
```clojure
{:crux.jdbc/connection-pool {:dialect   {:crux/module
                                         'crux.jdbc.psql/->dialect}
                             :pool-opts {:maximumPoolSize 100}
                             :db-spec
                             {:jdbcUrl
                              "jdbc:postgresql://localhost:6432/postgres"
                              :user     "postgres"
                              :password "postgres"}}
 :crux/index-store          {:kv-store
                             {:crux/module 'crux.rocksdb/->kv-store
                              :db-dir      (io/file
                                            "crux/index")}}
 :crux/tx-log               {:crux/module     'crux.jdbc/->tx-log
                             :connection-pool :crux.jdbc/connection-pool}
 :crux/document-store       {:crux/module     'crux.jdbc/->document-store
                             :connection-pool :crux.jdbc/connection-pool}}

```
versions:
```clojure
juxt/crux-core{:mvn/version "21.02-1.15.0-beta"}
juxt/crux-rocksdb{:mvn/version "21.02-1.15.0-beta"}
juxt/crux-jdbc{:mvn/version "21.02-1.15.0-beta"}

;; JDBC
org.postgresql/postgresql{:mvn/version "42.2.19"}
```

and  `crux/sync` for new node is slower than it should be. I checked execution plan for doc fetching query and it do not use index, crux have index https://github.com/juxt/crux/blob/master/crux-jdbc/src/crux/jdbc/psql.clj#L31 but its for 2 fields. I added index for `event_key` and query now for ~100 docs improved from ~6s to ~10ms. I do not know how it transfer to other dialects but for postgres its huge difference.

**Comment by jarohen** [comment]
Hey @beetleman, thanks for the report :pray: I'm not sure why the index is ordered in that way, will check on the history and let you know.

**Comment by beetleman** [comment]
After quick look on code i think we should have both indexies:
```clojure
"CREATE INDEX IF NOT EXISTS tx_events_compacted_event_key_idx ON tx_events(compacted, event_key)"
"CREATE INDEX IF NOT EXISTS tx_events_event_key_idx ON tx_events(event_key)"
```
but I'm not SQL expert so somebody with more experience should look on this:D

**Comment by kevinmershon** [comment]
Even with the additional index, syncing/indexing new data with a postgresql backend is slow to the point of unusable, if `crux.lucene/lucene-store` is used

Follow-up edit:
Appears the slowness isn't JDBC related but entirely caused by this line: https://github.com/juxt/crux/blob/master/crux-lucene/src/crux/lucene.clj#L251

Will report a new issue

**Comment by jarohen** [comment]
Thanks @kevinmershon - have seen you've raised #1500 and #1501 too :pray: 

Re the original issue, have pushed the above commit this afternoon to fix the issue for new nodes, but we should consider the best way to apply this to existing Crux installations (hence the delay to this issue thus far, sorry). I doubt we want to 'just' apply a blanket migration on startup to all DB dialects, I don't know offhand which of our supported databases take out full table locks for this kind of thing and which don't, and hence I don't want to just straight-out impose it on our users. It might be preferable to announce this in release notes instead, along with suggested migrations, and let users decide what's best for their use case. :thinking:
