### ISSUE TITLE
Transaction function return values

### ISSUE THREAD

**Issue by malcolmsparks** [xtdb/xtdb#1480]
It would be useful to be able to return values from transaction functions, rather than only 'false', to indicate the cause of the rollback.

**Comment by malcolmsparks** [comment]
Also, if a transaction function cannot be found (via `api/entity`) then it would be nice to indicate this with an error message rather than the NPE that results.

**Comment by malcolmsparks** [comment]
Also, how is it possible to determine whether the submitted transaction succeeded or not? The result of `await-tx` doesn't indicate this.

**Comment by jarohen** [comment]
Hey @malcolmsparks :wave: 

> It would be useful to be able to return values from transaction functions, rather than only 'false', to indicate the cause of the rollback.

If you throw an exception out of the transaction function then this should get logged (it's a warn-level log in `crux.tx`) - although were you thinking having this returned from the Crux API somehow?

> Also, if a transaction function cannot be found (via api/entity) then it would be nice to indicate this with an error message rather than the NPE that results.

Agreed, yep - could potentially be solved in a similar way to the above.

> Also, how is it possible to determine whether the submitted transaction succeeded or not? The result of await-tx doesn't indicate this.

`crux/tx-committed?` should help you there, after you've awaited the tx

Cheers :)

**Comment by malcolmsparks** [comment]
Throwing an exception in the tx function is something I didn't think of, thanks!
