### ISSUE TITLE
Benchmark / Long Running Tests Framework

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#149]
We want to create a simple framework that can handle ingestion, optionally keep the data around, and run the tests in a way that works both from lein or the REPL and in the cloud. New tests can then be added using this without having to reinvent the wheel every time.

The framework should also generate reports of times, space usage and potentially other useful metrics. In the cloud version, these can be uploaded to say S3.

@megakorre has already a stepping stone to this. Also somewhat related to xtdb/xtdb#2033 as these tests would all go via the Public API + any extra bench framework APIs.

**Comment by hraberg** [comment]
Related to xtdb/xtdb#31.

**Comment by hraberg** [comment]
Somewhat related to xtdb/xtdb#88 as it will be useful to monitor these test environments, capture useful logs from Crux during the run etc.

**Comment by megakorre** [comment]
I'll make the current bench runner able to run against multiple back ends and refactoring some of the code that is there now.
