### ISSUE TITLE
Add front page

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#15]

**Comment by shivekkhurana** [comment]
Do we have a "JUXT way" of creating static sites ?

**Comment by malcolmsparks** [comment]
No - use whatever you think best.

Once we have a need for a more dynamic site, we may host on our own website under a different hostname.

**Comment by shivekkhurana** [comment]
Okay. I'll write some react and es6 using gatsby and tachyons. This is the easiest thing for me.

**Comment by jonpither** [comment]
![001](https://user-images.githubusercontent.com/143601/42208366-f1d80b1e-7ea3-11e8-87a7-226fde305a42.jpg)
