### ISSUE TITLE
Lucene indexing process abysmally slow due to unnecessary commit call

### ISSUE THREAD

**Issue by kevinmershon** [xtdb/xtdb#1500]
When rebuilding the Lucene index from scratch for a small (~500 documents) crux node, the Lucene indexer is processing 1 transaction about every ~750-1000 ms. I hunted it down and it's caused by this unnecessary commit line:

https://github.com/juxt/crux/blob/master/crux-lucene/src/crux/lucene.clj#L251

Removing it in my local copy brought the average index time to ~2-3 ms per document and writes are still being committed/flushed to disk with regularity.

**Comment by refset** [comment]
As further context for anyone looking at this issue that doesn't happen to click on the PR, please see my response there: https://github.com/juxt/crux/pull/1501#issuecomment-821294963

tl:dr; this is a known issue and somewhat unavoidable until `crux-lucene` supports checkpointing (https://github.com/juxt/crux/issues/1221) and/or async indexing (https://github.com/juxt/crux/issues/1426), but there are some options discussed in the comment!

**Comment by kevinmershon** [comment]
Proposed changes using a 50ms debounce for last tx write are here: https://github.com/kevinmershon/crux/commit/2aec8955862ea59dad12e5d2143ea1470670221b

This is what we will be using until you guys have the checkpointing stuff sorted.

**Comment by jarohen** [comment]
Hey @kevinmershon - this has been merged and released into `"1.18.0-rc1"` - could you take a look and let us know whether this fixes your issue?

Included in this release is a Lucene index bump (similar to standard Crux version bumps) which will require removing your Lucene directory and letting it re-index from the transaction log.

Cheers,

James
