### ISSUE TITLE
Crux node hangs indefinitely during entity retrieval when after starting with existing persistent index-store (RocksDB)

### ISSUE THREAD

**Issue by rowlandwatkins** [xtdb/xtdb#1516]
Hi folks,

Firstly, I'd like to say how cool this project is - I have a background in Semantic Web technology and have been looking for something that was more natural for RDF storage (hopefully quads and named graphs in the future!), besides an RDBMS triplestore.

I've been playing around with Crux using Kafka for tx-log and document-store, together with RocksDB (local-document-store and index-store). This has been packaged into a docker container with an appropriate config.edn (attached).

Upon *initial* startup (no persisted index-store), I can perform submit-tx and retrieve entities as expected.

However, I've noticed that after removing old versions of the docker containers instances and deploying a new one (different deps.edn), with the same persisted RocksDB index-store, something odd happens:

- any entity retrieval will hang indefinitely, whether using the clojure API or REST API
- history retrieval still works
- shutting down the container takes > 10 seconds and outputs the warning: "could not stop node cleanly after 10000ms, forcing exit"

Even more interesting, there's a partial solution to this (on a per-entity basis):

- save a new version of the original entity (submit-tx)

This seems to trigger storage into Kafka and then immediately the hanging entity function will complete. Note this must be done for each entity request made to the crux node.

I've additionally tried running sync after starting up the docker container with an existing persistent index-store from my REPL and REST API, but this does not help.

Given that in this situation there is an existing persistent index-store and what appears to be a hanging thread, could Crux, on startup, be expecting tx updates from Kafka, but doesn't get any and waits indefinitely?

I've attached my Crux node configuration (crux.example.edn.txt) for reference. I can also confirm that I'm not using any custom code just the crux.cli: clojure -m crux.main in my Dockerfile.

For the time being I've disabled RocksDB for both local-document-store and index-store and just using the in-memory kvstore. I'd really like to have RocksDB as the index-store though.

Any hints/pointers for overcoming this obstacle would be most appreciated - it's entirely possible I've missed something that might help!

[crux.example.edn.txt](https://github.com/juxt/crux/files/6508225/crux.example.edn.txt)

Cheers,

Rowland

**Comment by jarohen** [comment]
Hey @rowlandwatkins, thanks for raising this :pray: 

> However, I've noticed that after removing old versions of the docker containers instances and deploying a new one (different deps.edn), with the same persisted RocksDB index-store

Quick question - could you confirm which containers you're removing/keeping here? If you're deleting the Kafka containers this would lead to the behaviour you're seeing. These are Crux's golden stores - removing the query indices is fine, they'll get rebuilt from the tx-log/document-store, but removing either of the tx-log or document-store is generally a recipe for a bad time :)

James

**Comment by refset** [comment]
Further to @jarohen's message, other points / questions...

> (hopefully quads and named graphs in the future!)

Thanks for calling those out specifically, you're not the first person to ask :) see https://github.com/juxt/crux/issues/317

> after removing old versions of the docker containers instances and deploying a new one (different deps.edn), with the same persisted RocksDB index-store

What about the RocksDB for the local-document-store? Is that persisted also?

Does anything different happen if you use the same RocksDB instance for the local-document-store _and_ the index-store? As per https://opencrux.com/reference/21.04-1.16.0/kafka.html#_sharing_the_local_kv_store

> Given that in this situation there is an existing persistent index-store and what appears to be a hanging thread, could Crux, on startup, be expecting tx updates from Kafka, but doesn't get any and waits indefinitely?

Something like that may well be happening, but I expect/hope that our logs would already have made that obvious (we might well need to add more logging!).

**Comment by jbourlo** [comment]
I also had this issue by doing the following using the latest Crux:

1. Start topology with Rocks index, Kafka docs, and Kafka tx log.  (Omit the local Rocks doc store cause [this ](https://opencrux.com/howto/confluent-cloud.html) doc didn't mention it)
2. Submit transactions.
3. Restart node.
4. Entity requests and pull's timeout.  Entity-tx succeeds.
5. Add local doc store, restart node.
6. Same timeout
7. Create all new local Rocks stores for index and docs.
8. Restart node
9. Successful entity and pull requests.

**Comment by rowlandwatkins** [comment]
Hi @jarohen, @refset, thanks for your replies! My response will be quite lengthy, so I'll split this into several comments, focusing on the following:
1. Kafka, RocksDB
2. LMDB
3. Switching between persistent index-stores at runtime

## Kafka, RocksDB
> Quick question - could you confirm which containers you're removing/keeping here? If you're deleting the Kafka containers this would lead to the behaviour you're seeing. These are Crux's golden stores - removing the query indices is fine, they'll get rebuilt from the tx-log/document-store, but removing either of the tx-log or document-store is generally a recipe for a bad time :)

So I did wonder at first if Kafka was causing the issue, because I originally deleted Zookeeper, Kafa, and Crux containers all at the same time using docker-compose:

```sh
docker-compose rm -v
```
In actual fact, removing the Kafka container using docker-compose (and keeping Crux running) does not affect Crux in any way (when using a persistent index-store). Consider the following scenario, using these attached crux, docker-compose and dockerfile. I've tried to make this as repeatable as possible to my current environment. 
[crux.rocksdb.edn.txt](https://github.com/juxt/crux/files/6529440/crux.rocksdb.edn.txt)
[docker-compose.yml.txt](https://github.com/juxt/crux/files/6529441/docker-compose.yml.txt)
[Dockerfile.crux.txt](https://github.com/juxt/crux/files/6529442/Dockerfile.crux.txt)

1. `docker-compose.yml` with Zookeeper, Kafka, and Crux.
2. Kicks off Zookeeper, Kafka, Crux, in order:
```sh 
docker-compose up -d
```
3. 
```Clojure 
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 1,
 :crux.kv/kv-store "crux.rocksdb.RocksKv",
 :crux.kv/size 39865,
 :crux.tx-log/consumer-state nil,
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? true}
```
4. Create entity `:rowland`:
```Clojure
core=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :rowland :description "lol"}]])
{:crux.tx/tx-id 0, :crux.tx/tx-time #inst "2021-05-22T07:52:58.161-00:00"}
```
5. Stop Crux container:
```sh
docker stop crux
```
Container exits cleanly.

6. Start Crux container:
```sh
docker start crux
```
7. Retrieve `:rowland` entity:
```Clojure 
core=> (crux/entity (crux/db node) :rowland)
{:description "lol", :crux.db/id :rowland}
```
8. Stop Kafka container:
```sh
docker stop kafka
```
9. Delete Kafka container:
```sh
docker-compose rm -v kafka
```
10. Check crux status. Note that Zookeeper is returned as not active:
```Clojure 
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 1,
 :crux.kv/kv-store "crux.rocksdb.RocksKv",
 :crux.kv/size 39865,
 :crux.tx-log/consumer-state nil,
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? false}
```
11. Retrieve `:rowland` entity:
```Clojure 
core=> (crux/entity (crux/db node) :rowland)
{:description "lol", :crux.db/id :rowland}
```
12. Recreate Kafka container with same data:
```sh 
docker-compose up -d kafka
```
13. Retrieve `:rowland` entity:
```Clojure
core=> (crux/entity (crux/db node) :rowland)
{:description "lol", :crux.db/id :rowland}
```
14. Stop Crux container:
```sh
docker stop crux
```
15. Delete Crux container:
```sh
docker-compose rm -v crux
```
16. Recreate Crux container, same persistent index-store:
```sh
docker-compose up -d crux
```
17. Check crux status:
```Clojure
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 16,
 :crux.kv/kv-store "crux.rocksdb.RocksKv",
 :crux.kv/size 122022,
 :crux.tx-log/consumer-state {"crux-docs-0" {:next-offset 1}},
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? true}
```
18. Retrieve `:rowland` entity:
```Clojure 
core=> (crux/entity (crux/db node) :rowland)
```
`crux/entity` hangs indefinitely.
19. Stop Crux container:
```sh
docker stop crux
```

Crux exits with "could not stop node cleanly after 10000ms, forcing exit".

20. Start Crux container:
```sh
docker start crux
```
21. Retrieve `:rowland` entity:
```Clojure
core=> (crux/entity (crux/db node) :rowland)
```
```sh
curl -X GET -H "Accept: application/edn" "http://localhost:8000/_crux/entity?eid-edn=:rowland"
```
Both `crux/entity` and `curl` hang indefinitely.

22. Update entity `:rowland`:
```Clojure
core=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :rowland :description "lol"}]])
{:crux.tx/tx-id 1, :crux.tx/tx-time #inst "2021-05-22T09:16:10.848-00:00"}
```

Both commands in 21 immediately return:
```edn
{:description "lol", :crux.db/id :rowland}
```
23. Stop Crux container:
```sh
docker stop crux
```
Crux exits cleanly.

Based on the above, I'm pretty certain the absence of Kafka is not an issue. Once we have a persistent index-store, creating a fresh Crux container appears to expect some data from Kafka on startup, hence the hang.

When we "feed" Kafka a new entity version (22), upon submit-tx, Crux's index-store mechanism reads from Kafka and updates the index-store, (a thread continues), and we complete the requests in 21.

**Comment by rowlandwatkins** [comment]
Hi @refset,

> What about the RocksDB for the local-document-store? Is that persisted also?

Yes, documented in here:
[crux.rocksdb.edn.txt](https://github.com/juxt/crux/files/6529440/crux.rocksdb.edn.txt)
>
>Does anything different happen if you use the same RocksDB instance for the local-document-store and the >index-store? As per https://opencrux.com/reference/21.04-1.16.0/kafka.html#_sharing_the_local_kv_store

I tried a crux.edn example using the same RocksDB instance for both local-document-store and index-store, but I did not see any different behaviour after recreating the crux container. As a further experiment, I tried using LDMB to see if this issue was a persistent index-store problem.

## LMDB

I also tried LMDB as the index-store (no local-document-store), I had the same results as above (removing the Crux container, leaving Kafka running all the time), and indefinite hang. We start off again with a clean docker-compose with no previous data. We will not remove Kafka in this example.
[crux.lmdb.edn.txt](https://github.com/juxt/crux/files/6529673/crux.lmdb.edn.txt)

1. `docker-compose.yml` with Zookeeper, Kafka, and Crux.
2. Kicks off Zookeeper, Kafka, Crux, in order:
```sh 
docker-compose up -d
```
3. Get Crux status, see we are using LDMB:
```Clojure
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 1,
 :crux.kv/kv-store "crux.lmdb.LMDBKv",
 :crux.kv/size 77952,
 :crux.tx-log/consumer-state nil,
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? true}
```
4. Create entity `:rowland`:
```Clojure
core=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :rowland :description "lol"}]])
{:crux.tx/tx-id 0, :crux.tx/tx-time #inst "2021-05-22T09:27:27.962-00:00"}
```
5. Retrieve entity `:rowland`
```Clojure
core=> (crux/entity (crux/db node) :rowland)
{:description "lol", :crux.db/id :rowland}
```
6. Stop Crux container:
```sh
docker stop crux
```
7. Delete Crux container:
```sh
docker-compose rm -v crux
```
8. Recreate Crux container, same LMDB-based index-store:
```sh
docker-compose up -d crux
```
9. Check Crux status:
```Clojure
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 14,
 :crux.kv/kv-store "crux.lmdb.LMDBKv",
 :crux.kv/size 98432,
 :crux.tx-log/consumer-state {"crux-docs-0" {:next-offset 1}},
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? true}
```
10. Retrieve entity `:rowland` using REPL and `curl`:
```Clojure 
core=> (crux/entity (crux/db node) :rowland)
```
```sh
curl -X GET -H "Accept: application/edn" "http://localhost:8000/_crux/entity?eid-edn=:rowland"
```
Both commands hang indefinitely.
11. Update entity `:rowland`
```Clojure 
core=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :rowland :description "lol"}]])
{:crux.tx/tx-id 1, :crux.tx/tx-time #inst "2021-05-22T09:33:29.081-00:00"}
```
Both commands in 10 return immediately:
```edn 
{:description "lol", :crux.db/id :rowland}
```
12. Stop Crux container:
```sh
docker stop crux
```
Crux exits with "could not stop node cleanly after 10000ms, forcing exit".

I think this goes some way to demonstrating that the hang issue isn't connected to a particular persistence module technology, RocksDB or LDMB.

**Comment by rowlandwatkins** [comment]
Hi @jarohen, @refset,

Thank you for your patience in reading this far!

We can go further, and show what happens when you switch index-store persistence modules: you will find that Crux will continue to work properly after the container is deleted then re-created. We start off again with a clean docker-compose with no previous data. We will not remove Kafka in this example.
[crux.lmdb.edn.txt](https://github.com/juxt/crux/files/6529673/crux.lmdb.edn.txt)
[crux.rocksdb.edn.txt](https://github.com/juxt/crux/files/6529440/crux.rocksdb.edn.txt)

1. `docker-compose.yml` with Zookeeper, Kafka, and Crux.
2. Kicks off Zookeeper, Kafka, Crux, in order:
```sh 
docker-compose up -d
```
3. Get Crux status, see we are using LDMB:
```Clojure 
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 1,
 :crux.kv/kv-store "crux.lmdb.LMDBKv",
 :crux.kv/size 77952,
 :crux.tx-log/consumer-state nil,
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? true}
```
4. Create entity `:rowland`:
```Clojure 
core=> (crux/submit-tx node [[:crux.tx/put {:crux.db/id :rowland :description "lol"}]])
{:crux.tx/tx-id 0, :crux.tx/tx-time #inst "2021-05-22T09:44:46.438-00:00"}
```
5. Retrieve entity `:rowland`
```Clojure 
(crux/entity (crux/db node) :rowland)
{:description "lol", :crux.db/id :rowland}
```
6. Stop Crux container:
```sh 
docker stop crux
```
7. Delete Crux container
```sh 
docker-compose rm -v crux
```
8. Recreate Crux container (using [crux.rocksdb.edn.txt](https://github.com/juxt/crux/files/6529440/crux.rocksdb.edn.txt)):
```sh
docker-compose up -d crux
```
9. Check Crux status (notice RocksDB)
```Clojure 
core=> (crux/status cx/crux-db)
{:crux.doc-log/consumer-state nil,
 :crux.index/index-version 17,
 :crux.kv/estimate-num-keys 14,
 :crux.kv/kv-store "crux.rocksdb.RocksKv",
 :crux.kv/size 138980,
 :crux.tx-log/consumer-state {"crux-docs-0" {:next-offset 1}},
 :crux.version/revision nil,
 :crux.version/version "21.04-1.16.0-beta",
 :crux.zk/zk-active? true}
```
10. Retrieve entity `:rowland`:
```Clojure 
core=> (crux/entity (crux/db node) :rowland)
{:description "lol", :crux.db/id :rowland}
```
11. Stop Crux container:
```sh
docker stop crux
```

Crux exists cleanly.

As you can see, changing the index-store persistence model appears to allow Crux to operate as intended during startup - retrieve all missing transactions from tx-log in Kafka. You can do this in any order: LMDB then RocksDB, or RocksDB then LMDB.

I could be very wrong, but this hints to me that something in Crux node startup tests to see if the persistent index-store might be out of date upon startup (in our case, recreation time), and blocks on getting new transactions from Kafka (hence the hang, possibly deadlock). Swapping the persistent index-stores shows that Crux is very keen to talk to Kafka, and won't hang if a) there's no existing persistent index-store, and b) there really is a new transaction to process (like when adding an updated entity).

Hopefully this is useful, as mentioned before, for the time being I'll use the in-memory index-store module, since we can recreate the index-store from Kafka on each start up, but it would be nice to have persistent modules too in the future.

**Comment by jarohen** [comment]
Hey @rowlandwatkins - thanks ever so much for this detailed repro, very much appreciated! :pray: 

I'll run through the steps in more detail and see what jumps out, will let you know.

James

**Comment by jarohen** [comment]
aha, tl;dr - think this would be solved by the docker-compose.yml file also preserving the `/tmp/crux-docs` dir.

----

I think I can see what's happening, here goes :smile: The main thing to run through here is the relationship between the various stores in Kafka - for historical reasons it's not as clean-cut for the Kafka document store (in particular) as for the other modules (both the Kafka tx-log, and the JDBC tx-logs/doc-stores) as crux-kafka has been around for much longer than the concept of the doc-store - initially, Crux was pretty much only Kafka! 

Specifically, what Crux needs from whatever doc-store you choose is a fast random access lookup of any given key - with Kafka topics we don't have this guarantee, so (for the doc-store) we keep a local cache (the 'local-document-store', LDS) of all the documents it's seen so far. The Kafka document store implementation then, when asked to fetch documents (e.g. for a call to `entity`), checks this local cache, rather than looking through the Kafka topic.

In terms of Crux's startup behaviour for the Kafka doc-store: 
* We check the latest cached doc-topic offset and then start indexing new documents from there. 
* However, this offset is stored in the query indices, not in the LDS (again, this is to preserve backwards compatibility, although after this issue I'd be tempted to look at keeping this with the LDS rather than with the query indices).  Normally, up til now, this hasn't been an issue but, in this case, this means that Crux thinks it's already up-to-date with the doc-topic, and so doesn't re-index the doc into the LDS.
* Due to #1479 (fixed in the upcoming release), in 1.16.0 the Kafka doc-store will hang if a requested document isn't present.
* Separately, in the next release we're also looking to remove this dependency on the doc-store for `entity` - this is #1512.

Right, so, https://github.com/juxt/crux/issues/1516#issuecomment-846702039 :
4. Document submitted to Kafka, consumed into LDS, indexed into query indices. 
7. Document retrieved from LDS, no problem
11. Document retrieved from LDS cache as this is still available
13. Likewise
15. Now the `/tmp/crux-docs` LDS cache has gone. 
16. We should re-index the LDS, but don't because the 'latest seen doc-topic offset' was preserved
18. Kafka doc-store hang
22. Doc now indexed into LDS, `entity` returns again.

As a test of this hypothesis, I'd try either preserving both or neither of the `/tmp/crux-docs` and `/tmp/crux-idx` dirs when you restart the Crux container - preserving both means that you'll have a full LDS; preserving neither means that Crux'll re-index the LDS on startup.

HTH!

James

**Comment by rowlandwatkins** [comment]
Hey @jarohen, thanks ever so much for the overview and details - indeed, deleting ```/tmp/crux-docs``` and ```/tmp/crux-idx``` works as expected.

I've also upgraded to 21.05-1.17.0 and with the form of failover already described, attempting to retrieve entities now results in ```nil```, rather than an infinite hang.

Give me a shout if there's anything else I can test at my end - this is an awesome system!

Cheers,

Rowland

**Comment by jarohen** [comment]
Will do - thanks! :pray:
