### ISSUE TITLE
Node out of sync error after calling await-tx - race?

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#1519]
(from @jacobobryant on Slack)

I've got some code that calls `submit-tx`, `await-tx`, and then `tx-committed?`. While importing data into a new app, I just got a NodeOutOfSyncException . Is this a crux bug?

https://github.com/jacobobryant/biff/blob/master/libs/crux/src/biff/crux.clj#L389-L392

```
May 27 19:57:14 findka-api run.sh[2007]: crux.api.NodeOutOfSyncException: Node out of sync - requested '{:crux.tx/tx-id 92, :crux.tx/tx-time #inst "2021-05-27T19:57:14.679-00:00"}', available '{:crux.tx/tx-time #inst "2021-05-27T19:57:13.513-00:00", :crux.tx/tx-id 91}'
May 27 19:57:14 findka-api run.sh[2007]: {:crux.error/error-type :node-out-of-sync, :crux.error/message "Node out of sync - requested '{:crux.tx/tx-id 92, :crux.tx/tx-time #inst \"2021-05-27T19:57:14.679-00:00\"}', available '{:crux.tx/tx-time #inst \"2021-05-27T19:57:13.513-00:00\", :crux.tx/tx-id 91}'", :requested {:crux.tx/tx-id 92, :crux.tx/tx-time #inst "2021-05-27T19:57:14.679-00:00"}, :available {:crux.tx/tx-time #inst "2021-05-27T19:57:13.513-00:00", :crux.tx/tx-id 91}}
May 27 19:57:14 findka-api run.sh[2007]:  at crux.error$node_out_of_sync.invokeStatic (error.clj:19)
May 27 19:57:14 findka-api run.sh[2007]:     crux.error$node_out_of_sync.invoke (error.clj:18)
May 27 19:57:14 findka-api run.sh[2007]:     crux.node.CruxNode.tx_committed_QMARK_ (node.clj:135)
May 27 19:57:14 findka-api run.sh[2007]:     biff.crux$submit_tx.invokeStatic (crux.clj:392)
May 27 19:57:14 findka-api run.sh[2007]:     biff.crux$submit_tx.invoke (crux.clj:376)
```

**Comment by jacobobryant** [comment]
Just reproduced it. The tx passed to crux was empty which I'm guessing is the cause. (so resolution might just be "don't do that")

**Comment by refset** [comment]
Nice, thanks for figuring that out. I've confirmed this reproduces it:

```clojure
;; e.g. in `crux.api-test`
(t/deftest empty-tx-can-be-awaited
  (when-not (contains? #{:remote} *node-type*)
    (let [tx (api/submit-tx *api* [])
          _ (api/await-tx *api* tx)]
      (t/is (= :foo [(api/latest-submitted-tx *api*) (api/latest-completed-tx *api*)] #_(api/tx-committed? *api* tx))))))
```

And doing it twice blocks indefinitely:

```clojure
(t/deftest empty-tx-can-be-awaited
  (when-not (contains? #{:remote} *node-type*)
    (let [tx (api/submit-tx *api* [])
          tx2 (api/submit-tx *api* [])
          _ (api/await-tx *api* tx2)]
      (t/is (= :foo [(api/latest-submitted-tx *api*) (api/latest-completed-tx *api*)] #_(api/tx-committed? *api* tx))))))
```

**Comment by jarohen** [comment]
Thanks both for the report and repro here :pray: The issue was that we weren't _fully_ storing the tx metadata required for `latest-completed-tx` in the case where there were no tx-events - this metadata changed when we changed the tx-basis to be tx-id in #1205.

@refset the two-await issue _was_ a race condition - can also be repro'd with a sleep between submit + await. There's two paths to await-tx - one if the node has already indexed the transaction in question, one if it hasn't and, in this case, your repro was exercising both.

Case where node hasn't indexed the transaction yet:
* `await-tx` is called, awaiting thread checks latest indexed tx, not recent enough yet. Parks awaiting `indexed-tx` bus messages.
* Bus message comes through, await-tx returns.
* Check latest-completed-tx, not updated correctly, :boom: 

Case where it has:
* `await-tx is called, awaiting thread checks latest-completed-tx, erroneously reported as not recent enough. 
* No further bus messages. so waits for as long as the specified timeout (indefinitely in this case)
