### ISSUE TITLE
Docker Getting Started Image

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#152]
Variant of our main Docker image that can be used to quickly get up and running and play with a standalone Crux node. Will have volumes so persistence can survive restarts.

**Comment by refset** [comment]
Most of the way there: https://github.com/juxt/crux/pull/156

**Comment by refset** [comment]
Solved by https://github.com/juxt/crux/commit/0784fa8fe56fe81d2d8e4c611e4a08bb7bbf076b, which simply reuses the existing image.
