### ISSUE TITLE
Order-by during pull

### ISSUE THREAD

**Issue by rowlandwatkins** [xtdb/xtdb#1525]
Hi folks,

I'm diving deep into querying and I'm looking at how to more efficiently load entities. I can already perform simple search with ```q```, together with ```entity``` to load the entire record. This is fine for single result retrieval, but less so for returning a collection - ```pull``` looks a lot more suitable. However, I'm not certain if there's a way to use order-by at the same time. Consider the following:

Sample data:
```edn
{:description "Leader of the ThunderCats", :age 24 :crux.db/id :lion-o}
{:description "Servant of the Ancient Spirits of Evil", :age 3000000 :crux.db/id :mumm-ra}
```
Pull-based query:
```clojure
(crux/q (crux/db db)
               {:find '[(pull ?char [:crux.db/id :description :age])]
                :where [[?char :crux.db/id ?uid]]})
```

This will return all data as expected, but the following throws a ```crux.IllegalArgumentException: Query didn't match expected structure```:

```clojure
(crux/q (crux/db db)
               {:find '[(pull ?char [:crux.db/id :description :age])]
                :where [[?char :crux.db/id ?uid]]
                :order-by [[:age :desc]]})
```
Although the above is not explicitly supported in the online docs, it follows the pattern of listing out the fields including the one for :age. I also tried the following but no success:

```clojure
(crux/q (crux/db db)
               {:find '[(pull ?char [:crux.db/id :description :age]) age]
                :where [[?char :crux.db/id ?uid]
                             [?char :crux.db/id age]]
                :order-by [[age :desc]]})
```

Any tips or if I'm trying something that isn't currently possible (I can always sort after getting the results) would be much appreciated!

Cheers,

Rowland

**Comment by jarohen** [comment]
Hey @rowlandwatkins - I'm afraid this isn't possible with `pull` as it stands. I would have guessed to use your final example - including `:age` as an explicit `:where` clause - will see what that's doing.

James

**Comment by jarohen** [comment]
Oh - it's got `[?char :crux.db/id age]`, guessing that should be `:age`? :wink:

**Comment by rowlandwatkins** [comment]
Hi @jarohen ,

I'm honestly not sure if ```:age``` or ```age``` should be used in the final example, I started trying different syntax to see if it would yield different results. Pull examples suggest that ```pull``` requires ```?``` in matched variables, with projection fields as keywords. Other query examples just have a variable name, so it could be me getting confused.

Cheers,

Rowland

**Comment by refset** [comment]
The `?` prefix for symbols representing logic variables is valid but is not significant/necessary (unlike other Clojure Datalog DBs where the prefix _is_ necessary). In general the team here has found the prefix to be superfluous (i.e. it's just syntax/visual noise) but various users may hold the opposite opinion. However, once you've made a decision about the prefix for a given query, you have to be consistent, since `?foo` and `foo` are not equivalent and will be treated as separate logic variables.

As for the docs, sorry for the confusion caused by our tests and docs examples applying the prefix inconsistently - we will look to fix this soon and document behaviour more clearly :slightly_smiling_face:

**Comment by jarohen** [comment]
Ah, sorry, my comment was more about the `:crux.db/id` attr - i.e.:

`[?char :crux.db/id age]` -> `[?char :age age]`

(deliberately not getting into the `?` discussion :wink:)

**Comment by rowlandwatkins** [comment]
Hi @jarohen @refset ,

Apologies for the delayed reply - I did get it all working after realising it was related to the single quotes in front of bound variables! 

Closing the issue, many thanks!
