### ISSUE TITLE
Data Explorer UI

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#154]
To demonstrate usage of bitemp in various processes in the banking domain. This can be a small web application, but it requires some data to be useful. Stretch goal could be to actually model several source systems and ingest them into Crux.

**Comment by hraberg** [comment]
As discussed on the call, time might be better spent on building several REPL based examples, but a single UI to browse and explore the data in Crux. See also xtdb/xtdb#2008 and xtdb/xtdb#145.

**Comment by hraberg** [comment]
Changing this card to be more inline with our latest thinking, we need a generic explorer for Crux which can co-exist with a REPL session.

Areas:
1. Bitemp visualisation.
2. Graph visualisation.
3. Queries.
4. Exploring the graph.

**Comment by comnik** [comment]
Sorry for dropping at random places here, but we are very interested in a more generic UI solution for schema management, basic entity administration (GDPR eviction!), some monitoring, etc... We will tackle this at some point, but right now it is out of scope. Might be beneficial to collaborate on this eventually?

**Comment by refset** [comment]
@comnik - somehow I only just saw your comment here, and I absolutely agree! It makes sense for us to reconnect soon now we've had a chance to test out 3DF from our side as well - I'll drop you an email.

Here are my notes from an initial brainstorming with @spacegangster today on this topic:
1. Generally use our efforts here to also showcase the cljs http wrapper and effective SPA Crux usage
2. Get the cljs http api tested and working for cljs, and sufficiently usable for js devs
3. Create a datafy and nav decorator for documents initially
4. Add CORS functionality to edge as an independent library (i.e. not simply extending `crux.ig`)
5. Extend `https://github.com/Lokeh/punk/` for Crux usage (e.g. an extra pane to manage connections, and persisted state) and include it in an edge-based project for easy distribution (maybe another container?)
6. Schema decorator
6.1 Inferring schema (types, attributes), evolution, statistics
6.2 Schema inference decorator stored in crux itself
7. Visualisation (e.g. neo4j, existing standalone example)
7.1. Graph as visual for connected schema
7.2. Graph of connected entities
7.2. Temporal graphs - also pagination over time, using nav-based decorator? (e.g. @spacegangster's "timeflow")
8. Maintain history of interactions & explore notebook-like functionality (e.g. nextjournal)
9. Table view (via inferred schema?), highlight gaps, show conformity (e.g. phpmyadmin)

We will work on developing all this in non-core namespaces as an evolving PR on `jt/109-datafy-nav`, with the edge project living under `/examples`.

I will create/update cards for 2-4 for now.
