### ISSUE TITLE
Try Building Graal Native Image for Crux

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#155]
We want to know if Crux can be built as a native image, and analyse what consequences that would have.

There are some usage of `eval` in Crux, and we also use Jetty, which might not work in the substrate VM. Usage of `eval` should be possible to remove, and Jetty can potentially be replaced with `http-kit` which is reported to work.

There might be other issues though, for example, JNR might not work well, as it also generates classes at run time.

Parts of Crux _might_ get faster in this mode, but the deployment should definitely become smaller, and would not depend on the JVM.

**Comment by hraberg** [comment]
There is both a leiningen plugin and a Clojure deps variant:
https://github.com/taylorwood/lein-native-image
https://github.com/taylorwood/clj.native-image

Though one does not strictly need a plugin to build the image which is simply an invocation to Graal.
His point mirrors mine in the original issue description:

> "The primary benefits to using a GraalVM native image are faster startup, lower memory requirements, and smaller distribution footprint (no JDK/JRE required). This doesn't necessarily mean the same code will run faster than it would on the JVM."


So again, we want to try it and see where the gap is, not go over top just to enable it. If the gap is small, it might make sense to close it and keep it closed.

**Comment by hraberg** [comment]
First issue:
> Error: Basic header file missing (<zlib.h>). Make sure headers are available on your system.

Solved locally on Ubuntu by `apt-get install zlib1g-dev`

**Comment by hraberg** [comment]
We next run into these two issues:
> Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported method java.lang.ClassLoader.defineClass(String, byte[], int, int) is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class

This first issue might be related to the below one, they're both early in `crux.main`, seemingly when loading `clojure.spec`:
> Error: unbalanced monitors: mismatch at monitorexit

Which seems to be this issue:
https://dev.clojure.org/jira/browse/CLJ-1472

**Comment by hraberg** [comment]
Potentially interesting, but might be a red herring:
https://github.com/oracle/graal/blob/master/substratevm/DYNAMIC_PROXY.md

**Comment by hraberg** [comment]
It's very easy to run into this issue when trying to build the native image:
https://github.com/juxt/edge/issues/22

A workaround is building under `/dev/shm/`

**Comment by hraberg** [comment]
Now failing on:
> Exception in thread "HotSpotGraalManagement Bean Registration" java.lang.OutOfMemoryError: Java heap space

**Comment by hraberg** [comment]
By targeting Clojure 1.9 one can get parts of the startup running. There seem to be two main issues:

1. Code using reflection, require (at least for AOT Clojure) or eval in an non-obvious or non expected way.
2. When issues like that come up, Graal tends to just sit and start consuming 100% CPU and eventually OOM. You get no real feedback on what's wrong and have to kill Graal, and have to slowly bisect the code to find the line causing the issue.

I've removed all usage of eval, and added a reflection JSON file for Graal so it can do reflection on a predefined set of classes (at least that's how I think it's supposed to work). We use reflection to dynamically load the `KVStore` and also the `ObjectStore`. Kafka, if we can get that far, will use it to load its serializers, so have replaced them with Java classes and reflection meta data.

I could not get `logback-classic` to work, there is an issue on Graal saying it also needs extensive reflection configuration, so fell back to `slf4j-simple` for the Graal profile, can revisit later when other more important thing starts to work.

My impression is that it's worth keep testing with newer Graal builds every now and then, and hopefully Clojure 1.10 starts working at least at some point. There are some issues on Graal around it just hanging like I describe above, and hopefully some of that will replaced with actual error messages telling you what's wrong.

One problem is that you often want to do certain things when in Graal mode, and certain when you're not, but haven't found a good way to deal with this,as things like this often depend on the dynamic nature of Clojure to start with. One approach is to have a more static `crux.bootstrap.graal` that by-passes a lot of the dynamic stuff to get Crux started.

JNI might be an issue, I think RocksJava does load, but haven't gone as far as managing to open a `KVStore` and actually use it.

**Comment by hraberg** [comment]
Useful links:
https://www.innoq.com/en/blog/native-clojure-and-graalvm/
https://github.com/taylorwood/lein-native-image
https://www.graalvm.org/docs/getting-started/

**Comment by hraberg** [comment]
Reference to `logback` issue mentioned above:
https://github.com/oracle/graal/issues/807

**Comment by hraberg** [comment]
I can't find any reference to this, but my impression is that things lock up when building when trying to call Protocols methods. Not sure if that's the actual root cause though.

**Comment by hraberg** [comment]
Seems like above theory is a red herring, attempted creating a small record with a protocol without issues.

**Comment by hraberg** [comment]
Been gone back and forth on this, but now feels like spec might be an issue. Another issue might that I simply don't have enough RAM to do the full build.

**Comment by hraberg** [comment]
Kafka clients doesn't seem to work without patching. bug in Graal related to method handles:
https://github.com/oracle/graal/issues/532

**Comment by hraberg** [comment]
LMDB, or rather LWJGL, isn't working either, here are a few issues discussing it:
https://github.com/oracle/graal/issues/438
https://github.com/oracle/graal/issues/304

**Comment by hraberg** [comment]
Not sure if the root cause or if it helps trigger it, but using multi methods didn't work, took time to find, was reported as an attempt of accessing a non existing proxy class during native image build.

**Comment by hraberg** [comment]
Actually, the above might not be true, issue persists after changing from multi methods, so is likely something inside the methods.

**Comment by hraberg** [comment]
As can be seen above Standalone mode now can start in the Graal native image. There are issues around protocols at times, and they do show up as the proxy class issue. Using `crux.api` doesn't work for example, and I had to do a direct interface call to one function inside `crux.tx`. There's a circular dependency at run time between some components there, which might be what is confusing Graal.

LWJGL LMDB doesn't work and JNR doesn't work, so the RocksJava backend is the only real backend that does work. The LocalNode cannot be started due to the Kafka issue in Graal here:
https://github.com/oracle/graal/issues/532

Solving this either requires patching Kafka or waiting until a new version of Graal that fixes the above is available. At the moment the latter is more pragmatic as we've done some headway. Will close this card and create a new one for that work.

**Comment by den1k** [comment]
For reference, https://github.com/borkdude/datalevin-native/issues/1
