### ISSUE TITLE
juxt/crux-standalone-rocksdb fails with "HTTP ERROR 500 Malformed text/html in :muuntaja/encode"

### ISSUE THREAD

**Issue by NodeGuy** [xtdb/xtdb#1551]
I'm trying to get started with Crux quickly with durability so I tried the following Docker image I found on the Hub:

`docker run -d -p 3000:3000 -v $(pwd):/var/lib/crux juxt/crux-standalone-rocksdb:21.05-1.17.0`

Visiting `localhost:3000` in my browser redirects to http://localhost:3000/_crux/query and produces the following error:

```
HTTP ERROR 500 Malformed text/html in :muuntaja/encode
URI:	/_crux/query
STATUS:	500
MESSAGE:	Malformed text/html in :muuntaja/encode
SERVLET:	-
Powered by Jetty:// 9.4.36.v20210114
```

Doing the same with the `juxt/crux-in-memory:21.06-1.17.1` shows the web UI for the Crux Console.

**Comment by refset** [comment]
I'm not sure exactly what might have changed, but since the recent fix to the config in https://github.com/juxt/crux/pull/1585 this looks resolved with the `1.18.0` image. Please let us know if you have further issues @NodeGuy and thanks for the report!
