### ISSUE TITLE
Using your own metrics registry

### ISSUE THREAD

**Issue by nivekuil** [xtdb/xtdb#1560]
Some docs feedback/signpost for future users: it took me a while to figure out how get crux-metrics to use my own prometheus registry. This is because the docs don't have `:registry` listed as a parameter in the section here https://opencrux.com/reference/monitoring.html#_metrics_module because it's under `::sys/deps` instead of `::sys/args`, while it is present in the section below ("Prometheus reporter"), implying that you should set it there. However doing so entails using the pushgateway or http exporter. It turns out to just tell Crux to write to your own registry you have to do something like `:crux.metrics/metrics     {:crux.metrics/registry #ig/ref :app.metrics/dropwizard-registry}`, which I did not find clear from the docs.

edit: actually not sure that worked. Is it possible to do this at all? Maybe `crux.metrics/->registry` should take params?

edit2: ok, I think I got it. It looks like if a key is not in `::sys/args`, passing it will throw which is good. But `:registry` is actually not even in `::sys/args` in https://github.com/juxt/crux/blob/master/crux-metrics/src/crux/metrics/prometheus.clj, contra the docs. Also `::sys/deps` does not seem to be able to be set from the config. So I ended up patching `crux-metrics` to move `:registry` from `::sys/deps` to `::sys/args`.

**Comment by deobald** [comment]
@nivekuil I realize @refset already has this in Selected, but in the interest of docs which suit the needs of the reader, I think we'd all be quite happy to take a patch if you already know precisely what you wish the docs said. Might save a cycle. Ignore me if I've missed a conversation elsewhere, though.

**Comment by nivekuil** [comment]
To summarize (as this issue was haphazardly written), 1. the code needs to be changed to match the docs by putting :registry in ::sys/args so it can actually be set as advertised and 2. it would be nice if the code and docs were changed to allow setting :registry in :crux.metrics/metrics so people can just use their own dropwizard registries and nothirg else.

**Comment by refset** [comment]
(alongside https://github.com/xtdb/xtdb/pull/1715)
