### ISSUE TITLE
Connection pool db-spec can only be a map

### ISSUE THREAD

**Issue by arichiardi** [xtdb/xtdb#1561]
Hi, there - just a quick one, the documentation seems to assert:

"The connection pool also requires a db-spec - a map containing either a full jdbcUrl or its component parts, including ..."

However the code says otherwise 

https://github.com/juxt/crux/blob/master/crux-jdbc/src/crux/jdbc.clj#L43

**Comment by jarohen** [comment]
Hey @arichiardi, thanks for flagging this. I think the docs are (strictly speaking) correct, although not particularly clear - I've added to the [examples](https://github.com/juxt/crux/blob/af97d6a1a53192e86b437a7fd2b39046aaf5dd01/docs/reference/modules/ROOT/pages/jdbc.adoc#example-configuration) - does this clarify what's required?

James

**Comment by arichiardi** [comment]
Oh ok - I guess what I tried was to actually use a `jdbc-url` there and it was never taken into consideration so I had to use a map.
I did not have time for a repro case at the time though, sorry about that, will try to create one.

**Comment by jarohen** [comment]
No worries, thanks for flagging it as unclear :pray:

**Comment by arichiardi** [comment]
I have actually just realized why it was not working. The options are `camelCase` (`:jdbcUrl`) :open_mouth:.
Thanks for adding the example @jarohen!

**Comment by jarohen** [comment]
Aha, yes - that's a `next.jdbc` thing :smile: https://cljdoc.org/d/com.github.seancorfield/next.jdbc/1.2.689/doc/getting-started#the-db-spec-hash-map
