### ISSUE TITLE
tx-log access APIs for Kafka are not thread safe

### ISSUE THREAD

**Issue by nivekuil** [xtdb/xtdb#1563]
![image](https://user-images.githubusercontent.com/4633048/124356560-7a33ef00-dbcb-11eb-9770-fdd7ac557afd.png)

Pictured is `crux-metrics` blowing up as it tries to call `latest-submitted-tx` while something else had apparently acquired the consumer. This would affect `open-tx-log` and `latest-submitted-tx`. Seems like an unnecessary constraint to have these not be thread safe given that they aren't performance critical? Maybe the tx-log protocol itself should prescribe certain semantics around this stuff too.

**Comment by jarohen** [comment]
Hey @nivekuil, cheers for raising :pray: We're currently keeping a `KafkaConsumer` in the Kafka tx-log purely for getting hold of the `latest-submitted-tx`, so that we don't have to re-create one every time it's requested, although it now seems that this is an invalid optimisation :(

James

**Comment by jarohen** [comment]
Merged, will go in with 1.18.1 - cheers for the report @nivekuil :pray:
