### ISSUE TITLE
Make crux work with constrained memory limits

### ISSUE THREAD

**Issue by megakorre** [xtdb/xtdb#157]
It currently seems like the usage of rocksdb that we do does not respect the JVM set
memory limits. (this needs to be confirmed)

We have seen out of memory errors from Kubernetes when deploying it with 2G of memory
and setting the heap size limits of the JVM to 1.5G. 

So we need to find out what the memory requirements of the rocksdb/lmdb usages are.
And if they can be constrained or made to respect the cgroup limits

**Comment by jonpither** [comment]
Hi @megakorre out of interest - what was the fix?
