### ISSUE TITLE
tx-committed? strange results

### ISSUE THREAD

**Issue by pekeler** [xtdb/xtdb#1579]
`(crux/tx-committed? crux {:what :ever})` returns true but probably shouldn't. I ran into this after copy-pasting the resulting transaction map in the REPL.

**Comment by refset** [comment]
Thanks for reporting this!

I think the issue will be resolved in #1580, but to confirm, where you wrote:
> I ran into this after copy-pasting the resulting transaction map

Did this pasted map contain the qualified `:crux.tx/tx-id` key or is possible that it was malformed (e.g. left out the `crux.tx` namespacing)? Do you have a copy of it still?

**Comment by pekeler** [comment]
@refset I left out the namespace.
