### ISSUE TITLE
invalid doc on match + tx-commited? when lucene is active

### ISSUE THREAD

**Issue by coadan** [xtdb/xtdb#1646]
Issue present in 1.19.0

Steps to reprod: 
```
(def node (xt/start-node {:xtdb.lucene/lucene-store {}}))

(->> (xt/submit-tx node [[::xt/match {:xt/id 1} nil]
                         [::xt/put {:xt/id 1}]])
        (xt/await-tx node)
        (xt/tx-committed? node))

Execution error (ExceptionInfo) at xtdb.tx.conform/check-doc (conform.clj:18).
invalid doc
```

**Comment by refset** [comment]
Hi @coadan thanks for the report and succinct repro. On first glance, I think this may be a dupe of https://github.com/xtdb/xtdb/issues/1627 which, coincidentally enough, got fixed earlier today (!)

**Comment by refset** [comment]
Apologies for the late follow-up here - I just confirmed this works as-of 1.20.0 and later (following the fix mentioned above). Thank you again!
