### ISSUE TITLE
Improve System Terminology

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#165]
(continuing the discussion...)

jdt   [3 hours ago]
How about `["embedded standalone" "remote standalone" "embedded node" "remote node"]` as the four standard types of system?

hak   [2 hours ago]
hmm, in theory there's no difference between the remote modes, like you access Crux over HTTP to a node that may or may not be part of a cluster / standalone

hak   [1 hour ago]
to go back to basics, there are 3 systems: remote API client over HTTP, and one where the transaction log is embedded (standalone) and one where it's shared (Kafka / local node) - from a query POV the latter two are identical, the index is local to them and they're both embedded in the users application as a library. To slightly confuse things the "local node" mode is also what's used when you use CaaS and talk to it over HTTP / Kafka only, except there's no user code involved.

hak   [1 hour ago]
From the users POV, the CaaS mode is the same as remote API mode.

hak   [1 hour ago]
In reality these might also be mixed, like you might have Kafka and "local nodes" embedded in your application but also allow remote API access to them.

jdt   [1 hour ago]
"From the users POV, the CaaS mode is the same as remote API mode." I agree the code perspective is important (where the user is the programmer), but what about the architect and sysadmin? I feel like "remote API client over HTTP" isn't a discrete thing, merely a way of interacting with the two actual types of systems (again, system from a sysadmin perspective, not a "Crux system")

hak   [1 hour ago]
this is totally correct - problem I guess is that all these are valid perspectives, we simply need a clear nomenclature that captures them unambiguously

hak   [1 hour ago]
Potentially we can rename ICruxSystem to ICruxAPI or similar, to break some of this confusion - like there's an internal "Clojure system" (as in Stuart Sierra, though we're not using it literally), but that's an implementation detail, to the user he's interacting with the API against a system - which as you say, might not be local.

jdt   [1 hour ago]
"in theory there's no difference between the remote modes" ...I guess that's a statement which is approximately correct today but may change. For instance the /status responses are already quite different, right?

hak   [1 hour ago]
we can also maybe rename internally maybe Standalone to EmbeddedNode?

hak   [1 hour ago]
ah, yes, there are a lot of differences on that level, but not so much from an application POV

hak   [1 hour ago]
or maybe CruxClusterNode and keep StandaloneSystem. I would prefer a naming scheme that makes sense both internally and externally, as otherwise we'll just keep getting confused.

hak [2:45 PM]
So having discussed a bit with @jdt - maybe a small step: rename `ICruxSystem`to `ICruxAPI` and `LocalNode` to `ClusterNode` and keep `StandaloneSystem` and `RemoteApiClient` as is. I'm quite keen on a naming scheme which scales from the internals to the docs and beyond as otherwise it will be confusing for no real reason.

jon [2:56 PM]
sounds good
ClusterNode is much more obvious

**Comment by hraberg** [comment]
To summarise and move out the conclusion:

> Rename `ICruxSystem` to `ICruxAPI` and `LocalNode` to `ClusterNode` and keep `StandaloneSystem` and `RemoteApiClient` as is.
