### ISSUE TITLE
Limit predicate and function usage in Queries

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#166]
We currently support open resolved predicates in the queries. This is fine when running as a library (as there's nothing the application already can't do), but a security risk when accepting queries over the HTTP API. This risk may or may not be acceptable depending on the overall system setup. We need at minimum document this so users can make an informed choice.

Solution is similar to the one for real transaction functions - some form of limited, safe subset of Clojure, see xtdb/xtdb#2019. It's slightly easier in this case as there can be no nested expressions, so a (configurable) white list could potentially do.

**Comment by hraberg** [comment]
One simple and minimal solution to this would be to add a configuration flag that disallows usage of predicates all together during queries. But that might not be useful in practice. And the step from that to have an explicit white list is quite small.

**Comment by refset** [comment]
I'm fairly sure this was meant to have been closed alongside https://github.com/xtdb/xtdb/issues/979
