### ISSUE TITLE
Limit JNI REPL Crashes

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#167]
As discussed on call. Depending on use case might hard, but we should clear out anything easily avoidable. @refset could you provide example on when and how it's caused?

I know reloading and unloading some namespaces (like `crux.kv.rocksdb.loader`) can crash the JVM, and is marked in an aim to avoid this.

**Comment by refset** [comment]
@hraberg See the latest commit message for usage & steps: https://github.com/cruxlabs/crash

**Comment by refset** [comment]
@hraberg updated with a much more minimal example https://github.com/cruxlabs/crash

Take a look at `/acme.api/repl-output.txt` and note that it gets all the way to the `db` call before crashing: https://github.com/cruxlabs/crash/blob/master/acme.api/src/acme/api/core.clj#L90

**Comment by refset** [comment]
The specific issue has not been resolved but this kind of behaviour is not unexpected when attempting to create ad-hoc life cycle management. The recommendation is to use a more resilient approach, e.g.: https://juxt.pro/edge/docs/built-in-libraries.html#crux.ig
