### ISSUE TITLE
Redo Matrix Spike in Rust and Compare

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#168]
This is an information gathering exercise. By rewriting the matrix spike as-is, we don't have to focus on both solving the problem and how to do it in Rust. We also have a direct like-for-like comparison, both in terms of code and performance characteristics.

The goal is to get the same WatDiv suite run against both, implemented using more or less the same strategy. Once that's done, one can try to tune it and change how it works.

It might be possible to split this up in smaller narrower incremental steps and compare as you go.

We could potentially use crates like these:
https://github.com/danburkert/lmdb-rs
https://github.com/saulius/croaring-rs
https://github.com/Amanieu/hashbrown
https://github.com/vbarrielle/sprs
https://github.com/utkarshkukreti/edn.rs
https://github.com/vandenoever/rome

As an extension one could try to use http://faculty.cse.tamu.edu/davis/suitesparse.html for real, but that's really another spike and could be done via JNR as well. At some point we should sanity check this and see what the gap is for our use case.There are a few hurdles, like building and maintaining the library, and mapping our data to its internal matrices in an efficient way.

**Comment by hraberg** [comment]
One could sidestep the ingestion and RDF step by simply reusing an LMDB instance prepared from Clojure. But on the other hand it might be a nice incremental way of building the spike and figuring out how to do stuff.

**Comment by hraberg** [comment]
One benefit of using real GraphBLAS is that one can then plugin back-ends using the GPU: https://github.com/gunrock/graphblast

But many questions would remain, as our usage would require a lot of chattiness and loading data over to the GPU.

**Comment by refset** [comment]
In regards competitors for bringing GraphBLAS to the masses, this looks worth keeping an eye on https://github.com/michelp/pggraphblas

**Comment by hraberg** [comment]
https://github.com/jonhoo/rust-evmap

**Comment by hraberg** [comment]
Closing this for now, we'll revisit the full future tech track, both Rust and matrix will come back in various forms. Main issue here is that the current matrix spike tree index is way to rough, and to go forward here we need something better.
