### ISSUE TITLE
IMDB example mentions `api/start-cluster-node` which is not available in `[juxt/crux "0.1.0-SNAPSHOT"]`

### ISSUE THREAD

**Issue by spacegangster** [xtdb/xtdb#170]
Tried to run IMDB example.
`:cause No such var: api/start-cluster-node`
Seems like it ain't present in the current clojars version of `juxt/crux` 
```
Retrieving juxt/crux/0.1.0-SNAPSHOT/crux-0.1.0-20190304.160429-21.jar from clojars
```

**Comment by refset** [comment]
For the benefit of others: Clojars hasn't been updated in a while so the solution here is to `lein install` crux locally. We will update Clojars with an official alpha version nearer to the launch.
