### ISSUE TITLE
New Ingest/Submit/Produce API for some operations (without full node / indexes)

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#176]
Currently operations such as `submit-tx` require a Crux System to be configured and fired up. 

You may just want a thinner API to work against an already running Crux topology, for example in the case of a data-loader, where you only want to submit transactions to Crux (currently you'd need to run a Crux System to do this).

**Comment by hraberg** [comment]
technically this is simple, at least for the case discussed, you just create a Kafka producer and use `crux.kafka` directly, so from a pragmatic POV one end of the spectrum is to document this, the other end is to clean it up better and hide it behind `crux.api`, potentially splitting out smaller capability Java interfaces out of the existing ones.

I mean, we can (and maybe should) start by writing the snippet in the docs that show how to do this, as knowing that will also guide how to to wrap it if one decides to move on with that step
the component you want to create is `crux.kafka.KafkaTxLog` which only depends on Kafka config and a producer, which can be created via `crux.kafka/create-producer`

**Comment by hraberg** [comment]
Ultimately the write operations in the API are the following, and they could all be broken out to their own interface and protocol, wrapping a `TxLog` instance:

`submitTx`, `newTxLogContext` and `txLog`. The latter do allow for pulling out documents though via a flag, which won't be possible (or at least not cheap) on a remote ingest-only instance, so potentially `submitTx` is the main one. Or one could have an extra overload not supporting `with-documents?` for the version wrapping `TxLog`.

**Comment by hraberg** [comment]
With the module system this would potentially be a new slimmer kind of ingest node.

**Comment by hraberg** [comment]
This is part of a more general drive to split the main `ICruxAPI` facade into a set of small capability based interfaces.
