### ISSUE TITLE
Ensure Eviction Updates Tx Index Properly

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#180]
As reported by @spacegangster, the entity API returns evicted entities, while queries doesn't (as expected), my comments from then:

> if you look at `crux.tx/put-delete-kvs` you'll see that it puts in several deletion messages, eviction probably needs to do the same / similar
> that is, for `crux.tx/tx-command-evict` you can try create the `:kvs` the same way `crxu.tx/tx-command-delete` does it, and then assoc in the `:post-commit-fn` on top and see if that still passes all the tests, and changes the behaviour of your REPL test above.

Still needs more testing and verification what's actually wrong, the above is my theory.

Ivan on 23-04-19:
for convenience – a reproduction gist:
```
(ns crux.scratch
  (:require [crux.api :as crux]))

(def system
  (crux/start-standalone-system
    {:kv-backend "crux.kv.memdb.MemKv"
     :db-dir "data/db-dir-1"})

(crux/submit-tx
  system
  [[:crux.tx/put :ids.artefacts/laptop
    {:crux.db/id :ids.artefacts/laptop
     :artefact/title "A Tell DPS Laptop (what?)"}
    #inst "2016-05-18"]])

(crux/entity (crux/db system #inst "2016-05-18") :ids.artefacts/laptop)

(crux/submit-tx
  system
  [[:crux.tx/evict :ids.artefacts/laptop]])

(crux/entity (crux/db system #inst "2017-05-18") :ids.artefacts/laptop)

; yields
{:crux.db/id :ids.artefacts/laptop, :artefact/title "A Tell DPS Laptop (what?)"}
```

**Comment by hraberg** [comment]
My impression from the report is that documents are deleted properly, but this also needs to be verified.

**Comment by spacegangster** [comment]
@hraberg  for now reproduces only for `crux.kv.memdb.MemKv`. RocksDB looks sound without any restarts.

**Comment by hraberg** [comment]
We have two options - either we create all necessary deletions, or we create no deletions at all. The current behaviour will break under some circumstances. It also doesn't respect the `keep-latest?` and `keep-earliest?` flags, so can currently accidentally mark these versions as deleted, breaking the compaction use-case.

Easiest fix would be to generate no transactions for the eviction and rely on the document index being cleared out. Might require some reflection though.

Would also be good to understand why it's not working in MemKv, like is it cache related potentially?

**Comment by hraberg** [comment]
Is this the same issue as #189 ?

**Comment by hraberg** [comment]
Or I guess, we have a cache issue, now #189, while this current issue refers to the fact I mention above - eviction needs to leave the tx index in a consistent state. So both seems valid.
