### ISSUE TITLE
Eviction Will Cause Kafka Replay to Block

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#184]
The indexer will pause consumption of transactions while waiting for all their documents to appear. When evicting documents they will have been compacted in Kafka, so replay will just block with the current behaviour.

See this line to start exploring the issue:
https://github.com/juxt/crux/blob/master/src/crux/kafka.clj#L220

A potential solution is to not actually delete the documents when receiving a `nil` (deleted) document from Kafka, and potentially even remove `ObjectStore/delete-objects` and put in a tombstone `nil` instead into the object store. 

`docs-exists?`, apart from then being misnamed, also won't work, as it delegates to `get-objects` which checks if the document is `nil`. This will need to be fixed for all `ObjectStore` implementations, and potentially add a new check instead, something like `known-keys?`.

Note that the blocking happens on `crux.tx/put` or `crux.tx/cas`, as these are the ones which depend on documents, not during the processing of the `crux.tx/evict` message itself, which will be later in the log. Also, while this proposed fix should (hopefully) solve the issue, it will hold up replay, as any message will have to wait for its evicted documents to be replayed to be indexed.

Fixing this would also be a good time to add more tests around eviction. Related to xtdb/xtdb#180.

**Comment by hraberg** [comment]
This check if the document has actually arrived during the pre-conditions, like here in `crux.tx/cas` also needs to just check the key is known (but might been evicted), not the document itself:
https://github.com/juxt/crux/blob/master/src/crux/tx.clj#L109

This fix is needed in `crux.tx/put` as well. I think this extra check is just a sanity check, as there's already the part in the indexer which waits for all documents in a transaction before indexing it, that is, the same blocking part this issue is about. One option might be to remove this check - but the main CAS failure check is still needed of course!

**Comment by hraberg** [comment]
Probably easiest to fix xtdb/xtdb#180 first and get familiar with the area, adding some new tests, before tackling this slightly more involved one.

**Comment by hraberg** [comment]
Related to xtdb/xtdb#2015.

**Comment by megakorre** [comment]
I think there is a problem if we need to use `nil` as a tombstone for documents. 
The way compaction works messages with null as the value will eventually get cleared out of the https://kafka.apache.org/documentation/#compaction (a minimum of 24 hours after writing it by default).

So on replay a consumer might not see any entry for the document at all.

If we need to find a tombstone for a document for this then we could write a explicit sentinel value.

(I guess there also could be a problem if with eviction if a node is blocked or unavailable for 24 hours and then restarts consuming. It then might miss the eviction message if we use null as the value).

**Comment by hraberg** [comment]
I did consider writing a `{:crux.db/id :crux.db/evicted}` placeholder tombstone document (under the original hash of course), and if the `nil` message will get cleared out, something like that might be the way to go?

**Comment by megakorre** [comment]
yea I think that would work fine
