### ISSUE TITLE
Default make target raises asciidoctor error about missing index.adoc

### ISSUE THREAD

**Issue by piotr-yuxuan** [xtdb/xtdb#191]
On commit 40f021fd4d298d6c5f633c9bb08d3778a5e026ee with a clean git state

``` sh
$ make
asciidoctor -d book -a "webfonts!" -a stylesdir=styles -a stylesheet=juxt.css index.adoc
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Users/$USER/Library in PATH, mode 040777
asciidoctor: FAILED: input file index.adoc is missing
make: *** [index.html] Error 1
```

Indeed `index.adoc` is missing.

Apart from that minor, technical detail, thanks so much guys for this amazing project!!

**Comment by jonpither** [comment]
Hi @piotr-yuxuan Thanks for this. The current asciidoc docs are consumed by the JUXT website, and aren't currently supporting a PDF/HTML build via `make`. The old `make` target is legacy and should either  be removed, or we make it work and commit to maintaining a HTML/PDF build of the docs. 

Will have a think - thanks again for reporting.
