### ISSUE TITLE
Kafka Deployment

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#1965]
There should be a way to deploy a Crux cluster into the cloud.

This might involve several layers, from Docker Compose to full AWS one click deployment or Kubernetes pods.

For this to be simple to use, we're likely to need a remote REST API, see xtdb/xtdb#8. Depends on xtdb/xtdb#5.

For the MVP we assume that a Crux cluster also includes Kafka and Zookeeper, these components might later be possible to swap out.

**Comment by jonpither** [comment]
To invesigation:

- Generation CloudFormation stacks
- AWS marketplace

Do we provide CloudFormation templates, or does the user need a script to generate them? Analysis needed.

Presumably we can't rebuild our marketplace offering from every CircleCI build, and even if we couild, it might not be desirable. Analysis needed.

**Comment by jonpither** [comment]
For now, all we need is a way to easily provision a Kafka cluster - that we can use for developing and testing Crux. Crux nodes after all, are an embedded library.

**Comment by jonpither** [comment]
We don't need to build a REST API into Crux yet, if we have a standalone console: https://github.com/juxt/crux/issues/28

**Comment by Roxolan0** [comment]
We don't want to have to maintain our own Zookeeper & Kafka CloudFormation template. Will look into using existing ones from the AWS marketplace.

(We currently have a single-machine ZK/Kafka launch template.)
