### ISSUE TITLE
Branch Snapshotting

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#1966]
The idea of branching off a time dimension. This is with a specific use case in mind: banks wanting to snapshot their data at business time T, but then to make corrections against this newly formed timeline.

It would be good to have a story around this in the docs - the need for, and the way Crux solves this problem (even if it doesn't directly solves it, but offers a helpful path).

Currently, not MVP.

**Comment by hraberg** [comment]
This card is for analysis, we currently don't know how to do this, like we can tag, via bitemp, but not branch and evolve this tag, there's only one main timeline.

**Comment by hraberg** [comment]
Some techniques discussed here might be of interest:
https://www.arangodb.com/2018/07/time-traveling-with-graph-databases/

Currently, we don't have any cross-entity concept of history.

**Comment by hraberg** [comment]
A less elegant way of doing this would be at the entire Crux db level, you can copy the tx topic to a branched topic up until the point you want to branch, and start a new crux instance from there. Currently this would require re-indexing, but in theory one could reuse the doc part of the indexes (which are likely costlier to build), as they don't concern themselves with time.

Similarly, one could imagine having several tx indexes in the same store, each being a branch, potentially sharing a past.

**Comment by megakorre** [comment]
not currently planned for phase2

**Comment by Tails** [comment]
Original Comment
----

I was looking for this as an alternative to Irmin. Does this feature now exist?


Response from @refset 
----

Not at this time, but we won't rule it out (2020-11-03)
