### ISSUE TITLE
Micro-optimisation: use types for seek k/vs

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#1970]
As part of `seek-and-iterate`, we generate small vector tuples. Rudimentary REPL testing shows a slight perf gain if we use defrecords. 

Note, the perf downside of small vectors could also be due to the way we are consuming them - more investigation needed.

Note (2), profiling shows it could be that multiple calls to `(.key i`) on the Rocks iterator has a hit. Refactoring to a micro-type should also these tackle redundant calls.

**Comment by hraberg** [comment]
One approach is to use actual map entries, that is, using for example `clojure.lang.MapEntry/create`.
