### ISSUE TITLE
Crux Query Node Deployment

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#1972]
We want a way to deploy the Crux query nodes next to our Kafka cluster, see xtdb/xtdb#1965.

**Comment by Roxolan0** [comment]
Using some kind of nested CloudFormation, so that launching the Crux CF will trigger the Zookeeper/Kafka CF (or connect to an existing one).

**Comment by Roxolan0** [comment]
We'll want an internal load balancer and a bastion.
