### ISSUE TITLE
Add history and doc to REST API

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#1977]
It would be nice to be able to get the full history of an entity id, and the actual document for a specific content hash. These features, like most in the current REST API aren't necessarily something that will survive further down the line, but enables users to access this data for now.

These calls would delegate to `crux.doc/entity-history` and `crux.db/get-objects` on the object store.

This could be further extended to add date ranges to the history and the option to add the documents directly in the same response, but the above are the primitives.

**Comment by Roxolan0** [comment]
Currently functional, but not very smart in how it reads UUIDs from GET requests. Will improve.
