### ISSUE TITLE
Create a sample app with Crux

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#1979]
@malcolmsparks asked if we could do this. It would be good as it's a somewhat simple use-case but will iron out things as someone tries to use Crux. We can potentially use this to drive docs as well. Running Crux on a single node without Kafka is possible, some tests do this, but requires manual wiring.

I'm adding this as part of the MVP milestone, but we will need to plan accordingly.

**Comment by jonpither** [comment]
I can see two pieces of work here.

1) use Crux in embedded mode
2) use Crux in AWS, using @Roxolan0 work

I would ideally like to see both. I imagine some export code will need to be written to migrate from the existing data store into Crux, and for 2), Crux -> Crux.

**Comment by hraberg** [comment]
Various ongoing work in this area related to deployment (like xtdb/xtdb#31), and the client work. Closing this card.
