### ISSUE TITLE
Implement checkpoint and restore

### ISSUE THREAD

**Issue by megakorre** [xtdb/xtdb#1983]
# Motivation

Currently a fresh started instance of Crux needs to index all of history from kafka
in order that have the latest queryable view available. This could potentially b e to slow
for bringing up new instances in case of instance failure or for horizontal scaling of query capabilities.

A way to potentially speed it up is to backup the underlying index at some interval to some shared storage.
Something like S3 or some mounted network storage.
And new instances can at startup download these snapshot and supplement the remaining data from kafka.

How much speedup you can expect between restoring it all from kafka vs downloading a checkpoint is something that needs to be tested

# Tasks
- [ ] implement configurable backup mechanism. Initial support for just s3
- [ ] implement restore from checkpoint on startup.

**Comment by jonpither** [comment]
Related: https://github.com/juxt/crux/issues/6
