### ISSUE TITLE
Cloud Setup and Templates

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#1992]
This might be a mix of scripts, AWS market place, cloud formation, Docker Compose or simply documentation. It needs someone to drive and look into. It also depends a bit on what level of release we're aiming for if this is necessary for Phase 2.

**Comment by hraberg** [comment]
Builds on @Roxolan0's work. Related to xtdb/xtdb#31.

**Comment by megakorre** [comment]
completing this. I have committed some templates and code to the repository. There's more stuff to be done. But that will be done in the other operations issues that exists
