### ISSUE TITLE
Result of a `:full-results? true` query contains `crux.query.BoundResult`-tag

### ISSUE THREAD

**Issue by christoph-frick** [xtdb/xtdb#201]
This makes it way harder to have a API client, as the client now needs to know about this type as well.

```clojure
http://localhost:8081 => (-> (GET "/") :body :crux.version/version) ; server version
"19.04-1.0.3-alpha-SNAPSHOT"
http://localhost:8081 => (-> (POST "/query" (edn '{:query {:find [e] :where [[e :name "Test"]] :full-results? true}})) :body) ; show body contains tag
"#{[#crux.query.BoundResult{:var e, :value :test, :doc {:crux.db/id :test, :name \"Test\"}}]}"
http://localhost:8081 => (config! :as :auto) ; enable EDN decoding in clj-http
{ ;...
 :request {:as :auto, :coerce :always, :debug false, :throw-exceptions false}}
http://localhost:8081 => (-> (POST "/query" (edn '{:query {:find [e] :where [[e :name "Test"]] :full-results? true}})) :body) ; call fails now
Execution error (ExceptionInfo) at clojure.tools.reader.reader-types/reader-error (reader_types.clj:391).
No reader function for tag crux.query.BoundResult
```

**Comment by refset** [comment]
Thanks for reporting. You may have noticed that we've been changing the way `:full-results?` works very recently and it looks like we didn't account for this. I hope it doesn't impact your experimentation too heavily -- we should be able to resolve it very soon!

Edit: Actually I just realised we _have_ accounted for this, but the changes are still being finalised, see https://github.com/juxt/crux/pull/197

**Comment by christoph-frick** [comment]
Yeah also https://github.com/juxt/crux/issues/173#issuecomment-486616860 methions this. I applied the mentioned PR on a local checkout and tag-problem is gone.  Thanks for looking into it.

**Comment by jonpither** [comment]
Thanks @christoph-frick for reporting :+1: . I'm closing as #173 addresses this, and the PR is going to be merged soon that fixes this.
