### ISSUE TITLE
Architectural Diagram of Crux

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#2010]
Assigning to @refset. Suggest @hraberg does a sketch that @refset can work into a doc.

**Comment by jonpither** [comment]
Relates to xtdb/xtdb#2006

**Comment by refset** [comment]
For feedback & initial discussion:

![image](https://user-images.githubusercontent.com/456658/50530785-f5972000-0af8-11e9-9c48-8f2c4a79fa70.png)

**Comment by hraberg** [comment]
Nice one @refset. I started an effort using https://www.draw.io/ a while back, but yours is clearer.

[Crux.pdf](https://github.com/juxt/crux/files/2716229/Crux.pdf)
[Crux.xml.gz](https://github.com/juxt/crux/files/2716232/Crux.xml.gz)

The second XML file can be unpacked and loaded into the tool. What tool did you use here?

I like your approach to splitting it up and focus on the essentials, need to reflect a bit on it, like the difference between persistence and update etc. and if this is the right way to describe it. But it's great to see someone else aim to explain how it all works. Might be useful to clarify the arrows, which are hashes (so eviction doesn't keep readable ids in the tx topic), between the topics, maybe in the text.

Would also be worth to highlight the library vs. HTTP API difference of accessing Crux.

We can keep discussing here, but also have a call next week sometime about this. I mentioned to @jonpither that if we get this slide right, it can drive a lot of the other messaging and explanations about Crux and keep referring back to it.

One thing that your overview quickly made me realise is that we don't have an ingest-only system exposed via the Java API, which writes to Kafka but doesn't actually read from it. I expect this scenario to be quite common. It's trivial to expose, potentially by splitting the main `ICruxSystem` interface into several smaller one defining different capabilities. At the same time it risks complicate things if we add permutations that no-one uses.

BTW, LMDB also has a logo, it can be seen in various slide decks, or more clearly, here:
https://dbdb.io/db/lmdb

**Comment by refset** [comment]
See: https://github.com/juxt/crux/blob/master/docs/img/crux-system-1.svg
