### ISSUE TITLE
Finalise Crux Logo

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#2012]
Related to xtdb/xtdb#113

**Comment by refset** [comment]
Just some ideas...

![crux-logo](https://user-images.githubusercontent.com/456658/51060013-0316d480-15e6-11e9-9337-5cd2316aede1.png)

My intention with these was to communicate bitemporality (hence the two arrows of time) and maximise legibility.

**Comment by danielcompton** [comment]
I like 2 and 5. 10/11 are also pretty good though, and maybe more legible at small sizes?

**Comment by mpenet** [comment]
+1 for 11 and 5 as well. I would exclude the redis like "database" symbol.
