### ISSUE TITLE
Transaction Functions

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#2019]
As mentioned in xtdb/xtdb#2018, we already know that we probably want to add transaction functions to Crux.

Crux's transaction commands are implemented via a multi method, so that's one way to do this already, but it's not easy to extend, as one also need to extend and update the relevant spec. It's also arguably not the right way to do this (though as Crux is open source, one can choose to do it this way).

Adding `:crux.tx/fn` is another (and the most obvious) option. This function would be given access to the current db, so it can issue arbitrary queries and validate constraints etc. But this requires running potentially untrusted code on the nodes, and it also requires that all nodes are in sync version-wise with the relevant code.

Because of this, one approach is that the transaction command is given the function verbatim, and that this function is "simple". The function would be evaluated in its own restricted namespace with a white list of functions and Java inter-op would be prohibited. There is an old library, https://github.com/Raynes/clojail that might help with things like this, but doesn't seem to be actively maintained.

One alternative is to write some form of interpreter and maybe not even assume that the  function is written in Clojure at all, Javascript probably being the natural alternative. One can also potentially use the Java Security Manager for this, but thinks it works the other way around, that is, it can give privileged access but not limit it.

**Comment by hraberg** [comment]
In some cases and deployments, simply allowing the function to be evaled without any restriction is the easiest way to get the functionality of this card working. Most analysis and harder work for this card comes from controlling what is executed.

**Comment by hraberg** [comment]
Like in Datomic, the function would likely return the new, modified, transaction commands.

**Comment by hraberg** [comment]
Note that it's possible that the commands returned by the transactor function contains further transactor functions, so it needs to keep iterate on the return value, potentially adding more data to the write set. Exactly how this will work requires some analysis. One alternative is to not support transaction functions returning other functions.

**Comment by hraberg** [comment]
We could potentially treat the functions as documents, so they're stored in the document store and their contents are hashed in the transaction log. This way the functions can be evicted. Potentially we want to store the arguments as a separate document, also hashed in the transaction log.

**Comment by malcolmsparks** [comment]
That's a very interesting idea. If functions are easy to handle and manage, it might open the door for some remote callable 'lambda' capability.

**Comment by mpenet** [comment]
You could have both unrestricted clojure functions with all dangers, freedom and power it allows and use something like luaj as another "safe" alternative that is ok to expose to users at another level. luaj in my experience is quite fast, easy to embed and restrict (in both what it has access to and for instance cycles it can use per call). It's also less scary to "biz" users and extendable quite easily too.

**Comment by hraberg** [comment]
We'll revisit this, similar to other post release cards we need to think this over properly. This card could be a placeholder to just implement to most naive version of transaction functions, but that's not necessarily the plan.

**Comment by refset** [comment]
Reopening this issue for further analysis.

**Comment by refset** [comment]
This may affect our efforts for Graal support (e.g. if dynamic class loading is required for these transaction functions).

History considerations:

1. Should transaction functions be able to access arbitrary entity and/or db histories, i.e. be passed the entire system for unconstrained access?
2. Or (somehow) passed the db constrained by `tx-time` set to "now" but still giving a full view of valid time? This could optionally include entity-level `history-ascending` & `history-descending`
3. Or should they simply be passed the db `valid-time` and `tx-time` set to "now"?

Additionally, our transaction functions definitely need to support use-cases like `inc-k` and the current limitation that "CAS can't assert absence of an entity with an attribute" (from Leon Grapenthin via Zulip). Also: `assoc`, `assoc-in`, `dissoc`, `merge`, `update` etc.

**Comment by hraberg** [comment]
Late comment to the above, CAS can assert absence of an entity, but not sure if that's what's meant above? In some cases you can have several entities smaller in a graph to get finer grained control.

**Comment by hraberg** [comment]
Added a spike to hak/tx-fns branch. Several issues directly surfaced, and some reflections:

1. Transaction functions can create new txs, which means they can create new documents, which have to be directly indexed, at least if they are supposed to be synchronous.
2. Somewhat messy dependency on `crux.query` instead of the API to create the current database snapshot. No support for full API or history right now.
3. Function is just a form which gets evaluated, first argument is the current db, rest of arguments are also evaluated before application.
4. Function returns transaction data in the format the ingest expects, but this happens post-ingest during transaction handling, which is a bit confusing.
5. Exceptions fails pre-commit.

Overall seems to work for the simple case though. Lots of reflection and work needed to make it real.

**Comment by hraberg** [comment]
The current implementation uses eval heavily, and there's no attempt of limiting what the transaction function can do. For the same reason, there's no guarantee that the functions are side effect free.

**Comment by hraberg** [comment]
Also, the functions and their arguments are stored in plain edn on the tx topic, with no ability to evict or get rid of this data once it has been published. As mentioned above much earlier, on potential option is to turn this into documents so they could in theory be evicted.

In the simplest case this document could be a normal Crux doc but with a few more required fields, `:crux.db/fn` and `:crux.db/args`. Alternatively, these could two separate documents, so the functions are reused. Something like this:
```
'[[:crux.tx/fn
   {:crux.db/id :inc-attr-fn
    :crux.db/fn (fn [db eid k f]
                        [[:crux.tx/put (update (crux.api/entity db eid) k f)]])}
   {:crux.db/id :inc-ivans-age-args
    :crux.db/args [:ivan :age inc]]}]]
```
Or with both attributes in a single document, as first mentioned.

**Comment by hraberg** [comment]
One could of course also separate out the fn as its own document, and then have the invocation depend on this document existing:
```
'[[:crux.tx/put
   {:crux.db/id :inc-attr-fn
    :crux.db/fn (fn [db eid k f]
                        [[:crux.tx/put (update (crux.api/entity db eid) k f)]])}]
  [:crux.tx/fn
   {:crux.db/id :inc-ivans-age-args
    :crux.db/fn :inc-attr-fn
    :crux.db/args [:ivan :age inc]]}]]
```

**Comment by hraberg** [comment]
The current format now looks like this, transaction function must already exists as a document before being invoked:

```
[[:crux.tx/put
  {:crux.db/id :update-attribute-fn
   :crux.db.fn/body
   '(fn [db eid k f]
      [[:crux.tx/put (update (crux.api/entity db eid) k f)]])}]]
```

Invocation, arguments are dealt with as another document:
```
[[:crux.tx/fn :update-attribute-fn
  {:crux.db/id :inc-ivans-age
   :crux.db.fn/args [:ivan
                     :age
                     inc]}]]

```

**Comment by hraberg** [comment]
The way the resulting docs gets submitted isn't really great. I can imagine getting orphaned docs which cannot be evicted for example. Would need some further thought, this entire part has just been retrofitted to work for the basic case.

**Comment by hraberg** [comment]
This might be a problem in general, that if docs are getting submitted but for some reason their transactions fail, they won't have transaction entries written, meaning eviction cannot find them when it deletes the entity.

**Comment by hraberg** [comment]
A workaround is that one could manually submit tombstones to the doc topic for specific content hash if one needs to get rid of orphaned documents. This obviously assumes the hash can be retrieved or calculated somehow.

**Comment by hraberg** [comment]
Maybe something like this could be of interest to limit what the functions can do?
https://github.com/borkdude/sci

Similar issue is discussed on xtdb/xtdb#166, this could be applicable there to.
Potentially one could have a different modes, from no functions, interpreted or full Clojure.

**Comment by hraberg** [comment]
Though for queries and xtdb/xtdb#166 this isn't as needed, as a white list (which sci provides) could be enough.

**Comment by hraberg** [comment]
Unrelated, might be worth noting that I removed all resubmitting of stuff to the log from transaction functions, and index the results and store documents directly on the node as they are executed. This is at least consistent with the local index being a function of the log. There are some drawbacks that one cannot easily see the consequences of the tx fns in the main log, but that's hard to fix without a centralised executor of the functions which can block and resubmit in a lock.

That is, the current implementation is optimistic and the nodes are still independent.

**Comment by hraberg** [comment]
Would we go down the path of adding transactions to the KV store, some things regarding this could be simplified, and it would be less of a risk of orphaning stuff. One complication is that even though they are usually backed by the same physical KV store, the object store and the index are treated as two different things, so it might not be as useful as it first seems to support full rollback.

Transactions in LMDB are already used as they are the same things as snapshots there, in RocksDB we would have to explore their API, most likely using the optimistic transactions from below:
https://github.com/facebook/rocksdb/wiki/Transactions

**Comment by hraberg** [comment]
Added a feature flag environment var, `CRUX_ENABLE_TX_FNS` which defaults to `false`.

**Comment by hraberg** [comment]
As discussed on call, an alternative would be to not have full transaction functions, but some form of declarative way to specify a query and assertions on the result which can check for consistency without being Turing complete and all the issues the comes with that. These would only be able to fail the transaction, basically acting as pre conditions, they would not be able to generate further transaction operations etc.

**Comment by hraberg** [comment]
We also discussed capturing more actual use-cases, and see what can and can't be done with CAS, and if, as per comment above, there's something else we can do here.

**Comment by refset** [comment]
Eviction of any document that might impact a query within a transaction function is my biggest concern as this has high potential to break the fundamental replayability properties. I can't think of any generic way to predict or detect when such a thing might happen.

It might be the case that all we can do is offer guidance such as:
1. Don't use eviction with transaction functions that run queries unless you are somehow 100% confident that the documents you are evicting will never impact the results of your queries. You could wrap evict with its own transaction function that helps to guard against eviction of special non-eviction-friendly documents such as for documents that are used as counters
2. Use of eviction with transaction functions that only operate with `content-hash` hashes are safe (via `history-ascending`/`history-descending`)
3. Evicting transaction functions or their invocations (argument documents) is almost certainly problematic

Additional reasons why transaction functions are desirable:
1. CAS only works with valid-time whereas transaction functions could allow various possible CAS-like operations to have awareness of tx-time (I know the current implementation is more restrictive). For instance, this may be useful for resolving causality in a situation where several interrelated CAS-like operations occur across multiple transactions. Admittedly I would need to think about it more before I can come up with a concrete use-case
2. Solving [ABA problems](https://en.wikipedia.org/wiki/ABA_problem) that CAS by itself can't address, i.e. CAS only replaces a single version at a single point in time but it could be useful to have a CAS variation that only does `put` (with start-valid-time and end-valid-time) if the old version is contiguous for the same period
3. Nested `and`/`or` CAS logic

Perhaps we ultimately need to think about these different transaction function use-cases more discretely, with different names reflecting the different levels of restriction. The current implementation which restricts access to transaction time may well be the most useful -- it may even make sense to restrict it further by limiting put/delete/CAS to the current valid time.

Counters seem to be a very common requirement which are currently quite clunky to implement using `CAS`, but maybe we can build something entirely outside of the core to make this easier now that tx-log tracks failed transactions (since https://github.com/juxt/crux/commit/82d6fd91d35db2822f4622360cbdd0607c89c083). Then we would have one less use-case driving users towards transaction functions.

Side note: sometimes you may only want to use CAS to assert some document version before adding some new documents, and you don't want to actually change the document version, however I think that currently [`tx-command-cas`](https://github.com/juxt/crux/blob/cba26fcfd54be4468e8e075057d214394c2be438/crux-core/src/crux/tx.clj#L71) will attempt to re-index `new-v` even if it's the same as `old-v` (so unless I'm mistaken, we may want to avoid that overhead when `(= new-v old-v)`)

**Comment by hraberg** [comment]
Just re-adding, as that mentioned earlier, I would be interested in a restricted version of this, potentially called something else, that is just able to check consistency but not add its own operations, I think that would simplify things a lot. One could then somehow track the pass/fail of this, similar to how we currently do in the index, and not rerun them if this flag exists, so eviction wouldn't affect them (as much). A consistency check that has been evicted itself would simply return the flag.

**Comment by hraberg** [comment]
"Somehow track" above most likely means a new topic where failed transaction ids are stored, potentially with some useful information, but not too useful, as in that case these would need to be evicted as well, etc.

**Comment by hraberg** [comment]
This failure topic could be compacted and keyed by the offset of the transaction topic itself, so it can handle many duplicated messages from the nodes.

**Comment by hraberg** [comment]
While an initial version of this was merged via xtdb/xtdb#320, the card itself isn't really done. My preference would be to keep this open but close it once we have more concrete cards to move on to.

**Comment by hraberg** [comment]
On the subject of counters, this is kind of a limited case of a CRDT, so we could consider having some form of support to merge docs. Riak has this, example of counters:
https://docs.riak.com/riak/kv/2.2.3/developing/data-types/counters/index.html

**Comment by hraberg** [comment]
Something like this: https://github.com/automerge/automerge

**Comment by refset** [comment]
Not _strictly_ related, also, but there's an idea for writing CRDTs as Datalog queries: https://martin.kleppmann.com/2018/02/26/dagstuhl-data-consistency.html (another Kleppmann reference!)
