### ISSUE TITLE
Review Data Access Patterns

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#2022]
For performance reasons we should review our data access patterns at the lower K/V level.

One example: We know that `seek` is more expensive than calling `next` on an iterator in Rocks (and presumably other stores). As @hraberg commented on Slack: "seeks are costly for (at least) two reasons, 1. the KV store obviously has to do more work 2. we have to allocate and build the seek key". 

There are a couple of ways to think about improving on this. Tactically, we could experiment with calling `next` after each seek and grab the data, so that consequent `seeks` could be avoided if we've got suitable data at hand (which could be the case with our tree-join approach, where multiple iterators are advancing across indices in tandem). Thinking further, you could imagine using statistics based on index paths as to whether to try and leverage this kind of peek-ahead `next`.

Strategically though, it's worth taking a step back and reviewing our data access patterns as a whole. I.e. are there other ways we can avoid unnecessary seeks, and therefore doing less of them. This may involve radically changing the indexing strategy, or not, by implementing some targeted improvements on what's already there.

**Comment by jonpither** [comment]
Some more analysis:

The original idea of using `next` in the opening description of this issue, suffers from the fact that making the data available at hand, means pulling back the K/V pair for the 'nearby' data. Pulling back values incurs a significant cost, that would likely outweigh the benefits (this could be measured in the micro-benches).

Also, with this approach, we are performance tuning above Rocks/LMDB, whereby you might expect this kind of tuning to be done directly inside the stores - so the anticipated benefits of doing it ourselves might not arise.

Lastly WRT `next`, there could be a gain in a different way - i.e. instead of calling `seek`, we try `next` a few times and throw away the returned keys until we hit what we're looking for. Before trying this, one really needs to measure `next` vs `seek` in a micro-benchmark. `next` would need to be substantially faster (by multitudes) to make this optimisation worthwhile.  

Some other areas of analysis:

**Prefix Iterator**  - Using a Prefix Iterator that is supported Rocks functionality, may-well give some speed ups when using Rocks. The main downside is that this functionality isn't supported by LMDB, and so is a jagged edge against our 'unbundled' approach, where we are seeking clean abstractions.

Nevertheless, this could be pursued. It's a bit invasive, and LMDB would be supporting the current way of iterators are working within a prefix, by using simple byte comparisons (grep about the code-base, and you can see the notion of prefix iterators are alive and well). The idea for the optimisation is essentially to push what we're doing already, into the KV store  

**ColumnFamily** Rocks has the notion of [column families](https://github.com/facebook/rocksdb/wiki/Column-Families). For example, at the most broad level, the individual indices we assemble could be put into their own column families. Again, similar to the prefix iterator issue, this isn't supported behavour for LMDB, so it would be a fairly invasive change to make. Up front metrics are needed to give us more analysis of the benefits.

**get vs seek** There are currently places where we do a `seek`, whereas `get` would suffice if it were exposed by the `KvStore` protocol. This ought to be a relatively straightforward change - but metrics should be sought ahead of time, in a micro-benchmark comparing the two access methods.

**Wider analysis** We should also look into all the various Rocks tuning options available - do a full and proper analysis here. We should also take a step back - is now the time the double down on LMDB and deprecate Rocks if we can't make it fast enough, without major investment? 

Lastly, could the development capacity be more wisely used on reworking the indexing approach such as in xtdb/xtdb#2023, rather than trying to squeeze every iota out of the current approach. See work done this far in xtdb/xtdb#97 and xtdb/xtdb#2009.

This issue should remain open until the issues raised are reflected on in a steering group. It's also advised that "get vs seek" should be tackled as it's low hanging fruit. It's also cheap enough to get stats on column families via the micro benches.

**Comment by hraberg** [comment]
Realised there's an alternative to column families in LMDB, you can have more than one named database inside the same file:
https://javadoc.lwjgl.org/org/lwjgl/util/lmdb/LMDB.html#mdb_dbi_open(long,java.nio.ByteBuffer,int,java.nio.IntBuffer)

**Comment by hraberg** [comment]
Would be good to get some timings and playing with the various options here:
https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes

I think what we want is related to this:
https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/Options.java#L1134
https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/ReadOptions.java#L253

For reference:
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/rocksdb.go
https://www.cockroachlabs.com/blog/cockroachdb-on-rocksd/

**Comment by jonpither** [comment]
Think we've reviewed the salient points, closing for now.
