### ISSUE TITLE
Consider Renaming Business Time to Valid Time

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#2025]
As per this paper, valid time is the preferred naming of this timeline. That said, a case can be made for business time, so this issue should not be seen as having decided to actually do this rename:

http://people.cs.aau.dk/~csj/Papers/Files/1993_jensenCGTDC-TR93-2035.pdf

**Comment by malcolmsparks** [comment]
I think 'valid time' is better terminology, so gets my vote. I've always wondered what the rationale for calling it 'business time' when the concept isn't necessarily just a 'business' thing.

**Comment by danielcompton** [comment]
I liked thee symmetry between business logic and business time. But after reading the linked paper, I can see that valid time is also good and probably preferable.

In the docs somewhere it might be good to excerpt the bits of the glossary you’ve used so people can understand more?

**Comment by hraberg** [comment]
Updated version of this glossary from 1998:
http://people.cs.aau.dk/~csj/Papers/Files/1998_jensenCGTDC.pdf

**Comment by hraberg** [comment]
And the site for the glossary:
http://people.cs.aau.dk/~csj/Glossary/

**Comment by hraberg** [comment]
This is a full encyclopedia of temporal concepts, from 2008 and slightly different from the glossary above, 345 pages:
http://timecenter.cs.aau.dk/TimeCenterPublications/TR-90.pdf
