### ISSUE TITLE
ZooKeeper NodeExistsException

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#2029]
I've encountered this a couple of times whilst playing with Crux, on the JUXT website and also locally. 

```
09:39:56.528 [nREPL-worker-0] ERROR kafka.server.KafkaServer - [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:122)
	at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1631)
	at kafka.zk.KafkaZkClient.registerBroker(KafkaZkClient.scala:87)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:257)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at crux.kafka.embedded$start_kafka_broker.invokeStatic(embedded.clj:36)
	at crux.kafka.embedded$start_kafka_broker.invoke(embedded.clj:34)
	at crux.kafka.embedded$start_embedded_kafka$fn__74900.invoke(embedded.clj:92)
	at crux.kafka.embedded$start_embedded_kafka.invokeStatic(embedded.clj:91)
	at crux.kafka.embedded$start_embedded_kafka.invoke(embedded.clj:73)
	at juxt.crux$eval74915$fn__74916.invoke(crux.clj:18)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
```

We need to understand what's going on to help others who might stumble into this - is it the way we're using/configuring Crux when playing with it in standalone mode? Caused by frequent restarts?

**Comment by jonpither** [comment]
Thoughts here - could be we're not shutting ZK down cleanly. Possible these errors aren't as fatal as they initially suggest, from a quick google.

**Comment by jonpither** [comment]
You can reproduce this by firing up an embedded Kakfa node, and then simply killing the Java process, then restart the node. ZK didn't have a chance to shutdown cleanly and so we get this issue.

This raises the question of whether we should recommend/promote the full on embedded approach, two reasons:

1) ZK doesn't feel like a thing you can play fast and loose with when it comes to resetting/restarting, as you do with REPLs, and indeed, how we do things with the current production JUXT website. I have to admit however, this point is more of a feeling that being data-driven. The real problem is:

2) In the REPL, people kill the buffer/process all the time, and let's be honest, on deployment machines they kill Java processes too.

You can overcome this by deleting the Crux data dir and restarting, but obviously we'd need to give users a more fine tuned / fail-safe recovery path that doesn't delete data.

I confirmed that when you cleanly shutdown the node prior to killing the Java process, all is good when you try to fire up a node subsequently.

I think, it's worth challenging if we want to climb this particular hill with ZK/Kafka embedded. You can run Crux easily enough talking to an external kafka/ZK, and also, you can run Crux without Kafka at all if you use the KV Tx log. This latter approach hasn't been fullly embraced/tested yet, and it needs certain work completing such as xtdb/xtdb#2028 and xtdb/xtdb#6 . 

Once we decide on the recommended approach, we should review the example integrant system. 

There's also the option of changing the start/stop of Kakfa so it only happens on an integrant `halt` vs `suspend`, but this doesn't help us with the real issue, the Java process being killed uncleanly. That being said, it's still worth considering to remove the noise and to speed up the reset.

**Comment by hraberg** [comment]
Worth mentioning that to develop Crux itself we still need or at least prefer to use the embedded mode, so would be interesting to understand closer what can be done to mitigate this. My JVM (and laptop) frequently crashes when working on Crux, and don't run into this issue, though I think I've seen it.

Might have something to do with frequency of restarts or aiming for fast reloads. I don't think one wants to restart Kafka and ZK for every code change, like these are more background processes that happen to run in the same JVM.

**Comment by hraberg** [comment]
Somewhat related:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-273+-+Kafka+to+support+using+ETCD+beside+Zookeeper

If Kafka finally opened up this layer, having a version of the consensus protocol for single nodes (which always agree on everything) would remove the need to embed ZK itself. Like in practice, it doesn't add anything in a single node deployment, it's just a requirement to run Kafka. In theory one could write a stub for current Kafka and replace it with something simpler, but there are many potential gotchas with this. While in theory possible, understanding what the minimal implementation is would take time and effort.

**Comment by hraberg** [comment]
The Curator testing server does a few more things than we do in our embedded ZK:
https://github.com/apache/curator/blob/master/curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java#L172

Most interestingly, it explicitly closes the database and its files and not just the connection manager.

**Comment by hraberg** [comment]
The work on xtdb/xtdb#2031 with our own internal event log for standalone has someone mitigated this, but not solved this issue itself.

**Comment by hraberg** [comment]
As can be seen in the original stack trace, this issue seems to be somehow related to ephemeral nodes. We're now (see commits above) deleting the ZK data dir between restarts, as it doesn't contain any data necessary to keep around for the embedded case. This may or may not have solved this, we haven't seen this for a while. Closing this for now as mentioned above, xtdb/xtdb#2031 mitigates this.
