### ISSUE TITLE
Remove random EID -> ID mapping in k-d tree

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#2036]

**Comment by hraberg** [comment]
Solution somewhat unconventional. The internal id is now the first row-id of an entity in big endian. This spreads the bits of consecutive ids out a bit and won't unbalance the tree and grid as much, similar to the original reason for using random ids.

While the only input for the internal id is the initial row-id, it depends on eviction (see xtdb/xtdb#1950) to not alter the row-ids for any other entities. That is, once assigned, it has to stay the same.

As the internal id is a direct one-to-one mapping from its row-id, there's no dependency on the other ids or size of the map or to track for potential collisions.

There might be some issues with this approach, so not necessarily the last we see of this issue.
