### ISSUE TITLE
Rename and maybe split repository

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#2040]
We should:

1. rename this repo to xtdb-rnd.
2. maybe move core2 sub-folder to its own repo under the xtdb organisation.

An option is to wait doing the second part until we decided what C2's relationship to the main xtdb repo is, should it be a branch, a sub-folder there etc?

Datalog, Rust, Timeline (SQL and Flexbuffer) spikes could be cleaned up naming-wise and stay in the xtdb-rnd regardless.

None of this is urgent.

**Comment by jarohen** [comment]
My front-runner was to have core2 as a branch on the main XT repo? Eventually we'll want it there, assuming the desire to preserve stars is itself preserved...

**Comment by jarohen** [comment]
done for now. eventually, we'll want the core2 master branch pushed to xtdb master branch, issues migrated, existing xtdb master -> core1 branch, and stars preserved.
