### ISSUE TITLE
SQL - TPC-H round 1

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#2048]
Broadly speaking, TPC-H but without outer joins and nested sub-queries.

Queries: 1, 3, 5, 6, 10.

* Will involve `SELECT` (incl. aggregations), `WHERE`, inner `JOIN` (incl. implicit inner joins by inclusion in `FROM` + `WHERE`), `GROUP BY`, `ORDER BY`.
* Regarding tables - requires discussing/approving [ADR 0025](../blob/master/doc/adr/0025-sql-dynamic-schema.adoc)

**Comment by refset** [comment]
> [mbutlerw](https://github.com/mbutlerw) moved this from In progress to Done in [Core2 Development](https://github.com/xtdb/core2/projects/1#card-72596240) [on 19 Apr](https://github.com/xtdb/xtdb/issues/2048)

(I assume this meant to have been closed already)
