### ISSUE TITLE
Sync Results in NPE

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#205]
```
1. Unhandled java.lang.NullPointerException
   (No message)

                   RT.java: 1280  clojure.lang.RT/longCast
                    tx.clj:  406  crux.tx/await-no-consumer-lag/fn
                    io.clj:  117  crux.io/wait-while
                    io.clj:  114  crux.io/wait-while
                    tx.clj:  406  crux.tx/await-no-consumer-lag
                    tx.clj:  399  crux.tx/await-no-consumer-lag
             bootstrap.clj:  106  crux.bootstrap.CruxNode/sync
                   api.clj:  129  crux.api/eval47803/fn
                   api.clj:    9  crux.api/eval47628/fn/G
                      REPL:  214  poe-apps.store-manager.loader/eval66603
                      REPL:  214  poe-apps.store-manager.loader/eval66603
             [... repl stuff ...]
```

The root cause for this seems to be lack of merging in the `crux.bootstrap/default-options` in `crux.bootstrap.standalone/start-standalone-system`. See `crux.bootstrap.cluster-node/start-cluster-node` for reference.

**Comment by hraberg** [comment]
Note that merging all the defaults might cause some unintended side-effect. Not saying it will, but worth being aware of. At times Crux uses the presence of config keys to decide which component to use etc.

**Comment by atamis** [comment]
Hey, this is an potential bug I brought up on the Juxt Zulip board. This error actually occurred on a cluster system with an external Kafka service. You can see the code base that generated this error at [atamis/poe-app](https://github.com/atamis/poe-apps), but that repo has a _lot_ going on, so I'm working on a minimal example codebase.

Edit: I've uploaded a minimal reproduction of this bug at [atamis/crux-reset-bug](https://github.com/atamis/crux-reset-bug), however I succeeded too well. Originally, the crux system would work fine until the REPL got reloaded (`(reset)`), and then would error out. However, the linked repo features a set of reproduction steps that does not require any reloading.

**Comment by hraberg** [comment]
Thanks a lot for this @atamis. We'll have a look. Quick glance shows this happens even when providing a Duration to sync.

Note for anyone looking into this, my initial analysis is still valid even if it doesn't apply in this case, there are missing defaults in the standalone mode which could also result in NPE.

**Comment by hraberg** [comment]
@atamis, while we closed this, which is related to the time out issue, there was also another sentence in the original bug report I now recall:

> I'm not 100% sure how this happens, but basically I can start a Crux system, query it successfully once or twice, and then _something_ happens, and all my queries act as though the database is empty, and return no results (including queries for all ids).

Is this issue related or reproducible via the above repo(s)? Thanks!

**Comment by atamis** [comment]
Not sure what happened, but I can't reproduce the empty database issue any more; everything is working just fine. Which is good news, I guess. I'll let you know if I start having the issue again.

**Comment by hraberg** [comment]
Great, thanks a lot for trying @atamis, and as you say, please shout if you see it again.
