### ISSUE TITLE
Retrieve an entity by external id without going through query

### ISSUE THREAD

**Issue by tonsky** [xtdb/xtdb#209]
If I have an external id in an entity, e.g. `:post/url`. It seems wasteful to go through queries just to retrieve a single entity. This takes ~4ms on my machine:

```clojure
  (crux.api/entity
    (crux.api/db system)
    (ffirst
      (crux.api/q (crux.api/db system)
        {:find  '[e]
         :where '[[e :post/url url]]
         :args  [{:url "0RZbjKRle"}]})))
```

While this is just under a millisecond:
```clojure
  (crux.api/entity
    (crux.api/db system)
    #uuid "000218dd-2deb-033a-0000-00000000008c")
```

Also, the former is not very convenient and probably generates lots of unnecessary garbage during the call.

What I ideally want is something akin to Datomic’s lookup refs, where you can use `[<attr> <value>]` in place of an id:

```clojure
(crux.api/entity
  (crux.api/db system)
  [:post/url "0RZbjKRle"])
```

Thanks!

**Comment by hraberg** [comment]
Thanks for this @tonsky. We'll reflect on this, the way Crux works makes any non-id lookup basically be a query, but we can try to tune it. Crux caches compiled queries, so you may see faster lookups at consecutive runs?

As Crux is schemaless, there's no concept of uniqueness for anything but the id, but we can think about lookup refs or similar. This can always be provided at a decorator level from a pure API perspective. The aim is to keep the core API quite slim.

**Comment by tonsky** [comment]
Makes sense, thanks! Still it’s probably faster to go directly through indexes than through query?

> Crux caches compiled queries, so you may see faster lookups at consecutive runs?

Nope, this is as fast as it gets.

**Comment by hraberg** [comment]
OK, thanks for checking on consecutive runs.

Yes, we can likely tune the separate case better than going through the full query, but would prefer to sanity check if simple queries can be made faster in general first, as then we don't have to maintain the separate lookup ref code. This might be easy and worth it though, we'll look into it!

**Comment by kosiakk** [comment]
Datomic-style loopup ist, indeed, very useful for finding an entity by some secondary key. But navigation deeper into the graph structure requires a query anyway. Also composite keys are not supported in the short syntax.

I'd say such lookup syntax has rather limited use for nested data (as opposed to table-like models). Efficiency is, of course, important.

**Comment by hraberg** [comment]
Adding a reflection to this: in Crux you're encouraged to use external keys as `:crux.db/id`, which can be URLs, UUIDs as well as Keywords. As Crux never assigns ids on its own, you're always forced to supply a known (or generated) external id as the primary id. Not saying this necessarily removes the need for lookup refs or similar.

**Comment by tonsky** [comment]
Sure. But imagine something like a blog engine. Each post has a slug, which is a part of an URL. What type should I use? It’s not UUID, not a keyword (as the set of post slugs is not known in advance). It’s not an URL either, it’s just a part of the URL. Also URL feels a bit heavyweight when all you need is just a string? I would be happy with a string, but those seem to be the only type that Crux doesn’t support for ids. Why is that by the way?

Now, what if I want a numeric id? Like a tweet, just a number that I’ll autoincrement? Can’t put that into an id either. Multiple ids (legacy and new)?

**Comment by hraberg** [comment]
Yep, all your use cases are valid ones, and I definitely agree that this use case should be faster. Though for some cases using `:crux.db/id` for the external id might be the right solution, which might be overlooked - I didn't think of it in my first answer - so needed to mention it.

The short answer to not supporting numbers or strings is due to Crux being schemaless. These types are both treated specially to support range queries, see `crux.codec/ValueToBuffer`. The only attribute we can make any assumptions about is `:crux.db/id`, but that's not very useful on its own, as links to it would be from other attributes.

So when using external numeric ids you're forced to use a secondary attribute, just as you say.

**Comment by jonpither** [comment]
Hi @tonsky - I've done some testing via https://github.com/juxt/crux/commit/b08aa12cf6befea8d91dc60e5cc63b6c389133e6 and can't yet reproduce the sort of disparity being reported. Could you provide any more details on the sort of data volume you have in Crux that you're testing against? Against the KV implementation? (Rocks vs Mem for example)

**Comment by tonsky** [comment]
@jonpither 500 documents, RocksDB local, UUID ids

**Comment by refset** [comment]
@tonsky a change in the previous release enabled arbitrary maps (that may contain vectors) to be used as IDs: https://github.com/juxt/crux/issues/245

Example:
https://github.com/juxt/crux/commit/dd03a3613f9a076116d87ca0500f2350302ecec8

Would this satisfy your requirements?

**Comment by tonsky** [comment]
@refset that looks cool! It definitely solves my case, thanks. Might not cover multiple external ids, but I don’t have those yet. Thanks again! Great stuff
