### ISSUE TITLE
Bitemp Indexes

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#21]
We want to support bitemporality. In our model the easiest way should be to add a transaction time at the end of the index key, as business time is the usual axis for query. When querying for transaction time, business time can default to transaction time if not given, as there can (?) be no writes in the future. When transaction time is not given, it defaults to now, or the last part of the index is simply ignored.

Needs further analysis.

**Comment by hraberg** [comment]
Transaction time is controlled by Crux when transacting, and cannot be set by the user. As mentioned above, we might not want to support writes into the future, but there might be valid business reason to write a future value. If querying for future values, the user needs to provide the business time.

**Comment by jonpither** [comment]
This issue needs acceptance criteria, possible breaking up (i.e. move the insert-in-future' into a subsequent issue).
