### ISSUE TITLE
Quantified Comparisons (IN/ALL etc.) should respect and return 3VL results when unable to be converted into a join.

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/xtdb#2122]
For example

```SELECT ( NULL ) IN (SELECT 1 FROM tab1 WHERE FALSE) FROM tab1```

Should return NULLs not FALSEs as it currently does. 

Suggested Approach

>So all/any exists as agg functions directly, my assumption is that one can do the expression and then simply aggregate it into a column (like the exists, but not hard-coded to true/false and respecting 3VL).

**Comment by jarohen** [comment]
see xtdb/xtdb#2157, I assume
