### ISSUE TITLE
Automate running of bench reports daily

### ISSUE THREAD

**Issue by megakorre** [xtdb/xtdb#214]
We would like to have the bench runner create reports for the current versions of crux regularly to be able to detect regression of performance and to be able to evaluate improvements.

## Tasks
* deploy master branch on commit to the bench runner in circle-ci
* have the bench runner run itself once per day

**Comment by refset** [comment]
Acceptance criteria: let's see what difference this made https://github.com/juxt/crux/pull/255

**Comment by jarohen** [comment]
closing in favour of split-out bench cards, #389
