### ISSUE TITLE
Cannot parse signed long min value as a literal

### ISSUE THREAD

**Issue by wotbrew** [xtdb/xtdb#2172]
I suspect may matter less once we support bignums, but technically we are currently supporting the full 64bit range of signed integers - and that is not exactly true.

Repro 

```sql
SELECT a.a FROM (VALUES (-9223372036854775808)) a (a)
```

This as the plan parses signed numbers as longs without the sign, but if you remove the sign `9223372036854775808` is higher than the max `9223372036854775807`

**Comment by jarohen** [comment]
@hraberg adds that `exact_numeric_literal` cannot deal with `Long/MIN_VALUE`, _nor keep precision_ 

(emphasis mine)
