### ISSUE TITLE
EBNF Gap Analysis and Summary

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#2192]
We should turn off rules that we don't expect to touch/implement in the near-term (pre-SL), and surface forgotten issues we may want to fix.

As an outcome we will be able to assemble a top-level `SQL.adoc` that attempts to document our current + expected coverage, and our quirks (e.g. current `SELECT *` behaviour, which is well-defined but surprising). This subsequent work can be tracked as a separate ticket, or not.

E.g. evaluate casts, and types at a minimum

**Comment by jarohen** [comment]
Covered by the cards created in the planning session the other day, mainly xtdb/xtdb#2214?
