### ISSUE TITLE
Wrap Runtime Errors such as java.lang.RuntimeException: cardinality violation in SQL/User facing reporting.

### ISSUE THREAD

**Issue by mbutlerw** [xtdb/xtdb#2229]
we have a pattern for IllegalArgumentExceptions which mean they carry some data, and can get correctly serialised over an HTTP wire (see core2.error) - I suspect a similar pattern should work well for RuntimeExceptions

* [x] Create `core2.RuntimeException` with `ex-data`, replace existing thrown RuntimeExceptions with C2 variants.
* [x] Translate existing IAE throws into `err/illegal-arg`s so that it's easier to yield sensible error codes
* [ ] Translate these errors into pgwire-compatible error codes, etc.

**Comment by wotbrew** [comment]
Pgwire flows the messages as internal errors, no mapping to error code happens in pgwire yet for the most part, so doing this particularly for runtime errors may be premature
