### ISSUE TITLE
Cache Entities During Queries

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#231]
Currently we're doing bitemporal resolution for an entity each time it's encountered, but the same entity might be encountered many times during a query, so we could experiment with adding a query-scoped LRU cache around the EnityAsOfIndex.

**Comment by hraberg** [comment]
In practice this would mean adding a new `CachedIndex` thing wrapping `EntityAsOfIndex`, and lift up the creation of them out of `update-binary-index!` and only create one and wrap it in the cache in `db` which already has a query cache for example. Note that the new cache shouldn't be created using `lru/get-named-cache` as its scope is per db.

**Comment by refset** [comment]
WIP: https://github.com/juxt/crux/pull/235
