### ISSUE TITLE
Cache Keys Needs to be Unpooled

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#236]
The recent change to #222 leads to pooled buffers being put in the cache, which isn't good, as this will lead to memory leaks. One easy change to this is to go via `(-> k new-id safe-id ->id-buffer)` or something similar.

If a key that was read straight out of the KV store accidentally got cached, it would could further lead to JVM crashes as this memory isn't managed by Crux.

**Comment by hraberg** [comment]
The current problem sits inside `CachedObjectStore`, but might potentially be more widespread as other caches could be affected (I don't think so). The new cache explored in #231 shared the problem.

**Comment by hraberg** [comment]
One can try to avoid the allocation on lookup in various ways. This could be done by adding an arity to `compute-if-absent` which allows modifying the key before storing it, similar to above.

**Comment by hraberg** [comment]
Note that it's only the calls to `compute-if-absent` inside the `get` operations that needs to be fixed (in one way or another), as the `delete` and `put` operations don't store the keys in the cache itself, but just evict and just pass it on down.

**Comment by hraberg** [comment]
Unrelated, but the nested call to `get-objects` with a single key could be replace with `get-single-object`, this method likely didn't exist when this cache was first written.

**Comment by spacegangster** [comment]
fixed in #255
