### ISSUE TITLE
Multi-Valued Attributes

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#24]
We want to support more than one value for an attribute, similar to Datomic's cardinality many.

An extension of this is to support actual types apart from (the implicit) sets, primarily lists but maybe also maps. This might be easier done using documents and not triplets. This card does not necessarily need to go that far, as that probably requires changing the underlying model.

**Comment by hraberg** [comment]
This will be supported by design in the document store, see #27, but keeping this card for the current triple store.

**Comment by jonpither** [comment]
Suggest we split this card up, have one for triple and one for doc.
