### ISSUE TITLE
Intermittent sparql test fail on java-8 (hotspot)

### ISSUE THREAD

**Issue by spacegangster** [xtdb/xtdb#242]
### crux.kafka-test/test-can-transact-and-query-using-sparql

Happens sometimes in a test suite. Can't yet find a reliable way to reproduce it.

```
lein test :only crux.kafka-test/test-can-transact-and-query-using-sparql
                                                                       
FAIL in (test-can-transact-and-query-using-sparql) (kafka_test.clj:323)
transacting and indexing                                                                                                                                              
expected: (= {:txs 1, :docs 8} (k/consume-and-index-entities consumer-opts))                                                                                        
  actual: (not (= {:txs 1, :docs 8} {:txs 0, :docs 0}))
```

Results in 9 assertions failed, which depend on that sparql ingestion.

 Reproduction steps
0 set java 8 (jdk1.8.0_202.jdk or jdk1.8.0_181.jdk in my case (HotSpot))
1 work as you do normally
2 run a test suite.

Not digging it actively. I will update the card if more details happen to me.

**Comment by refset** [comment]
Needs re-validating since latest `sync` changes

**Comment by spacegangster** [comment]
At the moment, I can't reproduce it for three consecutive runs on different VMs. Closing.
