### ISSUE TITLE
Crash when using maps as IDs

### ISSUE THREAD

**Issue by AdamNiederer** [xtdb/xtdb#245]
Currently, maps are allowed as IDs, but `crux.tx/tx-ops->docs` will treat them as documents and throw an exception after failing to retrieve an id from them.

Example code which exhibits this behavior:

```clojure
(let [% {:crux.db/id {:user "Xwop1A7Xog4nD6AfhZaPgg"}, :name "Adam"}] 
  (tx-ops->docs [[:crux.tx/put (:crux.db/id %) % #inst "2019"]]))
;; IllegalArgumentException: Document's id does not match the operation id:  {:user "Xwop1A7Xog4nD6AfhZaPgg"}
```

**Comment by hraberg** [comment]
The ability to use maps as ids is actually an accident, and we might stop this being allowed. Though it can on the other hand also be useful of course.

That said, it should either work as expected or give a more reasonable exception.

The reason maps can be treated as ids is that we use this to calculate the content hash for the documents themselves and reuse the id protocols for this. We have debated removing this ambiguity, as they were originally not intended to actually be used as keys.

**Comment by jonpither** [comment]
It works now - to have a map as an ID. The debate could still loom, as it's still an accidental feature, but I'm content to close this issue.
