### ISSUE TITLE
Rules do not bind doc in metadata

### ISSUE THREAD

**Issue by SevereOverfl0w** [xtdb/xtdb#248]
Example:

```
(crux/submit-tx (dev/crux-system)
                  [[:crux.tx/put ::tech {:crux.db/id ::tech
                                         :foo "Technology"}]
                   [:crux.tx/put ::programming {:crux.db/id ::programming
                                                :foo "Programming"}]
                   [:crux.tx/put ::clojure {:crux.db/id ::clojure
                                            :foo "Clojure"}]
                   [:crux.tx/put ::spec {:crux.db/id ::spec
                                         :foo "clojure.spec"
                                         :rel [::clojure]}]])

(map meta
       (crux/q (crux/db (dev/crux-system))
               '{:find [?e]
                 :where [(foo ?e)]
                 :rules [[(foo ?e)
                          [?e :foo]]
                         [(foo ?e)
                          [?a :rel ?e]
                          (foo ?e)]]}))

;; =>
({?e #crux.query.BoundResult{:var ?e, :value :io.dominic.koni.core/programming, :doc nil}}                                                                                                             
 {?e #crux.query.BoundResult{:var ?e, :value :io.dominic.koni.core/tech, :doc nil}}                                                                                                                    
 {?e #crux.query.BoundResult{:var ?e, :value :io.dominic.koni.core/spec, :doc nil}}                                                                                                                    
 {?e #crux.query.BoundResult{:var ?e, :value :io.dominic.koni.core/clojure, :doc nil}})
```

Doesn't happen if there's only one version of the rule.

**Comment by hraberg** [comment]
First I thought this has to do with `:full-results?` but locally we still add the meta data it seems, this behaviour should potentially be removed.

What actually happens here though might be the fact that the results gets bound in the rules themselves and this is not propagated upwards. If this is a bug or not warrants some discussion. This may or may not be easy to fix, long time ago I looked at this code. Rules are implemented as `or-join`.

**Comment by SevereOverfl0w** [comment]
https://github.com/juxt/crux/blob/81da4631da09d1dd170eab65f9654c3367c32602/src/crux/query.clj#L808-L816

These lines likely account for why the problem does not occur when there's only one rule branch.

**Comment by SevereOverfl0w** [comment]
`:full-results?` is affected by this bug (not sure if that's a surprise), so `:full-results?` is broken in combination with `or-join`.

**Comment by SevereOverfl0w** [comment]
https://github.com/juxt/crux/blob/81da4631da09d1dd170eab65f9654c3367c32602/src/crux/query.clj#L519 we appear to be landing on this code path, where `nil` is a hardcoded value for the doc.

**Comment by SevereOverfl0w** [comment]
Given that `or` on it's own does not work, I think there's some relationship. After analyzing `compile-sub-query` and `build-var-bindings` I'm not sure how to proceed.

I think that an or-join might need to know about it's subordinate `or` clauses in order to make this work, and currently the code treats them as adjacent to each other.  I'm not sure how you would recreate that hierarchy, or if it's even the appropriate way to target this problem.

**Comment by hraberg** [comment]
My guess is that what's kind of happening is that at the top-level, the `?e` is just and argument to the rule, and as such has no entity (and by extension, document) associated with it.

One could try to somehow grab the meta of the underlying result and reuse it at the higher level somehow. See the `has-free-vars?` usages in `build-or-constraints`. It explicitly takes the `.value` out of the `bound-result-for-var` here:
https://github.com/juxt/crux/blob/81da4631da09d1dd170eab65f9654c3367c32602/src/crux/query.clj#L655

If you add some `println`s around there you might see the docs you're looking for? The question is how to cleanly propagate this information upwards, the raw values are passed upwards via `update-relation-virtual-index!` a few lines below.

As you've seen, the rules are also at times expanded into their literal forms, which changes the internal behaviour a bit as well. The rules and the ability to add meta data have evolved in isolation, and there's been no holistic reflection - until this issue - on how they might interact.

**Comment by SevereOverfl0w** [comment]
https://github.com/juxt/crux/blob/81da4631da09d1dd170eab65f9654c3367c32602/src/crux/query.clj#L655 does indeed point at the boundvar that I would like to see in my result.

**Comment by hraberg** [comment]
I'm starting to think that the solution to this is to remove the meta data and full results as currently stands, as this exposes query engine internals. Instead, we make full results lookup the document for each variable which is in used in entity position again, most of these documents should be cached if done during the inner loop. The entity lookup could also use the new per-query entity cache.

This would all be a bit slower, but would require a lot less work and won't leak internals out over the API.

**Comment by hraberg** [comment]
An entity could be assumed being any variable used in an entity position regardless at what level in the query it sits. The query engine might already have this information internally.

**Comment by hraberg** [comment]
One way to look at this is that in the result tuple, instead of the entity id, there could be the entire document. We could also potentially change the API as well, so instead of a boolean, we have an explicit list of variables that should be turned into documents.

One could also make the case of removing this feature from the core all together, and let the user loop over and resolve the entities in the results manually. This would likely be quite a bit slower, but we should test that before dismissing it as a solution, that is, moving it to a decorator.

**Comment by hraberg** [comment]
Changing this to be even simpler, `full-results?` simply replaces any valid entity ids with their docs in the result tuple. We can revisit, but this will give most of the power decorators and the console needs from this.

**Comment by hraberg** [comment]
This solution won't be tuned for performance, and you can also get things resolved to entities you didn't directly expect to in some cases. I would prefer to fix the key problem and confusion in this card first and deal with any fall out in later cards if needed.
