### ISSUE TITLE
Extend `q` to also select meta DB attributes (valid time / transaction time / tx-id)

### ISSUE THREAD

**Issue by den1k** [xtdb/xtdb#267]
https://clojurians.slack.com/archives/CG3AM2F7V/p1561214889099800

I found that oftentimes I want to know when a entity has been transacted, for example when I want to sort results by recency. Currently I'm adding a `:entity/tx-time` field manually. It would be great if I could simply query for tx-time, even valid-time when provided.

I also noticed that history returns a content-hash. For `entity`, this would be valuable to be able to tell whether and entity changed before transacting it.

I think besides `:crux.tx/tx-id` all other keys could come in handy and I wouldn't know what the harm would be in providing tx-id as well.
```
:crux.tx/tx-time
:crux.db/valid-time
:crux.db/content-hash
:crux.tx/tx-id
```

**Comment by refset** [comment]
e.g.
```
{:find  '[?e ?s ?r ?t]
 :where '[[?e :snippet ?s]
          [?e :result ?r]
          [?e :crux.db/valid-time ?t]   ; <------------
          [(some-strings-include? ?search-string ?s ?r) ?match]]
 :args  [{:?search-string "test"}]}
```

**Comment by den1k** [comment]
Also should these values be available through `entity`? If not by default then maybe when passed a flag?

**Comment by refset** [comment]
I agree `entity` should be able to retrieve these values without too much trouble, however for the main query, accessing these values may only be possible/practical by reifying the transaction data as documents, e.g.

```
{:find  '[?e ?s ?r ?t]
 :where '[[?e :snippet ?s]
          [?e :result ?r]
          [?e :crux.db/tx ?tx]
          [?tx :crux.db/valid-time ?t]
          [(some-strings-include? ?search-string ?s ?r) ?match]]
 :args  [{:?search-string "test"}]}
```

This would almost certainly require the use of transaction functions, which we haven't got a solid vision for yet, although there is a closed issue with related discussion: https://github.com/juxt/crux/issues/121

We are keen to analyse this properly soon.

**Comment by refset** [comment]
After much reflection I think it is essential that `q` must only be aware of its context as a single point-in-time, provided by the `db` coordinates. Giving an engine designed for point-in-time queries access to any underlying history (vt or tt) would undermine the design goal of providing consistent queries against valid time.

For example, a query run at a specific vt (and current tt) really needs to return the same results when run at a later tt, assuming that the set of valid documents is identical for both points in time - however, if your query is given information about the "start" valid time of a given document, then you will break the desired consistency if you retroactively put a new version of that document later than that start time but before the vt of the query.

Reifying the valid-time information inside the document is the right way to go, should you need it, and this approach also enables support for efficient range searches when querying (as per other domain-level #inst attributes). It may feel somewhat like duplication or a waste of storage, but in the scheme of things, for most use-cases, it's pretty minimal.

When we officially release transaction functions (resolving https://github.com/juxt/crux/issues/121) we'll add some examples showing how reifying tx-time can be feasible too (vt is easy enough to do in user space already).

Doing something like this, outside of a query, is also okay:
```clojure
(defn list-by-ids-with-timestamps [{:keys [::node]} ids]
  (let [db (crux/db node)]
    (->> ids
         (map #(let [h (crux/history node %)]
                 (assoc (crux->id (crux/entity db %))
                       :created (-> h last :crux.db/valid-time)
                       :updated (-> h first :crux.db/valid-time)))))))
````

We're always happy to continue debating this, of course, but I'm closing this for now as there are no plans to change the query engine for the time being, although we are thinking beyond point-in-time bitemp queries in the long term! Thanks for the discussion :)

**Comment by refset** [comment]
Just noting that this has been possible since `$` (implicit `db` var) was added

```clojure
(defn get-vt-created [db eid]
  (with-open [h (xt/open-entity-history db eid :asc)]
    (-> (iterator-seq h)
        first
        ::xt/valid-time)))

(defn get-vt-last-updated [db eid]
  (with-open [h (xt/open-entity-history db eid :desc)]
    (-> (iterator-seq h)
        first
        ::xt/valid-time)))

(xt/q (xt/db my-node)
      '{:find [e vt-created vt-last-updated]
        :limit 1
        :where [[e :xt/id]
                [(dev/get-vt-created $ e) vt-created]
                [(dev/get-vt-last-updated $ e) vt-last-updated]]})

;;=> [[-219 #inst "2021-10-15T12:01:06.289-00:00" #inst "2021-10-15T12:15:11.020-00:00"]]
```
