### ISSUE TITLE
JDBC backend for tx-log

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#270]
TODO:

- [x] Postgres AND hsql test
- [x] Compaction
- [x] Eviction
- [x] Micro-bench
- [x] Rename column -> event_key
- [x] Sqlite test
- [x] Oracle Test (possibly make use of h2 oracle mode)
- [x] Eviction (handling the current error `Put, incorrect doc state`)

**Comment by refset** [comment]
e.g. bundling in-memory Postgres JAR for easy testing

**Comment by refset** [comment]
We may need new names for "ClusterNode" variants with different tx-log backends.

**Comment by refset** [comment]
We could introduce a new lower-level protocol hiding the EventLog ("Kafka semantics, similar to the generic KV store level") itself, sitting beneath the TxLog ("Crux semantics").
So Kafka, Moberg and JDBC would all be EventLog implementations, and there would be one TxLog wrapping them.
Then the consumption etc. could be pushed out, but there are some issues with that, as the different lower levels have slightly different needs and ordering etc.

**Comment by mitchelkuijpers** [comment]
I actually wrote a tx-log backend with ActiveObjects for Crux. I think a lower level protocol to make this easier could be really beneficial.

**Comment by refset** [comment]
@mitchelkuijpers nice! It's great to hear you were able to figure that out.

I also wanted to note that a `crux.kv.jdbc` implementation is perhaps another way of achieving this (though it may be the least elegant solution of all, and it would only be viable for use behind `tx-log`).

**Comment by hraberg** [comment]
A JDBC backed KV implementation might be useful for other things as well, so it's an interesting idea, and would be directly usable via Moberg as a tx-log.

For normal queries, the JDBC backed one is likely to be too slow - but this would depend a lot on the actual backing db. For the event log case, the JDBC KV implementation probably not optimal for the log use case. That said, as it's an easier incremental win, we should consider it. Good idea @refset.

**Comment by hraberg** [comment]
Also agree on exploring adding a lower level protocol here, especially if we implement a native JDBC tx-log, and then have 3 different implementations.

**Comment by hraberg** [comment]
If we build this around Moberg at the KV level, we need to revisit #176 as currently Moberg assumes standalone mode, but this would require a client version for it to be useful. This issue is kind of true for ingest-only usage of Kafka as well.

**Comment by jonpither** [comment]
@refset and I found a problem with the current design. Events are read in order, so if you have 

1) Doc
2) Put Tx
3) Doc (as part of eviction)

Then currently as implemented, transacting the 3 event will cause the 1st event to get deleted. This makes the event-log unreadable, as the contract is that a doc must be present for a tx to get properly processed / indexed.

Two ideas for fixing:

1) Split the event-log into two tables, with two different consumers, so that the doc will get processed eventually before the tx does (the tx consumer will have to block, as it does for Kafka)

2) Update previous records to insert a tombstone, and change the deletion logic to be a pre-insert step, to avoid duplication. (We move from compaction to de-duplication).

**Comment by jonpither** [comment]
A third option:

3) Rework put-tx, so it's not necessary for the doc to actually exist. If the doc doesn't exist, the put-tx could assume the doc has been evicted.

The downside is that this a fundamental rule being added, and it's pushes responsibility to the consumers to ensure the indexes remain consistent (i.e. the consumers are ensuring that docs have been processed ahead of txes).

**Comment by refset** [comment]
Once concern I have with Option 3. is that it might then preclude splitting the event-log later down the line (as in 1.), which may be desirable and necessary for performance reasons.

**Comment by jonpither** [comment]
Excellent point. It may make sense to split the event-log as in option 1 as it's more likely the destination.

**Comment by jonpither** [comment]
Ready for review. If @hraberg is OK with the overall shape of the code, there's an argument to add an index on `EVENT_KEY` for each dialect. You could possibly also consider making a conditional insert, to replace 2 sequential DB calls when inserting a document. You would need to test each dialect.

We also need to update the docs and give this a bit of road-testing. Whilst we're in alpha, I wouldn't stress getting the config input completely right, which could be assessed as part of #305.

**Comment by jonpither** [comment]
From @hraberg and I agree: "I would like some basic perf and the expected indexes added before encouraging people to use it"

**Comment by jonpither** [comment]
Closing - we have released crux-jdbc
