### ISSUE TITLE
Add the IMDB example to the test suite

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#277]

**Comment by hraberg** [comment]
Had a quick look at this, and resurrected the examples a bit to work with the modules. This example seems nice, but ingestion takes quite a while, so will be hard to add it to the normal test suite. We do of course already have several tests which need env variables set to be run, but me feeling is that we'll move away from that and have a more explicit slow test module or add them to benchmarks.

**Comment by hraberg** [comment]
Closing this for now as it takes way too long to ingest to add to the normal suite.
