### ISSUE TITLE
Datalog Console

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#28]
Use for testing in the cloud. A simple wep-app presenting a datalog console, using an embedded Crux, connecting to a provision kafka cluster.

This is a tool for development now, that may or may not graduate into part of the actual product.

**Comment by jonpither** [comment]
I don't mind if someone builds this out of Edge and blurs the lines with a sample app - to be discussed when the actual dev happens.

**Comment by jonpither** [comment]
Part of the acceptance criteria for this task is that we need a rapid way to redeploy the console to match changes happening in Crux core.

Not sure if this should be a separate repo or not - please instantiate the discussion in the crux slack.

**Comment by hraberg** [comment]
This might not be MVP.

**Comment by hraberg** [comment]
There are things like https://github.com/viebel/klipse and https://github.com/oakes/Dynadoc but they might be overkill for this.

Then there are things like http://gorilla-repl.org/ and https://github.com/clojupyter/clojupyter that can provide full "notebook"-style experience, which run against a Clojure server, Gorilla with full REPL access to it, so this is again not really what we want.

A leaner but potentially time consuming variant is to build the console straight on top of CodeMirror, https://codemirror.net/doc/manual.html, similar to this https://yogthos.net/posts/2015-11-12-ClojureScript-Eval.html (a few years old).

Then there's https://github.com/graphql/graphiql of course, which is also built on CodeMirror. As we're schema on read, supporting this is a later, more involved thing beyond MVP.

**Comment by hraberg** [comment]
There's the editor powering VS Code:
https://microsoft.github.io/monaco-editor/

**Comment by hraberg** [comment]
Removing this from MVP, needs further analysis and work.
