### ISSUE TITLE
JSON API over HTTP - part 1

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#284]
Users who aren't familiar with Java/Clojure will want to use the HTTP API directly (no client) and should not have to work with EDN. 

In Scope:

- [x] Users should be able to request JSON responses from all HTTP endpoints.
- [x] The endpoints that have streaming EDN responses should also have streaming JSON responses.
- [x] Where query params are currently submitted in EDN (e.g. `?eid=`, `?eid-edn=`), they should also accept `?eid-json=`
- [x] Query params submitted in camelCase should be accepted as if they were kebab-case (consider a middleware for this before it hits spec?)
- [x] JSON responses should have their keys camelCased, and any namespace qualification removed, for ease of use from JS. e.g. `"validTime"`, `"txTime"`, etc.  
- [x] Transaction function bodies (legacy and current) should be submitted as a string containing Clojure code, and read as EDN. 
- [x] Attributes in documents should be decoded to Clojure keywords and encoded to JSON strings, where appropriate (i.e. no string-keyed maps in Clojure). Kebab/camel casing in document attributes should be preserved.
- [x] tx operations (for submit-tx request and open-tx-log response) converted as above (`:crux.tx/put` -> `"put"` etc, dates parsed and encoded as necessary)
- [x] A separate set of tests specifically exercising the JSON API (assuming this won't get exercised by the standard api-test)

Out of Scope:

* Initially, the `/_crux/query` _request_ is considered out-of-scope (it should still be possible to receive query results in JSON format)
* Transaction function bodies will need to remain Clojure only. Transaction function arguments should be passed through as their JSON types (i.e. even if the transaction function expects keywords/symbols, JSON consumers will only be able to send them strings)

For reference & consideration:
https://github.com/tonsky/datascript/blob/master/test/js/tests.js
https://github.com/cognitect/transit-js

**Comment by hraberg** [comment]
Here's an example of how to read and write Transit for Crux:

```clj
(require '[cognitect.transit :as transit])
(import [java.io ByteArrayInputStream ByteArrayOutputStream])

(with-open [out (ByteArrayOutputStream.)]
       (let [writer (transit/writer out :json
                                    {:handlers
                                     {crux.codec.EDNId
                                      (transit/write-handler
                                       "crux/id"
                                       c/edn-id->original-id)}})]
         (transit/write writer {:crux.db/id #crux/id "415c45c9-7cbe-4660-801b-dab9edc60c84", :value "baz"})
         (with-open [in (ByteArrayInputStream. (.toByteArray out))]
           (transit/read (transit/reader in
                                         :json
                                         {:handlers
                                          {"crux/id"
                                           (transit/read-handler
                                            c/id-edn-reader)}})))))
```

**Comment by hraberg** [comment]
What's actually goes on the wire in the Transit example above would be this:
```js
"[\"^ \",\"~:crux.db/id\",[\"~#crux/id\",\"415c45c9-7cbe-4660-801b-dab9edc60c84\"],\"~:value\",\"baz\"]"]
```

**Comment by hraberg** [comment]
Using `:json-verbose` this becomes a bit nicer:
```js
"{\"~:crux.db/id\":{\"~#crux/id\":\"415c45c9-7cbe-4660-801b-dab9edc60c84\"},\"~:value\":\"baz\"}"
```

**Comment by hraberg** [comment]
Added this to `crux-kafka`. Should arguably be broken out to its own module as it pulls in Transit. These could also be used consistently in crux-kafka-connect potentially.

**Comment by hraberg** [comment]
Using JSON as is similar to the Datascript Javascript example is hard it Crux, as there's no schema, and no way to know what's an id or not without it or the right types or tags.

**Comment by hraberg** [comment]
This is somewhat of a hack, but as Crux currently depends on ids to be typed a potential idea for JSON is to rely that maps are ids in Crux, is to either simply provide `"crux.db/id"` directly as a reference, like `{"$ref": "my-id"}`, or for cleaner usage to have a decorator that takes an `"$id"` in JSON and copies it to under `:crux.db/id`, and lifts the value into a map like `{:$ref "my-id"}` (in the resulting EDN). This id would then hash to the same as any value looking like `{"$ref": "my-id"}` in a JSON document, like `{"friends": [{"$ref": "my-id"}]}`.

For queries written in JSON there would need additional decoration to translate the attributes in the basic graph patterns to keywords and to identify variables, potentially like this: `["?e" ":name" "Foo"]` would translate to `[?e :name "Foo"]`, As per above, a reference would still look like `["?e" ":friends" {"$ref": "my-id"}]` 

Another approach is to look at JSON-LD, there used to be a JSON-LD translator in the `crux.rdf` namespace way back. Here the special attribute is `@id` and a reference would be a map with this single attribute.

**Comment by refset** [comment]
Riffing on @hraberg's suggestions (4th September 2019), I spiked a very rough JSON translation inside `crux-http-server` using cheshire:
https://github.com/refset/crux-1/commit/bcf1f7f36754798b0d41fda1783dc367befe5c9d

```
curl -X POST \
     -H "Content-Type: application/json" \
     -d '[["crux.tx/put", {"crux.db/id" :{"crux.db/json-id":true,"my-id":"ivan15811"}, ":name": "Ivan",":last-name": "Petrov"}]]' \
     localhost:3000/tx-log

> {"crux.tx/tx-id":1617450525597697,"crux.tx/tx-time":"2020-01-20T17:32:08Z"}

curl -X POST \
     -H "Content-Type: application/json" \
     -d '{"query": {"full-results?": true, "find": "[e]" , "where": "[[e :crux.db/id _]]"}}' \
     localhost:3000/query

> [[{"crux.db/id":{"crux.db/json-id":true,"my-id":"ivan15811"},":name":"Ivan",":last-name":"Petrov"}]]

curl -X POST \
     -H "Content-Type: application/json" \
     -d '{"eid": {"crux.db/json-id":true,"my-id":"ivan15811"}}' \
     localhost:3000/entity

> {"crux.db/id":{"crux.db/json-id":true,"my-id":"ivan15811"},":name":"Ivan",":last-name":"Petrov"}
```
The limitations of this approach are not 100% clear, e.g.

- sets might be workable but probably shouldn't be allowed
- interop with clients submitting regular edn documents needs to be handled carefully or prevented entirely

Worth exploring: http://metosin.github.io/ring-middleware-format/ring.middleware.format-response.html

On reflection this would be a better id scheme: 
`{"crux.db/id": {"crux.db/json-id": "ivan15811"} ... }`

**Comment by alexisread** [comment]
I'd possibly suggest using **json schema** as an intermediate step to just json - it can bidirectionally map to edn well (https://github.com/luposlip/json-schema),
and it looks like it's being considered for querying as well: https://juxt.pro/blog/we-need-to-talk-about-json

There are tools for json schema in most languages, including UI generators etc.
There's also interop with json-ld (and hence RDF) if you add a number of fields to the schema:
https://www.w3.org/2019/wot/json-schema#interpreting-json-schema-as-json-ld-1-1

**Comment by refset** [comment]
Given we are unlikely to initially provide json queries, signposting to edn libs such as https://github.com/jorinvo/edn-data is probably a good idea.
