### ISSUE TITLE
Doc and tx spec enhancements

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#285]
Open for debate.

In the document spec:
- Restrict vectors from being keys (it currently complains that the vectors can't be converted to IDs) -- only maps work OR enforce keys as keywords (slight performance hit either way)
- Sanity check other possible invalid document structures, nested types etc.

In the transaction spec:
~~- Relax both tx and op specs to accept seq (currently they only accepts vec)~~
~~- Can the spec changes accept seqs but also reject maps? Or is there a sensible/useful format to accept maps here?~~

**Comment by refset** [comment]
Via @den1k on #crux in Clojurians Slack...

Crux seems to quietly error when transacting an object it can't serialize. For example:
```
(defn foo [])
(submit-tx system [{:entity/foo foo}])
```

It does not error, but what's worse, it doesn't seem to recover. The db needed to be restarted.

**Comment by hraberg** [comment]
The second part of this looks like a bug, so let's treat it as one.

**Comment by hraberg** [comment]
Looks like both Kafka and Moberg will serialise first and only later actually submit the doc, so cannot reproduce the second part. Specs for docs have also been beefed up a bit.

**Comment by den1k** [comment]
@hraberg this happened to me using rocksDB

**Comment by hraberg** [comment]
@den1k, thanks, this is what I tested against as well. Let us know if you encounter it again. And thanks for the report in the first place, have not tested much with "bad" data.
