### ISSUE TITLE
Improve simple query performance for non-id entity lookups

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#287]
This was discussed in #209 and needs reproducible benchmarks and further analysis.

**Comment by hraberg** [comment]
Will have a glance at this to see if something obvious stands out. There will otherwise be a concentrated performance push in a few months once we get #214 and related cards going again.

**Comment by hraberg** [comment]
A quick glance shows that queries on ids and non-ids are quite similar in speed, but that going via the `entity` API call is much faster, which isn't surprising, as this doesn't involve the full query engine.

**Comment by hraberg** [comment]
It's worth noting that lookup refs would work differently in Crux, as Crux has no schema and also no concept of uniqueness for non ids, so it wouldn't make sense in the context of the `entity` call as it might return an arbitrary number of unrelated entities.

**Comment by hraberg** [comment]
An upfront cost which hits simple queries harder is using spec to both assert and conform the query.

Running 10000 simple single clause queries.
Without caching of specs:
"Elapsed time: 3532.561026 msecs"
"Elapsed time: 2939.512272 msecs"
"Elapsed time: 2902.018557 msecs"

With caching of specs:
"Elapsed time: 2492.809189 msecs"
"Elapsed time: 1888.351576 msecs"
"Elapsed time: 1844.571226 msecs"

Which is a 30-35% speed up for small queries, where execution time is small compared to preparing the query. Haven't tried with larger queries, but they should also benefit of course, but would be less noticeable.
