### ISSUE TITLE
Build Kafka sink connector

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#292]
e.g. https://www.confluent.io/connector/kafka-connect-neo4j-sink/ & https://github.com/neo4j-contrib/neo4j-streams

**Comment by jonpither** [comment]
- [ ] Make use of monitoring interceptors to send metrics to the control center

**Comment by hraberg** [comment]
We probably going to start with a simple sink to get existing Kafka data into Crux.

**Comment by hraberg** [comment]
At the end of the day, in the usual case, this is a matter of mapping data from a Kafka topic and submitting them to two other topics (doc and tx), maybe Kafka Streams would be more natural here? There's something called the Processor API there, which includes stream to stream transforms, but doesn't seem like a perfect match.

Regardless, there's somewhat of a dependency on  #176 here, as the sink shouldn't be an entire node. One could also use the HTTP API, but that's kind of roundabout, as the data is already in Kafka, and will go back into it in the normal case. Though the source and sink Kafka cluster might not be the same.

In the basic case, the sink would accept documents in some form that can be mapped to edn, and create put transactions for it on the other side in Crux. Kafka has its own concept of message schema which may or may not be of use here.

Another approach is to have a Kafka topic contains Crux transactions (this could use the stream transforms to create them) and simply forward them by submitting the to Crux.

**Comment by hraberg** [comment]
https://docs.confluent.io/current/connect/devguide.html

**Comment by hraberg** [comment]
https://github.com/apache/kafka/tree/trunk/connect/file/src/main/java/org/apache/kafka/connect/file

**Comment by hraberg** [comment]
At some level, the Mongo connector is likely to answer most of the questions regarding serialisation etc:
https://github.com/mongodb/mongo-kafka

**Comment by hraberg** [comment]
https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained

**Comment by hraberg** [comment]
https://github.com/humio/kafka-connect-hec-sink

**Comment by hraberg** [comment]
We might be able to build a source connector as well, using the `tx-log` API enriched with documents. Exactly what should be sent out is less obvious. The exact enriched transactions could be useful for certain use cases - potentially even replication - but something more document oriented, potentially with the ids as keys and no bitemporality might be more generally useful.

**Comment by hraberg** [comment]
This test shows how to start the connect worker in process if we would want to:
https://github.com/mongodb/mongo-kafka/blob/master/src/integrationTest/java/com/mongodb/kafka/connect/embedded/EmbeddedKafka.java

**Comment by hraberg** [comment]
Reflecting more on the source version of this, it's technically possible, but not too useful out of the box, so think we'll park that. There are many concerns around what to do with bitemp, how and if to slice up transactions etc.

**Comment by hraberg** [comment]
There's some relationship here to #284.

**Comment by hraberg** [comment]
Would we decide to build a source this might be of interest:
https://debezium.io/docs/tutorial/

**Comment by hraberg** [comment]
This will evolve, but closing the initial card.
