### ISSUE TITLE
Spike middleware approach for enforcing a common schema

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#30]

**Comment by jonpither** [comment]
Data writes should be rejected if the data doesn't match the predefined schema.

**Comment by hraberg** [comment]
So this could be done when submitting the transactions via submit-txs in the crux.core.TxLog protocol. Or potentially by wrapping this.

**Comment by hraberg** [comment]
Closing after discussion, we might revisit it. This assumes that Crux can handle different types of the same attribute.
