### ISSUE TITLE
ID support not according to spec (Valid IDs)

### ISSUE THREAD

**Issue by ThomasKaemmerer** [xtdb/xtdb#303]
In https://juxt.pro/crux/docs/transactions.html#_valid_ids URIs are declared as valid IDs. The URI Spec (https://tools.ietf.org/html/rfc3986) allows a wide varity of strings to be recognized as a URI.

I've used an URI modelled like the mailto-URI (explicit mentioned as an valid URI in the CRUX specification): 'dfid:35133@S.SBRM.db.de' but the usage `:crux.db/id #crux/id `dfid:35133@S.SBRM.db.de throws an exception `:cause "Invalid constituent character: @"`.

Changing the '@' to '.' in the edn `:crux.db/id #crux/id dfid:35133.S.SBRM.db.de` throws another exception `:cause "No implementation of method: :id->buffer of protocol: #'crux.codec/IdToBuffer found for class: clojure.lang.Symbol"`.

Trying both variants as strings `:crux.db/id #crux/id "dfid:35133@S.SBRM.db.de"` or `:crux.db/id #crux/id "dfid:35133.S.SBRM.db.de"` throws the exception `:cause "Not a SHA1 hex, keyword, URL or an UUID string: dfid:35133@S.SBRM.db.de"`/`:cause "Not a SHA1 hex, keyword, URL or an UUID string: dfid:35133.S.SBRM.db.de"`
Better but why no URIs?

So i've transformed my URI to an `:keyword` But even the a keyword could not be used as ID `:crux.db/id #crux/id :dfid/de-db-SBRM-S-35962`  throws another exception `:cause "Don't know how to create ISeq from: clojure.lang.Keyword"`.

**Comment by refset** [comment]
Hi @ThomasKaemmerer thanks for opening the issue. You are right that not all URIs seem to work.

"mailto:" was the main URI format I tested that worked without an issue. I tried briefly to understand why other seemingly valid URIs (e.g. ones found here: https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) wouldn't work correctly. Crux relies on standard Java URI methods for converting the URI into bytes, as seen in `codec.clj`: https://github.com/juxt/crux/blob/25ac5046a2fe3c9536bfbaa428007b385a83167c/crux-core/src/crux/codec.clj#L255-L257

We will investigate this further and report back soon (although we would be very happy to collaborate if you are particularly keen to have this resolved quickly - do let us know).

In the meantime, you could consider transforming your URIs into keywords, using something like we used in `crux-rdf` for handling IRIs as IDs: https://github.com/juxt/crux/blob/7d44cc7d2b020015aa84e53f0e95f5cc9a2b5b4c/crux-rdf/src/crux/rdf.clj#L28-L34

**Comment by ThomasKaemmerer** [comment]
The `:keyword` attempt seems to be parsed but lead to the exception `:cause "Don't know how to create ISeq from: clojure.lang.Keyword"`...

**Comment by refset** [comment]
Hmm, your keyword example seems to work for me with & without the `#crux/id` reader:

```
> (crux/submit-tx
  node
  [[:crux.tx/put
    {:crux.db/id :dfid/de-db-SBRM-S-35962
     :name "Pablo"
     :last-name "Picasso"
     :location "Spain"}
    #inst "1881-10-25T09:20:27.966-00:00"]]) ; valid time, Picasso's birth
#:crux.tx{:tx-id 1600889706574849, :tx-time #inst "2019-07-17T13:07:34.077-00:00"}

> (crux/submit-tx
  node
  [[:crux.tx/put
    {:crux.db/id #crux/id :dfid/de-db-SBRM-S-35962
     :name "Pablo"
     :last-name "Picasso"
     :location "Spain"}
    #inst "1881-10-25T09:20:27.966-00:00"]]) ; valid time, Picasso's birth
#:crux.tx{:tx-id 1600889723259905, :tx-time #inst "2019-07-17T13:07:50.371-00:00"}
```

Which version of `crux-core`, Java and Clojure are you using?

**Comment by ThomasKaemmerer** [comment]
I'm using the latest Docker image (Standalone Webservice example). I've tried the `:keyword version` with and without the `#crux/id` reader. The result is the same exception `:cause "Don't know how to create ISeq from: clojure.lang.Keyword"`.

`curl -X POST -H "Content-Type: application/edn" -d '[	:crux.tx/put
	{
		:crux.db/id #crux/id :dfid/de-db-SBRM-S-35962
		:train-number "35962"
		:train-product "S"
		:train-depature-call "FH"
		:train-depature-date-time #inst "2019-07-16T18:31:00.000+02:00"
		:train-departure-day-of-year "197"
		:train-departure-time "1831"
		:vehicle-unit-id "948004301271"
		:vehicle-journey-begin-call "FH"
		:vehicle-journey-end-call "FW"
		:vehicle-coupled-units []
	}
	#inst "2019-07-16T18:27:00.000+02:00"
	:crux.tx/tx-time #inst "2019-07-16T18:32:40.574+02:00"
]' http://localhost:8091/tx-log`

**Comment by refset** [comment]
@ThomasKaemmerer ah, that explains it. I don't think the last version I published was updated properly, for some reason. Sorry about that. Anyway, I have just refreshed the image with the very latest `1.3.0` release which includes the relevant changes.

Please pull the latest image and give it another go when you can.

**Comment by ThomasKaemmerer** [comment]
I've pulled the new image `Digest: sha256:a8e742ca4f809eb1321633634b79d17b4aa1f50fa806585ec64da338a82dace0
Status: Downloaded newer image for juxt/crux-standalone-webservice:latest` and the startup messages are different, so i'm pretty sure a new version is up-and-running - why is the ready message conatining the listing port now missing?

But even with this new version the behavement is unchanged:

`[{:type java.lang.IllegalArgumentException,
   :message "Don't know how to create ISeq from: clojure.lang.Keyword",
   :at [clojure.lang.RT seqFrom "RT.java" 553]}]`

is thrown using the invocation:

`curl -X POST -H "Content-Type: application/edn" -d '[	:crux.tx/put #crux/id :dfid/de-db-SBRM-S-35962
	{
		:crux.db/id #crux/id :dfid/de-db-SBRM-S-35962
		:train-number "35962"
		:train-product "S"
		:train-depature-call "FH"
		:train-depature-date-time #inst "2019-07-16T18:31:00.000+02:00"
		:train-departure-day-of-year "197"
		:train-departure-time "1831"
		:vehicle-unit-id "948004301271"
		:vehicle-journey-begin-call "FH"
		:vehicle-journey-end-call "FW"
		:vehicle-coupled-units []
	}
	#inst "2019-07-16T18:27:00.000+02:00"
	:crux.tx/tx-time #inst "2019-07-16T18:32:40.574+02:00"
]' http://localhost:8091/tx-log`.

**Comment by refset** [comment]
@ThomasKaemmerer I tweaked your snippet, so this should work for you now:

`curl -X POST -H "Content-Type: application/edn" -d '[[:crux.tx/put {:crux.db/id #crux/id :dfid/de-db-SBRM-S-35962 :train-number "35962" :train-product "S" :train-depature-call "FH" :train-depature-date-time #inst "2019-07-16T18:31:00.000+02:00" :train-departure-day-of-year "197" :train-departure-time "1831" :vehicle-unit-id "948004301271" :vehicle-journey-begin-call "FH" :vehicle-journey-end-call "FW" :vehicle-coupled-units [] } #inst "2019-07-16T18:27:00.000+02:00"] ]' http://localhost:8091/tx-log`

The changes I made were:

1. Transactions are a _vector_ of operations (such as `:crux.tx/put`), so wrapped your `put` in a vector
2. In the latest version of Crux you no longer need to restate the ID at the beginning of the `put` (since it is needless duplication)
3. I removed the `:crux.tx/tx-time` from the second-to-last position in your `put` vector. For complete clarity, the arguments that `put` takes are `<document> <valid-time-start> <valid-time-end>`, and you will need to query your Crux node between those two points in time in order to access the contents of the document.

I'm glad the Docker image updated correctly. I will take a look at the missing port message as well.

**Comment by hraberg** [comment]
Closing this for now. The ways ids are handled once you move out of the comfort zone of keywords isn't dealt with optimally. As of the original slightly different issue, we just use `java.net.URI` and don't try to claim to support this properly, it was mainly added as a potential convenience for some use cases.

Surely to be revisited.
