### ISSUE TITLE
Make config nested sub-maps 

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#305]
To marry up with the modules approach. This is instead of having a large, flattened map.

As part of this, also experiment to see if the API could work with a JSON config map - this may better suit people arriving at the Java API.

**Comment by refset** [comment]
Also, it would be helpful to expose more of the provided and interpreted config information in the `status` API, perhaps including the versions of each module.

And resolve this while we're at it:
`Reflection warning, crux/bootstrap.clj:25:33 - reference to field trim can't be resolved.`

**Comment by jonpither** [comment]
Am closing this issue in light of #340 . See comment https://github.com/juxt/crux/pull/340#issuecomment-543591512 for more information.
