### ISSUE TITLE
Refactor benchmark test

### ISSUE THREAD

**Issue by ovidiu-beldie** [xtdb/xtdb#310]
In order to expand on the current benchmark tests, a good initial step is to split the existing code into more and easier to manage namespaces. Another goal is to add more documentation and to facilitate easy exploration in the REPL. This issue is related to #85 and #149.

**Comment by ovidiu-beldie** [comment]
Progress update:
- bench tests: split into smaller, more manageable files
- cloud environment: able to create a k8s cluster; still need to deploy all the elements of the environment (such as kafka)

**Comment by refset** [comment]
For reference: https://github.com/juxt/crux/tree/bench-tests-explore

**Comment by refset** [comment]
Closing this for now as we reprioritise the broader task.
