### ISSUE TITLE
Duplicate CAS failure in CI

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#321]
Seen this enough times in CI now so we can assume it's not just a fluke and needs a looking at, started relatively recently AFAIK:

```
lein test :only crux.query-test/test-query-and-cas

FAIL in (test-query-and-cas) (query_test.clj:1330)
can update existing user last CAS command in tx wins
expected: (true? (api/submitted-tx-updated-entity? *api* submitted-tx :ivan))
  actual: (not (true? false))

lein test :only crux.query-test/test-query-and-cas

FAIL in (test-query-and-cas) (query_test.clj:1331)
can update existing user last CAS command in tx wins
expected: (= #{["Ivan 4th"]} (api/q (api/db *api* tx-time tx-time) (quote {:find [n], :where [[:ivan :name n]]})))
  actual: (not (= #{["Ivan 4th"]} #{["Ivan 2nd"]}))
```

**Comment by hraberg** [comment]
The idea is that later transactions ops generating identical keys "win" as they are put into the map passed into the kv store in the same order they was generated, so later keys should overwrite earlier ones.

**Comment by hraberg** [comment]
Actually, what happens as can be seen in the test output, neither of the new CAS operations have fired before the query is issued, meaning there's either a timing issue, bug or silent error somewhere.

**Comment by hraberg** [comment]
I've added more logging and output of the transaction log if this fails, but haven't been able to get it to happen again for a while. This will hopefully help next time it does, but will park this card until then.

**Comment by hraberg** [comment]
Some output of a recent failure, not sure what this means though, feels like there's not enough info:
```
FAIL in (test-query-and-cas) (query_test.clj:1333)
can update existing user last CAS command in tx wins
{:crux.tx/tx-id 1605054098515970, :crux.tx/tx-time #inst "2019-09-02T14:47:23.082-00:00", :crux.api/tx-ops [[:crux.tx/cas nil {:crux.db/id :ivan, :name "Ivan 1st"}]]}
{:crux.tx/tx-id 1605054098733059, :crux.tx/tx-time #inst "2019-09-02T14:47:23.294-00:00", :crux.api/tx-ops [[:crux.tx/cas {:crux.db/id :ivan, :name "Ivan 1st"} {:crux.db/id :ivan, :name "Ivan 2nd"}]]}
{:crux.tx/tx-id 1605054098842627, :crux.tx/tx-time #inst "2019-09-02T14:47:23.401-00:00", :crux.api/tx-ops [[:crux.tx/cas {:crux.db/id :ivan, :name "Ivan 2nd"} {:crux.db/id :ivan, :name "Ivan 3rd"}] [:crux.tx/cas {:crux.db/id :ivan, :name "Ivan 2nd"} {:crux.db/id :ivan, :name "Ivan 4th"}]]}

expected: (true? updated?)
  actual: (not (true? false))
```

**Comment by jarohen** [comment]
@hraberg haven't seen this one for a while, reckon we're good to close it?

**Comment by jarohen** [comment]
closing for now, let's reopen if we can repro it
