### ISSUE TITLE
Kafka Connect Source for Change Data Capture

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#324]
Depends on #323. Will publish change data capture events to a topic, preferably in a format similar to https://debezium.io potentially using `debezium-core` to do it, unclear if this simplifies this or not.

**Comment by hraberg** [comment]
Related to #292.

**Comment by hraberg** [comment]
In the first cut, this won't take bitemporal commits into account, and only send the live versions out. Bitemporal updates likely won't fit the debezium model. More importantly, they require queries to resolve what actually changed in case the update was a across a range.

We could consider "flattening" the transactions, so that the range operations generate more transactions operations instead of just index entries, and record this somewhere. Transaction functions could work a similar way..

**Comment by hraberg** [comment]
As #292 isn't merged yet, this work will happen on the same branch.

**Comment by hraberg** [comment]
Apart from trying to build on Debezium, one can go for simply mirroring the tx log with documents onto a new topic as is. Another alternative is to put a document per event, with the message as value, and entity id as key, and use nil for deletes. Regardless output, the source consumption would be similar of course.

**Comment by hraberg** [comment]
Considering adding a flag so one can switch between document and transaction mode (as described above) and skip Debezium style for now. One can also add a second flag for the desired format, edn or json. Avro could potentially be added later.

**Comment by hraberg** [comment]
This will evolve, but closing the initial card.

**Comment by hraberg** [comment]
The source should potentially have a mode where the valid time gets set to the original transaction time if it is not there? That is, Crux defaults valid time to transaction time, but should this default maybe be set at the origin?

**Comment by neuromantik33** [comment]
Sorry to resurrect a dead topic, but I was wondering if this feature was available in any version as I'm trying to experiment migrating an existing legacy postgres source of truth into crux, and providing an incremental source of transactions/documents would be grand for incremental refactoring.
I might add that the DB is a rails app, which by convention puts a created_at and update_at columns in every table, which might help to _mimic_ bitemporality.

Thanks for any advice!

**Comment by refset** [comment]
Hi @neuromantik33 we created the Kafka Connect sub-project here: https://github.com/juxt/crux/tree/master/crux-kafka-connect

You could, in theory, use this connector in conjunction with Kafka to stream data out of Postgres (e.g. using https://docs.confluent.io/debezium-connect-postgres-source/current/index.html) and into Crux.

You would need to build the latest version of our connector yourself, by cloning this repo and following the instructions in the linked readme. However, depending on your exact requirements you may even want to fork the connector and adapt it to your needs - what we have created is more like a template than a general purpose tool.

Note that we don't currently support "importing" transaction time, such as from an external created_at column (though we potentially could!). Feel free to open a new https://github.com/juxt/crux/discussions thread if you want more general feedback/advice on the various approaches :)
