### ISSUE TITLE
Consistent semantics for put/delete operations with valid time ranges

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#326]
We'd like to amend the put/delete semantics so that the behaviour is consistent, without the user needing to understand the implementation details of the internal Crux indices to reason about the query results they're seeing.

We think of each of these operations as a function operating over a timeline - for this spec, we'll think of a the value of a single attribute of a single entity, over time. Each operation can be thought of as a function taking a timeline and returning a new timeline.

We have four such operations:
* 'put' with a start and end valid-time - this should override the value in the timeline between the two valid times. Particularly, after the end valid-time, the operation shouldn't change the value (as it does currently) - the previous value should be restored.
* 'put' with a single valid-time - this should put the value between the provided valid time and the next time the value changes or, if there isn't a subsequent value, indefinitely. (Due to the way the Crux index updates are currently implemented when a put has a start and an end valid-time, this may not take effect all the way until the next value change - we'd like to fix this)
* 'delete' with a start and end valid-time - behaves like a put, putting a 'nil' value within the range.
* 'delete' with a single valid-time - likewise, behaves like put with a single valid-time, putting a 'nil' value until the value next changes.

Worked example:
* Put value 25 at vt=25 - if we then query any time after vt=25, we should expect '25' to be returned
* Then, put value 27 at vt in `[27, 30)` - we then expect to see 27 at vt=28, but then return to 25 at vt>=30
* Delete at vt=28 - expect to see no value returned at vt=29, but 25 returned again at vt>=30
* Put 20 at vt=20, expect to see 20 for vt in `[20,25)`, then 25 for vt in `[25, 27)`, and so on.

Separately, 'evict' also used to take valid-time ranges - these were temporarily removed as part of #428, but we expect to reinstate these with similar, consistent semantics, in the near future.

---
(original PR spec follows)

In this newly added test I validated that the effect of using the `end-valid-time` argument with `put` means that, whilst corrections within the range happen as expected, the corrected document is still visible _after_ the `end-valid-time`: https://github.com/juxt/crux/commit/34a43c697704fc50d56d66956c27233a427ad76e

This might be desirable behaviour in some circumstances and may be even sensible to leave as the default option. However, I propose that there are other variations for using `end-valid-time` with `put` which may be useful (and potentially even more intuitive):

1) The equivalent of `delete` could be inserted at the end of `end-valid-time` i.e. the test I added should fail because there shouldn't be any version at `v4-valid-time #inst "2018-11-30"` due to the equivalent of a delete operation at `end-valid-time #inst "2018-11-29"`
2) If the `put` range sits within a larger range of a single version, then `put` could effectively re-`put` the initial version at `end-valid-time` i.e. if version A is valid `2018-11-26 -> 2018-11-30` and you `put` version B with the range `2018-11-27 -> 2018-11-28` (using start & end-valid-time arguments) then version A should still be valid at `2018-11-29`

These variations could be handled using additional arguments, like `open-ended?` and `put-within?`, respectively.

Additionally, a similar concern applies to how `end-valid-time` is used with the `delete` operation, which currently ends up leaving a gap in the valid time history, where it could instead have the equivalent effect of making a `put` of the last version (within the range) at `end-valid-time`.

Another option is to rename the current `end-valid-time` to `correct-until-valid-time`.

**Comment by hraberg** [comment]
Having reflected on this, my feeling is that we keep it end-exclusive to not complicate things, like these are really two different issues. But we could consider adding an additional flag that resurrects the latest version within the range at the `end-valid-time`. Not sure what to call this flag, `slice-history?` or something.

**Comment by refset** [comment]
I agree that maintaining the current behaviours is the right answer.

> we could consider adding an additional flag that resurrects the latest version within the range

Assuming you are referring to the latest version within the _existing_ range here then great. Other suggestions for the flag name: `splice-history?`, `restore-end?`, `restore-prior-at-end?`, `splice-into-history?` (splice seems more accurate than slice)

In general I suspect most modelling / ergonomic concerns are fine to be handled using a set of higher-level operations that get converted into the low-level operations prior to submission.

**Comment by EzzatOmar** [comment]
Just starting looking into crux.
For a newcomer this is really confusing.

Example query.
```clojure
(crux.api/submit-tx
 crux-node
 [[:crux.tx/put
   {:crux.db/id :money
    :amount 100}
   #inst "2010-01-01"
   #inst "2015-01-01"]
  [:crux.tx/put
   {:crux.db/id :money
    :amount 300}
   #inst "2017-01-01"]])
;; => #:crux.tx{:tx-id 194, :tx-time #inst "2019-10-25T21:21:57.799-00:00"}

(crux/q
 (crux/db crux-node #inst "2016-01-02")
 {:find '[?e]
  :where '[[?e :crux.db/id :money]]
  :full-results? true})
;; => #{[{:crux.db/id :money, :amount 100}]}
```  

I really expected to query an empty set.  The problem I'm having with this implementation is that the term valid-time and end-valid-time gives me the impression of a document that only exists within the valid-time window.  So asking the db for a fact in this particular point in time we should expect the db to return only valid documents.

**Comment by refset** [comment]
Hi @EzzatOmar - thank you for your feedback and concise illustration. We will attempt to iron this out in the not-too-distant future. Thanks for your patience in the meantime & I hope nothing else is quite so confusing!

**Comment by jarohen** [comment]
As discussed, we're proposing to remove the 'end-valid-time' parameter from these operations - the current behaviour is evidently quite confusing, and it seems possible to achieve the majority of what's needed by simple combinations of vanilla puts/deletes

**Comment by hraberg** [comment]
After reflecting on this and discussed it at several times with @refset and @jarohen I'm now convinced that the low-level style it currently has is really the wrong thing to expose to the user. The range versions of put and delete should simply slice in the document (or nil) into the history.

**Comment by hraberg** [comment]
There's another problem here which we need to deal with, and that's having several operations in the same transaction affecting the same entity. When using ranges (regardless semantics) the versions to correct is found using the history API, but the this is done in the pre-condition, and while the operations are executed in order within a transaction, this means the end result might make no sense.

There are a few alternative ways to deal with this:
1. Merge ranges over the same entity across operations as a pre-processing step across all operations in a way consistent with writing them first-to-last .
2. Detect overlaps during pre-conditions and fail the transaction.
3. Outright disallow multiple operations on the same entity in the same transaction. But there are many valid use-cases for this though (like back-filling) so it's not a good alternative.
4. Introduce read transactions to allowing to read your own writes at as the transaction progresses, and deal with all issues that way. Doing this has some benefits, but is a chunky change affecting all KV implementations and effectively forces a rewrite of the transaction processing, so my feeling is "not now".
