### ISSUE TITLE
Transaction information embeddable inside of documents using constants

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#330]
Including constants such as `crux.tx/*valid-time*`, `crux.tx/*tx-id*`, `crux.tx/*tx-time*`, `crux.tx/*tx-ops*` and `crux.tx/*content-hash*` inside of documents is one potential solution to address the need for building and storing transaction metadata (e.g. capturing _who_ submitted a transaction and _why_). These constants would only be replaced during indexing.

This would hopefully resolve https://github.com/juxt/crux/issues/267.

This would also allow range scans within queries over `valid-time` that would otherwise require a user to both `put` at a specific `valid-time` and manually include that value within the relevant document.

Related: https://github.com/juxt/crux/issues/253 - though I think the requirement and solution for that is subtly different

**Comment by hraberg** [comment]
So it's a bit tricky reflecting on this, some constants are "easy", like tx-id and tx-time, as they're valid for the entire tx, valid-time and content-hash per operation, and potentially more than one operation. The catch-all tx-ops might help for cases where someone actually would want to deal with that.

Another bigger issue here is that by changing the values in the document, you change their content-hash, which might make this strategy somewhat questionable. Needs more analysis. That is, by introducing this you're really rewriting the document, so it's kind of like a form of transaction functions.

That said, the transaction functions themselves could have this transaction metadata made available to it somehow, either as bindings as here, or as an extra argument.

**Comment by refset** [comment]
I'm fairly satisfied that transaction functions are the way to go here until we have a clearer proposal. Good discussion!
