### ISSUE TITLE
Publish Kafka Connector(s) onto Confluent Hub

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#332]
This will be an unverified/community connector for now. The Confluent verification process will be the next task.

https://docs.confluent.io/current/connect/managing/confluent-hub/contributing.html

**Comment by hraberg** [comment]
Technically for step one, the main piece of work is to build the actual archive in the right format:
https://docs.confluent.io/current/connect/managing/confluent-hub/component-archive.html#confluent-hub-component-archive

They do provide a Maven plugin to help you with this, this may or may not simplify it. One can generate a pom from Leiningen, One can probably write another pom with the archive plugin referring to this if we went down this route. But it might be easier to just write a script.

**Comment by hraberg** [comment]
This source connector shows how to use JSON and turn it into Structs:
https://github.com/jcustenborder/kafka-connect-spooldir

What we're currently doing, just using a String schema and then produce various formats using a config is likely the wrong way to do it. Like it kind of works, but you lose some of the point of Kafka Connect.

**Comment by danmason** [comment]
- [ ]  Need to add features to generated manifest files

```
"features": {
    "confluent_control_center_integration": true,
    "delivery_guarantee": ["exactly_once"],
    "kafka_connect_api": true,
    "single_message_transforms": true,
    "supported_encodings": ["any"]
  },
```
