### ISSUE TITLE
Investigate Query Performance

### ISSUE THREAD

**Issue by Roxolan0** [xtdb/xtdb#334]
Things to measure:

- [ ] Speed

- [ ] CPU usage

- [ ] Memory usage

- [ ] Effect of running multiple parallel queries

- [ ] See also: current content of the DEBUG prints

We'd also like to check that queries actually work as intended. But that requires knowing the expected result, and it's a good bit of work in its own right, largely beyond the scope of this card.

See #328 for data sources.

**Comment by jarohen** [comment]
included under #389
