### ISSUE TITLE
Cloud deployment of benchmarking 

### ISSUE THREAD

**Issue by Roxolan0** [xtdb/xtdb#335]
For #328 and #334 

Initially these cards will only allow local testing, i.e. biased & limited by the performance of the user's machine. We want to be able to run the bench in the cloud, probably with Kubernetes.

Needs options for both single and multi-nodes.

This will eventually be needed as a fully fledged Crux feature, not just for benchmarking. That'll require a lot of work and is beyond the scope of this card.

**Comment by jarohen** [comment]
done, #389
