### ISSUE TITLE
Improve Benchmark result reports

### ISSUE THREAD

**Issue by Roxolan0** [xtdb/xtdb#336]
For #328 and #334

Currently the benchmark function returns a clojure map of the raw data - not particularly human-readable - and a few averages. Needs to produce a much friendlier report, likely with graphs.

Could use a simple graphing library: Plotly, SVG, Vega... This is a potential rabbit hole though; we don't want to spend too much time on it.

Could use the graphing capabilities of a monitoring tool. This kills two birds in one stone, since we want to set up monitoring eventually. But on the other hand it might take a while to get that working properly; we want quick wins.

**Comment by hraberg** [comment]
Does this potentially supersede #213?

**Comment by Roxolan0** [comment]
Yes (and in the long term we'll use more complex tooling anyway). I'll go ahead and close #213

**Comment by jarohen** [comment]
closing in favour of split-out bench cards, #389
