### ISSUE TITLE
Add Monitoring tooling

### ISSUE THREAD

**Issue by Roxolan0** [xtdb/xtdb#338]
Measure time taken by ingestions & queries in regular usage (though watch out for overhead), and pass that data to one or more of:

* Cods Hale Metrics (via metrics-clojure https://metrics-clojure.readthedocs.io/)

* Prometheus (https://prometheus.io/)

* Kibana

* AWS Cloudwatch (this could become a standard Crux feature)

**Comment by crimeminister** [comment]
I'll throw in a mention for [Riemann](http://riemann.io/) as a tool I enjoy using and which just so happens to be written in Clojure.

**Comment by jonpither** [comment]
How also, would you integrate with Splunk / Kibana.

**Comment by jarohen** [comment]
closing this as we've got a whole load of cards now under #384, and the 'prod-monitoring-384' label
