### ISSUE TITLE
Approximate dates for Beta? Evaluating

### ISSUE THREAD

**Issue by jeveloper** [xtdb/xtdb#339]
Hello there team!

Thank you for amazing work.

I am evaluating this product for a potential use for a project.
How likely will you be able to reach Beta by November/December or end of year? 2019

Thank you kindly and feel free to reach directly if this is sensitive.

**Comment by jonpither** [comment]
Hi @jeveloper thanks for the question!

After this batch of conferences - Strange Loop and ClojuTre - the team is going to meet and discuss the roadmap and the path towards Beta. We will reply on this issue and give some indication. Our main concern with going Beta is that we commit to not making breaking changes to the API. 

I don't think there are breaking changes that are in clear view - so we should be able to give some clarification in the next 2-3 weeks.

**Comment by jeveloper** [comment]
@jonpither  thank you Jon and i'll be happy to follow up later on.

**Comment by refset** [comment]
Hi @jeveloper our beta release plans quietly morphed into today's latest 1.9 release. You can consider this version a stable foundation for all manner of evaluations and long-term support (production users should always get in touch with us directly though!).

Feel free to reach out directly for any further questions: jdt@juxt.pro
