### ISSUE TITLE
Queries should allow Datasource to setup a context

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#34]
There's a large perf gain for Rocks in re-using Iterators in queries, especially where multiple seeks might be made. For example there's a 30-40% improvement for the `multiple-clauses` query in the micro-bench.

We could add a new protocol fn `in-context` to Datasource, so that queries's can surround query execution with this.

Some thoughts:

- the name `in-context` can be improved upon
- Since we may one day use reducers or pmap & friends, we should probably not use thread-locals and bite the bullet with a `context` arg to `iterate-with`. 

I had an initial attempt, but have decided to wait on implementing this, until a conversation is had around the above two points. It's also a straightforward change, so it's not critical at this stage (but would be critical prior to the MVP release).

**Comment by jonpither** [comment]
Another reason for a context map vs dynamic binding - I found myself wanting to pass through params such as `keys-only?` when the iterator is created. I got bit by the thread-local binding in bench.clj..

**Comment by hraberg** [comment]
Another reason for this is to ensure that we keep a consistent view of the underlying store when doing read transactions throughout a query. Both LMDB and Rocksdb have LMDB concepts we should be able to leverage.

**Comment by hraberg** [comment]
Opening an iterator does this implicitly in Rocks, so this is enough if one reuses the same iterator throughout the query. One can also acquire an explicit snapshot at the start of the query, and assign this to all iterators used in the same query. See:
https://github.com/facebook/rocksdb/wiki/Iterator#consistent-view
https://github.com/facebook/rocksdb/wiki/Transactions#setting-a-snapshot

(Using actual transactions in Rocks should not be necessary I think.)

In LMDB you always have to use a transaction, and a cursor is opened within the context of one.

**Comment by hraberg** [comment]
Currently implementing an approach with explicit snapshot (context) and iterators, which have to be used in with-open, allowing the caller to open several iterators etc.

**Comment by hraberg** [comment]
This is implemented now, via the new fns new-snapshot which returns KvSnapsthot which can be used to create any number of iterators via new-iterator. All these resources have to be managed explicitly using with-open by the caller. It's been wired in everywhere where iterate-with was used, but isn't actually used properly to take advantage of them, this would need the Datasource to have a snapshot and create iterators from it, but right now there are missing abstractions there to do this cleanly without spilling the kv level up to query.
