### ISSUE TITLE
Clean up doc/examples

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#341]
There's a lot of example test code written in good faith, that is now starting to add a tax. We should do a 'lean up' and concentrate on a solid set of docs. For example the example test code written into `docs/examples`. Much of this code - based on much earlier versions of Crux - I suspect no longer works as intended.

- [x] Add examples into testing suite, to automatically check for breakages on code changes
- [x] Do the same for 'query_examples'
- [x] Repair any broken examples
- [x] Add tutorials to test suite

**Edit**
With the merge of node-config-property, a number of examples will need to be fixed alongside the new structure being properly documented.
- [x] Fix examples within Crux (examples.clj jdbc node, examples within the REPL walkthrough)
- [x] Add tests for contents of REPL Walkthrough
- [x] Update tutorials on the website (Pending, push on release)
- [x] Properly document the configuration changes, in a number of places (Needs to be done with API reference)
- [x] Add notes to the documents about the topologies.

**Comment by danmason** [comment]
(Added a list item within the original post about adding tests for these examples to ensure they still work)

**Comment by danmason** [comment]
With the merge of node-config-property, a number of examples will need to be fixed alongside the new structure being properly documented.
- [ ] Fix examples within Crux (examples.clj jdbc node, examples within the REPL walkthrough)
- [ ] Update tutorials on the website
- [ ] Properly document the configuration changes
- [ ] Add notes to the documents about the topologies.

**Comment by jonpither** [comment]
Referencing https://github.com/juxt/crux/pull/340 for a list of outstanding work tasks, following on from the PR merge
