### ISSUE TITLE
Add slower running builds as jobs in CircleCI

### ISSUE THREAD

**Issue by danmason** [xtdb/xtdb#344]
- [x] Fix timeout issues within ts-devices / ts-weather
- [x] Add necessary data files for ts-devices and ts-weather to CircleCI
- [ ] Fix issues with circleCI running of long-build

**Comment by danmason** [comment]
A 'nightly' build is now added to the circleci and sets the necessary environment variables to run ts-devices and ts-weather, though the two still need their files to load.

**Comment by danmason** [comment]
Timeout issues within the two tests appear to come as a result of using kafka, causing the indexes to lag behind. Running using the in-memory database seems to work well for ts-weather, though results in a segmentation fault for ts-devices. 

Alternatively, either the partitioning can be removed or the database can wait between transactions (not utilizing the asynchronous nature of submit-tx). In both cases, the tests take much longer. Will continue looking into the issue, and see if there is another way to remove the timeout.

**Edit**: Currently fixed by increasing the timeout within ts-devices and ts-weather to five minutes (though this is arguably much higher than it likely needs to be).

**Comment by danmason** [comment]
Upon trying to run long-build, get an exit code 1 when it goes to run ts-devices. Not entirely sure as to why, currently.

Edit: Appears to be caused by the configuration options of the circleCI server, seems to work fine locally when using 8Gb of memory (set within crux-test's project.clj) but appears to fail with 3200Mb

**Comment by jarohen** [comment]
closed in favour of the new bench cards, #389
