### ISSUE TITLE
Production-ready default Kafka configurations

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#347]
E.g. default `:replication-factor` should probably be `3` for typical production usage here https://github.com/juxt/crux/blob/69b3078c5c2d0c28c45c6a53f7da7fbb34c26217/crux-core/src/crux/bootstrap.clj#L34 (or wherever this ends up after the config branch is merged https://github.com/juxt/crux/pull/340)

Additionally Confluent Cloud recommends 6 partitions by default, which seems like a sensible default for the document topic. See: https://github.com/juxt/crux/blob/ee310eb5cf153a8b4ad3d8c5764da7aa0bdc0669/docs/example/crux-cloud/README.adoc

There may also be other useful default config options of interest. Somewhat related is the ability to POST to remote Crux nodes for Kafka configuration rather having to think about making `.properties` files available.

**Comment by hraberg** [comment]
When making this change, sanity check that the tests and `dev.clj`, or rather, anything related to embedded kafka uses a replication factor of 1.

**Comment by jarohen** [comment]
we have these in Soak, let's ensure these are documented as part of #386
