### ISSUE TITLE
Google Firestore Crux Adapter

### ISSUE THREAD

**Issue by theronic** [xtdb/xtdb#349]
Are there any reasons why Google Firestore could not be used as a Crux persistence layer?

**Comment by refset** [comment]
Hi @theronic, assuming you are thinking of the logs specifically (and not the embedded KV indexes) - we don't see any particular limitations that would prevent this from working. Firestore seems to support the necessary transactional/ordering requirements to create a new `tx-log` implementation. Clearly there will be downsides in terms of storage costs and latency but availability seems to be taken care of quite well. Please let us know if there is a particular project you have in mind and we could potentially help you with designing and building such a Firestore backend.

**Comment by theronic** [comment]
What about the KV indexes?

In the past I've looked at building a Firebase adapter for Datascript. I would like to be able to use Google Cloud Functions + Firestore to get something like Crux.

**Comment by refset** [comment]
The design of our current query engine means that use of the local KV indexes is very "chatty". Therefore even a small amount of additional latency introduced by a networked KV round-trip could have a dramatic impact on average query execution time. For example, a typical non-trivial Datalog query could easily require many thousands of lookups and tens of seconds to complete. This may be acceptable if you don't have any need a for near real-time query responses.

> I would like to be able to use Google Cloud Functions + Firestore to get something like Crux

I would also very much like to see a multi-tenant Datalog DBaaS exist somehow :) Unfortunately I don't think it will be feasible to build a serious query engine directly on top of a FaaS platform in the near future...but let's continue this discussion on Slack or Zulip!

You are of course welcome to respond here further, though it will ultimately be more efficient to limit discussions in these GitHub issues to bugs and specific proposals.

**Comment by theronic** [comment]
Datomic caches batches of 10k+ datoms with shared locality and streams them to the peer. I don't see why this could not be implemented on a KV store that is billed by lookup.

(re: channels - given sufficient thought here, this could become a specific proposal.)

**Comment by jonpither** [comment]
Closing for now, may be revisited.
