### ISSUE TITLE
Edn Serialisation is Likely Broken

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#365]
See https://www.nitor.com/fi/uutiset-ja-blogi/pitfalls-and-bumps-clojures-extensible-data-notation-edn

Any places using `pr-str` in the code should be consolidated to use some helper in `crux.io` that deals with all this. The main culprits are the http-server and client. But also the Kafka EdnSerialiser or example.

Somewhat related to #151.

**Comment by refset** [comment]
This may also impact hashing (we also need to identify all the places where hashes are generated, using nippy, for future analysis).

**Comment by jarohen** [comment]
@hraberg I can't access that link - just me? if not, could you pop a rough outline of what's broken in the description?

**Comment by cddr** [comment]
Ah we made that mistake in jackdaw (https://github.com/FundingCircle/jackdaw/pull/190)

**Comment by hraberg** [comment]
The blog post above seems to have gone, but the points made seem to be the defaults anyway, so maybe this card isn't needed, as seen in the jackdaw commit above, they did remove the explicit bindings in their `edn2` serde. Relevant bindings are:

* `*print-length*` defaults to `nil`  but `100` in CIDER.
* `*print-level*` defaults to `nil`
* `*print-namespace-maps*` defaults to `false` but `true` in the REPL.

The jackdaw point about not emitting newline is also worth reflecting on, but think we use `pr-str` in all relevant cases, though would be worth sanity checking while bringing in a consistent helper function.

So raising this card might been false alarm after all. But this can easily be confusing if not handled in a consistent way.

**Comment by hraberg** [comment]
As the original post seems to have disappeared, here's a discussion around it:
https://www.reddit.com/r/Clojure/comments/d967fd/pitfalls_and_bumps_in_clojures_extensible_data/

**Comment by danmason** [comment]
Found a (non broken) link to the article: https://www.nitor.com/en/news-and-blogs/pitfalls-and-bumps-clojures-extensible-data-notation-edn
