### ISSUE TITLE
`(crux/entity db :some/fancy-id)` throws NullPointerException if entity was inserted after db snapshot

### ISSUE THREAD

**Issue by theronic** [xtdb/xtdb#367]
Attempting to fetch an entity from a prior snapshot of a DB throws a NullPointerException instead of returning nil if you inserted the entity after constructing the snapsphot.

To reproduce:

```
(def my-node
  (crux/start-node
    {:crux.node/topology            :crux.standalone/topology
     :crux.node/kv-store            "crux.kv.memdb/kv" ; see docs for LMDB/RocksDB storage options
     :crux.standalone/event-log-dir "data/event-log-dir-1"
     :crux.kv/db-dir                "data/db-dir-1"}))

(def my-document
    {:crux.db/id    :some/fancy-id
     :arbitrary-key ["an untyped value" 123]
     :nested-map    {"and values" :can-be-arbitrarily-nested}})

(def my-db (crux/db my-node)) ;; should be empty
(crux/entity my-db :some/fancy-id)
=> nil
(crux/submit-tx my-node [[:crux.tx/put my-document]])
(crux/entity my-db :some/fancy-id) ;; note my-db is a snapshot from the past.
=> Execution error (NullPointerException) at crux.codec/date->reverse-time-ms (codec.clj:536).
```

I haven't delved into any internals, but I imagine this could be caused by the keyspace for entity IDs not being versioned, even if the document contents are.

**Comment by jonpither** [comment]
Thanks for this bug report @theronic - have reproduced.

**Comment by jarohen** [comment]
thoughts from pairing so far - this looks like the empty db (one without a valid-time/transact-time yet) is a necessary condition to repro - in theory (haven't tried it) this should be fine for databases with _any_ other transactions already indexed.

the hunt continues...
