### ISSUE TITLE
Failed CAS operations can leave unevictable documents

### ISSUE THREAD

**Issue by psagers** [xtdb/xtdb#371]
Execute the following sequence on a clean instance (I'm running from source, revision 8ed4cf4aacc5f478644f21ed694706640b54e8c1):

```clojure
(crux/submit-tx node [[:crux.tx/put {:crux.db/id :doc-a, :value 0}]])
(crux/submit-tx node [[:crux.tx/cas {:crux.db/id :doc-a, :value 1}, {:crux.db/id :doc-a, :value 2}]])
(crux/submit-tx node [[:crux.tx/put {:crux.db/id :doc-a, :value 3}]])
(crux/submit-tx node [[:crux.tx/evict :doc-a]])
```

Now inspect your document log (I use the JDBC backend for easy access). The first and last revisions of `:doc-a` will have been replaced by tombstones. The two that were part of the CAS operation never got indexed, so they're still in there.

Half of the problem could perhaps be solved by not fully ingesting the first argument to CAS: we only ever care about the id and if it's not already in the log, the operation can't possibly succeed anyway.

The second argument seems like a much deeper problem, at least assuming that it's a design rather than implementation issue. I can speculate on two high-level approaches off the top of my head.

1. Somehow allow the eviction process to find all proposed revisions to a document, regardless of whether they were ultimately accepted and indexed.
2. Have some other garbage-collection-like mechanism to identify orphaned documents in the document log and redact them proactively.

**Comment by refset** [comment]
Hi @psagers - thank you for opening this issue. It looks like a sharp edge in the eviction design to me. We will have a think and report back soon!

**Comment by psagers** [comment]
Here's another scenario. Hard to tell if it's distinct enough to deserve its own issue, so I'll just document it here:

```clojure
(crux/submit-tx node [[:crux.tx/put {:crux.db/id :doc-a, :value 0}]
                      [:crux.tx/put {:crux.db/id :doc-a, :value 1}]])
(crux/submit-tx node [[:crux.tx/evict :doc-a]])
```

The first document will not be evicted in this case.

**Comment by hraberg** [comment]
Current plan is to solve this together with #375 by removing date ranges for eviction for now.

This feature was added without properly analyse all the consequences, and with the aim that eviction could also be reused as a way to compact data. But due to risk of creating either documents which cannot be evicted (this issue), or evicting unexpected documents (#375), we're taking a conservative step back for now and to simply evict an entity's entire history in one go. 

Similar to other patterns in Crux, if one needs finer granularity, one can split out the entities into smaller ones for now.

We might revisit this in the future, likely after 1.0.

**Comment by hraberg** [comment]
It's worth noting that we have ways of finding the documents related to the failed CAS operations by their entity id internally by bypassing the temporal indexes, so the new approach will use this to determine which versions of an entity does exist, not the higher level APIs.

**Comment by hraberg** [comment]
The approach above will also allow us to find documents that were overwritten in the same transaction.

**Comment by hraberg** [comment]
To be more explicit, the way to find the orphaned content hashes is to use`idx/all-keys-in-prefix` over a `c/encode-attribute+entity+content-hash+value-key-to` prefix where attribute is `crux.db/id` and content hash and value aren't set. Then to use `c/decode-attribute+entity+content-hash+value-key->entity+value+content-hash-from` to grab the content hashes. See other usages (like `idx/entity-history`) for example usage.
