### ISSUE TITLE
Allow clojure.lang.Cons as a predicate

### ISSUE THREAD

**Issue by AdamNiederer** [xtdb/xtdb#377]
Hey, thanks for releasing such an awesome database! 

I noticed that this query

```clojure
{:find ['e] 
 :where [['e :name 'n]
         [(cons '= '(n "hi"))]]}
```

will fail `:crux.query/query`, because the predicate on the last line is a `clojure.lang.Cons`, which isn't a list
```
1. Unhandled clojure.lang.ExceptionInfo
   Spec assertion failed.

         Spec: :crux.query/query
        Value: {:find [e], :where [[e :name n] [(= n "hi")]]}

     Problems:  [...snip...]

            val: (= n "hi")
             in: [:where 1 0]
         failed: list?
           spec: :crux.query/pred
             at: [:where :pred :pred]
```

```clojure
user> (list? (cons '= '(n "hi")))
false
```

This may be confusing to users who are programmatically constructing queries, because Conses are relatively transparent to Clojure users, and have the same textual representation as lists and seqs in the repl - for example:

```clojure
user> (= (cons '= '(n "hi")) (list '= 'n "hi"))
true
user> (= (pr-str (cons '= '(n "hi"))) (pr-str (list '= 'n "hi")))
true
user> (= (class (cons '= '(n "hi"))) (class (list '= 'n "hi")))
false
```

Would allowing conses where-ever lists are allowed be possible? It's technically not the fault of Crux, but it may remove a stumbling block for users who want to compile things to datalog.

Thanks!

**Comment by danmason** [comment]
Hello there, thank you and good find! 

I relaxed the spec for predicates in queries somewhat to allow the use of **cons** in queries.
