### ISSUE TITLE
Users can monitor a production Crux deployment

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#384]
When something isn't quite right in production, we want to give users the tools to diagnose and fix the issue. Problems that we'd like to be able to diagnose include:
* Why are my queries running slowly?
  * Many queries at the same time? One slow query clogging things up? (#493, #494, #516)
  * CPU/RAM/Disk usage? CPU/RAM through normal node monitoring (#499), but Crux can also expose the disk space it's using: (#492)
  * Out of scope (OoS) for us:
    * Other processes on the machine?
    * Remote Crux - something in the middle could be slowing things down? 
* Why is this specific query slow?
  We can look into providing dev tools for this. OoS for this project, but something we are looking in to (#504, amongst others)
* Why is ingest hanging/not as fast as I expect? (#495)
* Other metrics from RocksDB/LMDB (#496, #497)

Reqmts:
* Deployed to the Crux dev environment (#397)

Some possible ideas for solutions:
* Dashboards - maybe AWS CloudWatch?
* Prometheus, Grafana, ELK, CodeHale, loads of others

**Comment by t-taylor** [comment]
## Possible so far
* Linux gives us:
  * `ps -p [pid] -o %cpu,%mem,bsdtime,cmd`
  * all other system wide stuff e.g. disk space, network traffic...
* JVM monitoring gives us:
  * Thread monitoring
  * Heap usage/size
  * CPU usage
  * Profiling

## Possibilities

* Ingestion rate
* query response time
* Store size

### Monitoring libs

* [jmx](https://github.com/clojure/java.jmx)
* [Prometheus](https://github.com/clj-commons/iapetos)

**Comment by t-taylor** [comment]
I believe the first step in this issue is to add some endpoints to start seeing what a fully fledged metric system could look like.
I propose for a first pass of this epic to produce some sort of ingestion rate/quantity and query response time.

**Comment by adamfeldman** [comment]
On the Crux REST API, currently [`GET /`](https://www.opencrux.com/docs#rest-home) returns healthcheck info, as EDN. 

- As far as discoverability for users goes, perhaps `/health` could be added as well, with the same data as `/`
  - Note: [`/health` is not an official standard AFAICT, just a common convention](https://tools.ietf.org/id/draft-inadarei-api-health-check-01.html#creating-and-serving-health-responses).
- As most other tools in the observability ecosystem don't speak EDN, it may be useful to support JSON as an additional content-type for the returned data (e.g. [`/health+json`](https://tools.ietf.org/id/draft-inadarei-api-health-check-01.html#example-output))

Please let me know if this is best moved to a separate issue.

**Comment by jarohen** [comment]
thanks @adamfeldman - yes, we're currently looking at a number of things to make Crux more monitorable - will add a link to your comment from the relative card.

re the `+json` part - we'll likely use `Accept` headers for this, rather than a change in URL? (although yes, defaulting to JSON seems sensible)
