### ISSUE TITLE
We've got the existing Console work into a releasable state

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#390]

**Comment by jonpither** [comment]
I propose the following:

1) The query console is simple - just a box to enter queries in on the left, and EDN results are displayed on the right. We retire or move out the way the 'sample snippets'. A stretch goal here, is some useful auto-complete (the core query language, i.e. `where` and `find`).

2) We have a document navigation tool - a page show documents in the database, and a click through tool to:

3) Entity page - show the version of an entity for bitemporal coordinates and be able to navigate versions of the given entity in bitemporal space (@hraberg previously created a selectable tool/graph for this). You should also be to navigate 'click through' to other documents.

In the above, 2) is arguably a nice-to-have, if you can click through from documents within search results to get to 3), so a little reflection required, and investigation into if Crux could support such a page, to list out all entities at scale.

I'd like keep in sync with the styling done thus far. 

Some guiding principles:

1) The console should perform as the volume of of data within a Crux node and the complexity of the queries grow. We want the basics right and we want it to be robust.

2) We shouldn't use internal Crux functions, or base the console functionality on any Crux functionality that isn't officially supported.
