### ISSUE TITLE
We've created a large example 'soak data' cluster that we can use to test performance, migrations and operations on an ongoing basis

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#397]
We'd like a example of how to deploy Crux to production as an example in the repo. (`examples/...`, bonus points for a good project name!)

* Should fetch data from a free, open, ongoing data source - examples could be daily financial market data (or something more interesting if you can find it :smile:)
* Deployed to AWS, repeatable deploy using CloudFormation, metrics in CloudWatch.
* Multiple Kafka nodes (separate to Crux), preferably across availability zones (AZs). Data preserved across node restarts and backed up appropriately. (the closer this is to a 'standard' cloud Kafka deploy, the better)
* Multiple Crux nodes, preferably across AZs. Data on Crux nodes should be persistent, preserved both between node restarts and over Crux version upgrades.
* Small load-balanced HTTP service to present the data in a web-page (doesn't need to be massively dynamic, just enough to present it - doubt it needs a CLJS pipeline, even - think 90s web design)
* No secrets committed into Git! :speak_no_evil: 
* Opportunities for blogs galore, no doubt.

**Comment by jarohen** [comment]
@jonpither you ok to pop a few details on here about what you're looking to achieve with this one?

**Comment by jonpither** [comment]
The idea here is that we have a Crux cluster deployed that is 'always on', always some data being ingested - and has large volumes. We can use it to QA metrics provisioning, query-speed, our deployment capability, the Console, and of course, performance.

This would not be a controlled, clinical benchmark setting. It's would be a useful go-to place to test out various aspects of Crux, and also for demonstration purposes to show volume.

**Comment by jarohen** [comment]
backup/restore, infrastructure-as-code, testing deploying a cloud topology, gateway to a benchmarking environment
