### ISSUE TITLE
We've clarified the behaviour of `db/sync`

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#409]
The two arities of `db/sync` are causing confusion. We either need to:
* Make the API more intuitive
* Document up why it's like this, and how to use it

**Comment by refset** [comment]
For context, this was the last change we made in this area:
https://github.com/juxt/crux/issues/254

...it was subsequently pointed out (via Zulip) that this change "does however leave the question as to what the defined behavior is when you supply a tx-time not yet seen"

**Comment by jarohen** [comment]
killed in favour of #466
