### ISSUE TITLE
Devs can get insight into how queries execute

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#414]

**Comment by jonpither** [comment]
For now this is envisioned as a REPL tool, but the groundwork should allow us to consider a user facing visualization tool for the Console (which would be a new card/issue).

**Comment by jonpither** [comment]
![screen](https://user-images.githubusercontent.com/143601/68955438-ecb94680-07bd-11ea-8abd-a4b9d89b0862.png)
 
Example output

**Comment by jonpither** [comment]
This has been merged in #416
