### ISSUE TITLE
query order-by doesn't order unless sort variable returned

### ISSUE THREAD

**Issue by t-taylor** [xtdb/xtdb#418]
See test on branch/commit [here](https://github.com/juxt/crux/commit/1e20f8c280160ecb856d7036b45afa54b3794dee).
When `:order-by` is used in `crux.api/q` and the variable on which the sort is decided by is not returned in `:find`, the results returned are not ordered but still in a vector.

**Comment by jonpither** [comment]
Let's throw an explicit IllegalArgumentException so the user can add it to the where clause

**Comment by t-taylor** [comment]
See https://github.com/juxt/crux/pull/420
