### ISSUE TITLE
Link to CLA broken?

### ISSUE THREAD

**Issue by mdiin** [xtdb/xtdb#423]
The link to the CLA is broken on the documentation site: https://opencrux.com/docs#about-contributing

It points to https://opencrux.com/open-crux-individual-contributor-license-agreement-cla.odt, which does not exist. Maybe this is just a case of the documentation site being very new, in which case you can simply disregard this issue. :-)

**Comment by jarohen** [comment]
Cheers @mdiin - you're right, it's very new, but we'll get on it :)
