### ISSUE TITLE
Calling functions on closed ICruxSystems in the Java API crashes JRE

### ISSUE THREAD

**Issue by danmason** [xtdb/xtdb#424]
Calling any functions on a closed ICruxSystem causes a segmentation fault, in a similar manner to #368 

I've created a crashing test which shows this behavior, [here](https://github.com/juxt/crux/commit/100978544ac2b2d3a02d61d205d5c640c577eb18).

**Comment by jarohen** [comment]
see #368, perhaps? @jonpither

**Comment by jarohen** [comment]
yep, local code caching issue, clean/build/test worked fine
