### ISSUE TITLE
Users can use all features of the old Java API from the new Java API

### ISSUE THREAD

**Issue by danmason** [xtdb/xtdb#435]
Within the next vertical slice of the API, I wish to cover the contents of [**ICruxDatasource**](https://github.com/juxt/crux/blob/master/crux-core/src/crux/api/ICruxDatasource.java) and [**ICruxAPI**](https://github.com/juxt/crux/blob/master/crux-core/src/crux/api/ICruxAPI.java) in particular.

**Comment by jarohen** [comment]
killing, we'll be migrating crux.api.alpha into crux.api
