### ISSUE TITLE
Users can query via the Java API using strongly-typed objects

### ISSUE THREAD

**Issue by danmason** [xtdb/xtdb#437]
Currently, queries are constructed using a mix of typed clauses and strings, ie:
``` java
Query.find("[e]")
     .where("[[e :crux.db/id _]]")
     .fullResults(true)
...
```

For each of the clauses which take a sequence/vector (**find**, **where**, **args**, **rules** and **order-by**), I would like to add strong typing to their terms (see [query.clj](https://github.com/juxt/crux/blob/master/crux-core/src/crux/query.clj)) rather than only taking and parsing strings.

**Comment by arichiardi** [comment]
Hi there, not a Java dev here but subscribing to this.

My 2c is that in terms of requirements most of Java folks would love to statically type check their queries either a-la [JOOQ](http://www.jooq.org/) or with [MyBatis annotations](https://mybatis.org/mybatis-3/java-api.html).

**Comment by jonpither** [comment]
Relates to #413
