### ISSUE TITLE
The 'sync' API is clarified, with differently-named functions for the different use cases

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#442]
Currently, the 'sync' API has several overloads, which are used for several quite distinct use cases, with a few different blocking behaviours. We should consider splitting these into differently-named functions.

**Comment by refset** [comment]
A related consideration is whether to restore the previous blocking behaviour for `db` (instead of always having to use `sync` as well to read-your-writes).

**Comment by jarohen** [comment]
I've inadvertently started work on this as part of #441, adding an `await-tx` function. given that's a much bigger chunk of work, and given I'd like to get that PR in, I'll create a separate branch for that (with this issue number) on my fork

**Comment by jarohen** [comment]
Closing in favour of #466
