### ISSUE TITLE
Query with multiple join conditions between the same entities shouldn't time out

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#443]
Needs further clarification (raised on a call), but it seems like when you join between two entities on more than one field, the query can time out.

I'm assuming it's something like this:
```clojure
{:find [...]
 :where '[[e1 :e1/foo foo]
          [e1 :e1/bar bar]
          [e2 :e2/foo foo]
          [e2 :e2/bar bar]
          [(!= e1 e2)]]}
```

**Comment by jonpither** [comment]
Self-assigning for some initial investigation

**Comment by jarohen** [comment]
have a repro for this on my branch now.

`:vars-in-join-order [e1 x y e2]`

looking at how Postgres deals with this kind of query, for comparison:

```
                Table "public.foo"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 id     | integer |           | not null | 
 x      | integer |           | not null | 
 y      | integer |           | not null | 
Indexes:
    "foo_pkey" PRIMARY KEY, btree (id)
```

```
INSERT INTO foo SELECT x * 1000 + y, x, y FROM 
generate_series(1,50) x (x), generate_series(1,1000) y (y);
INSERT INTO foo VALUES (-10, 4, 8);
```

```
SELECT * FROM foo f1 JOIN foo f2 ON (f1.x = f2.x and f1.y = f2.y) WHERE f1.id <> f2.id;

  id  | x | y |  id  | x | y 
------+---+---+------+---+---
 4008 | 4 | 8 |  -10 | 4 | 8
  -10 | 4 | 8 | 4008 | 4 | 8
```

```
explain analyse ...                                                       QUERY PLAN------------------------------------------------------------------------------------------------------------------------
 Merge Join  (cost=9347.01..10723.04 rows=50050 width=24) (actual time=87.499..101.645 rows=2 loops=1)
   Merge Cond: ((f1.x = f2.x) AND (f1.y = f2.y))
   Join Filter: (f1.id <> f2.id)
   Rows Removed by Join Filter: 50001
   ->  Sort  (cost=4673.51..4798.51 rows=50001 width=12) (actual time=63.041..64.740 rows=50001 loops=1)
         Sort Key: f1.x, f1.y
         Sort Method: quicksort  Memory: 3710kB
         ->  Seq Scan on foo f1  (cost=0.00..771.01 rows=50001 width=12) (actual time=0.028..13.258 rows=50001 loops=1)
   ->  Sort  (cost=4673.51..4798.51 rows=50001 width=12) (actual time=23.578..25.256 rows=50003 loops=1)
         Sort Key: f2.x, f2.y
         Sort Method: quicksort  Memory: 3710kB
         ->  Seq Scan on foo f2  (cost=0.00..771.01 rows=50001 width=12) (actual time=0.015..2.895 rows=50001 loops=1) Planning Time: 0.377 ms
 Execution Time: 102.130 ms
```

so self join, sorts the relation, then merge joins. seems sensible.

what (I think) Crux is doing - we're choosing e1, x and y first, then scanning through e2 to find a doc that both matches x and y, and also `(not= e1 e2)` - so a nested loop join, as postgres would call it. the Crux join is 4 levels deep - one for each bound var.

in Crux, to follow a similar pattern, we'd have to set up two two-col indices, then use our usual join but over only two levels. would require a change to the query engine (planner) to realise that we were joining on more than one attribute (which I think might be a more general case of the way the planner works atm? although I'm not 100% familiar with it yet)

**Comment by jarohen** [comment]
@hraberg and I spent most of the afternoon on this one, concluded there's not much Crux can do about this one without significant changes to the query engine.

There are 8 relations at play here (with cardinalities assuming x in 0..5 and y in 0..10):
```
;; 1. aev-e e1 50
;; 2. aev-v x  1
;; 3. aev-e e1 50
;; 4. aev-v y  1

;; 5. ave-v x  1
;; 6. ave-e e2 10
;; 7. ave-v y  1
;; 8. ave-e e2 5
```

which leads to the following join layers:
```
;; JL1 (e1): #{1 3} 50 (scan)
;; JL2 (x):  #{2 5} 1
;; JL3 (y):  #{4 7} 1
;; JL4 (e2): #{6 8} relations have 10/5 elements respectively, yields 1 tuple
```

with a complexity of `O(xy^2)`, which is what's causing the slowness in larger databases.

It's not pretty, but the short-term solution to this would be to split `x` and `y` out as composite keys - either as additional map values within these documents, or separate documents - leaving a more respectable join-order of `xy e1 e2`.
