### ISSUE TITLE
We've published and documented an end-to-end Crux/GraphIQL example

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#447]
* User should be able to run `docker-compose up -d` and get a GraphIQL webserver running on http://localhost:3000 (i.e. delete the haproxy stuff), serving the Star Trek data set
* Shouldn't contain any data that isn't publicly releasable
* A blog running the user through what's possible, and an overview of how they might be able to write their own GraphQL service over a Crux node (how to write the resolvers, etc)

Eventually we might release the GraphQL-to-Crux-adapter as a general library, but let's assume the user can manually write resolvers for the time being.

**Comment by coconutpalm** [comment]
Status on this work?  (Thanks in advance.)

**Comment by armincerf** [comment]
> Status on this work? (Thanks in advance.)

Have a look at Site https://github.com/juxt/site

Still a work in progress, currently it works well if you don't have many authz requirements and is in use in production, but there is a big piece of ongoing work in the 'actions' branch which adds comprehensive authn/authz abilities

There's also a juxt-site channel here https://clojurians.slack.com/archives/C02RDUVDEP2

**Comment by jarohen** [comment]
I'll close this in the XT repo, given this is pretty much what Site's for now - it didn't exist when I wrote this :smile:

**Comment by coconutpalm** [comment]
Thanks!
