### ISSUE TITLE
Retention Mechanisms

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#46]
We want to explore various retention mechanisms. For the docs this can be done similar to eviction #32, having the query node decide which versions of an entity to delete. For TTL it's for example all versions of an entity older than a specific time (compared to transaction time) for example.

Unlike eviction, retention is likely done by logic on the query node.
There are more advanced versions where you keep data for say every day or month.

**Comment by megakorre** [comment]
not planned for phase 2
