### ISSUE TITLE
Users can await a tx using the map returned from submit-tx

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#466]
* [x] Update `sync` zero-arg to sync to the latest transaction as of the function call (i.e. not chasing the producer)
* [x] Added 'await-tx' function on node, takes a transaction map and an optional timeout. 
* [x] Added 'await-tx-time' function on node, same as current `sync` to tx-time arity, deprecate `sync` arity
* [x] Updated tests to use new functions
* [x] Updated crux docs

**Comment by alexanderkiel** [comment]
What would `await-tx` return? Could it return the outcome of the transaction we wait for? Or how do I test wether a transaction I just submitted was successful?

**Comment by refset** [comment]
Hi @alexanderkiel the main purpose of `await-tx` will be to block the thread while ingestion takes place (essentially like `sync` currently does), and it will probably at least return the same map of `tx-time` and `tx-id` that was passed in. Returning the outcome of the transaction as well (i.e. `success`/`fail`) seems like a reasonable suggestion to me at least - thanks for chiming in!

> how do I test whether a transaction I just submitted was successful?

You can achieve this currently (though perhaps not as elegantly) using either `submitted-tx-updated-entity?` or `submitted-tx-corrected-entity?`: https://www.opencrux.com/docs#_submitted_tx_updated_entity

**Comment by alexanderkiel** [comment]
Hi @refset. Thanks for pointing to `submitted-tx-updated-entity?`. In case the only way a transaction can fail is through `:crux.tx/cas` as it is currently in my understanding, using `submitted-tx-updated-entity?` on every CAS op should give me the information I need.

If you consider to implement a one-shot transaction failure detection, you have to also provide the reason for the failure. Here that would be the CAS op that failed. From looking at the code, I don't see that you have this information stored explicitly. So it might be actually favorable to have to test for each CAS update.

But still, given that a transaction can either fail or succeed, to me it feels a bit strange, that I can't simply ask Crux for this information.

**Comment by refset** [comment]
> the only way a transaction can fail is through `:crux.tx/cas`

That's correct as things stand today (ignoring transaction functions, which are experimental and hence undocumented).

> given that a transaction can either fail or succeed, to me it feels a bit strange, that I can't simply ask Crux for this information

I'm not 100% certain, but I think the simple answer is that Crux doesn't currently store any reified data about individual transactions in the indexes (at the nodes). Storing additional transaction information is certainly plausible but would it would also further bloat storage requirements. I agree we should make the UX more convenient in any case :)

**Comment by danmason** [comment]
Note on `remote-api-client` / `http-server`: Both of these still use 'sync' (though `http-server` does call down to **await-tx-time**, if a transaction time is provided). Should probably also include **await-tx** and **await-tx-time** in both of these, and update the REST api docs thereafter.
