### ISSUE TITLE
standalone demo from readme errors trying to resolve rocksdb

### ISSUE THREAD

**Issue by joinr** [xtdb/xtdb#482]
Given:
```
(def my-node
  (crux/start-node
   {:crux.node/topology :crux.standalone/topology
    ;; see docs for LMDB/RocksDB storage options
    :crux.node/kv-store "crux.kv.memdb/kv"
    :crux.standalone/event-log-dir "data/event-log-dir-1"
    :crux.kv/db-dir "data/db-dir-1"}))
```
I get an error:
```
Execution error (FileNotFoundException) at crux.node/resolve-topology-id (node.clj:155).
Could not locate crux/kv/rocksdb__init.class, crux/kv/rocksdb.clj or crux/kv/rocksdb.cljc on classpath.
```
due to crux trying to resolve a default option somewhere to use rocksdb (which I don't have the per the readme, just crux.core).

Further investigation led me to find things bombing at crux.standalone/event-log-kv-store, 
and that crux.standalone/event-log-kv-store  has [rocksdb as a default](https://github.com/juxt/crux/blob/master/crux-core/src/crux/standalone.clj#L52) which explains the failing resolve.

So I submitted a value:

```
(def my-node
  (crux/start-node
   {:crux.node/topology :crux.standalone/topology
    ;; see docs for LMDB/RocksDB storage options
    :crux.node/kv-store "crux.kv.memdb/kv"
    :crux.standalone/event-log-dir "data/event-log-dir-1"
    :crux.standalone/event-log-kv-store "crux.kv.memdb/kv"
    :crux.kv/db-dir "data/db-dir-1"}))
```

And can now at least load the node without error.  No idea if this is correct though.

**Comment by danmason** [comment]
Hello there,

What you did here was correct, yes. The README is somewhat behind the configuration docs ([here](https://opencrux.com/docs#config-standalone)) and this needs bringing up to date. Thanks for the find!
