### ISSUE TITLE
Query engine should perform more consistently for simple range queries

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#505]
The query engine should give more consistent performance when performing simple seeks, and ideally the first value returned by the query should align with the range (i.e. to be able to use `:limit 1` without having to use `:order-by` which materializes the entire set of results)

```
(for [i (range 5000)]
  (c/submit-tx node [[:crux.tx/put {:crux.db/id (java.util.UUID/randomUUID) :offer i}]]))


{:find [i],
 :where [[_ :offer i] [(test-pred i j)]],
 :args [{j test-val}],
 :limit 1}


[= 2]
#{[2]} ; slow

[< 10]
#{[9]} ; slow


[< 9223372036854775807]
#{[2690]} ; fast

[< -100]
#{} ; slow

[> -100]
#{[2690]} ; fast
```

**Comment by hraberg** [comment]
This is related to #348 as if even if one is using this as documented above, there's no guarantee that Crux picks a useful join order based on the range constraints present in the query.

**Comment by refset** [comment]
To summarise:

1. my test logic mistakenly used `:args`, which meant the range predicates didn't get recognised as range predicates - see the note in the committed test (also this needs documenting)
2. `<` range predicates never use reverse prefix seek iteration, which means you can't rely on them when using `limit` -- therefore you can either reverse your values before submitting it (i.e. `(- 0 i)`), or even store your data in both forwards AND reverse directions, so that it can be efficiently queried using `limit`. This is useful for pagination but is still not necessarily a complete pagination solution. See also https://github.com/xtdb/xtdb/discussions/1514#discussioncomment-758943
3. as things stand you should aim to stream range scans in and out of independent queries if you really need to guarantee efficient order/limit behaviours, rather than relying on the Datalog picking optimal sorted indexes (the Crux query engine has been designed around optimal joins, not sorting)

The main reason for 2) is that iterating in reverse order with prefix seeks has more limited (/inefficient) support within RocksDB:
https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes#limitation
https://github.com/facebook/rocksdb/wiki/SeekForPrev
https://groups.google.com/g/rocksdb/c/Gq7b99-9Iq4

...however it seems LMDB can do this efficiently:
https://www.openldap.org/lists/openldap-technical/201502/msg00149.html
