### ISSUE TITLE
Users can query Crux using SQL

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#514]
See PR #735 for more discussion.

(from @malcolmsparks on Slack)
SQL has now become a protocol to allow the integration of a vast ecosystem of tools for:

- Reporting, management information (MIS)
- Business Intelligence (BI)
- Dashboards
- Data extract-transform-load (ETL)
- Systems integration

There are some SQL standards defined by ANSI, such as SQL-92, SQL:2003, SQL:2011. Historically, the conformance of SQL implementations vary so much that the common denominator is quite small. Therefore, the most rudimentary implementation of SQL can yield interoperability with a significant fraction of the industry toolset.

We'd likely want to allow users to:
* transact a fixed relation (a 'table', in SQL)
* query these fixed relations from Crux using a SQL (or subset thereof) query

**Comment by jarohen** [comment]
Cassandra/Calcite docs (thanks @refset)
* https://calcite.apache.org/docs/cassandra_adapter.html
* https://github.com/apache/calcite/tree/master/cassandra/src/main/java/org/apache/calcite/adapter/cassandra

**Comment by jonpither** [comment]
See also for an initial Crux/Calcite spike: https://github.com/juxt/edge/tree/calcite

**Comment by jarohen** [comment]
Things to think about:
* What do we expose over the network?
* Schema generation? Can it be dynamic?
* Taking control of joins
* Bitemp SQL - 'as-of?'
* Prior art (Cassandra?)
* Evaluate Presto vs Calcite
* DML/DDL

**Comment by jonpither** [comment]
From @SevereOverfl0w:

https://prestodb.io/docs/current/connector/mongodb.html#table-definition-label seems worth evaluating.

In particular: "MongoDB [connector plugin] maintains table definitions on the special collection where mongodb.schema-collection configuration value specifies."

That is, they store table definitions in MongoDB.

**Comment by jonpither** [comment]
Fixed by #735
