### ISSUE TITLE
Sync/await-tx then query over HTTP won't necessary hit the same node

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#527]
If the Crux HTTP cluster is load-balanced, the sync/await (see #466) HTTP request will hit one node, wait for that node to become up-to-date, then the subsequent query HTTP request may hit a different node.

Let's say a user gets a `db` instance and then makes multiple calls (queries, history reqs, etc).

With the remote HTTP client, we aim that the API and behaviour (network instability aside) is as similar as possible to a local node. With a local node, users `await-tx` once, supplying a timeout - after waiting, they get a `db` instance and then make their calls. They know that once the `await-tx` returns, they're free to make whatever queries they like, without needing to wait again for the indexing to catch up.

With a remote node, though, if each of the subsequent requests hits a different node, they'll either have to accept the request failing, or await the transaction again, _for each request_ - i.e. the waiting has to be done on the individual request, rather than a single `await-tx` call. (This could be mitigated by things like session stickiness, but that's on the user to set up.)

Currently, if the `await-tx` call goes to one node, and a subsequent request goes to a node without that transaction indexed, the request will fail with a `NodeOutOfSyncException`.

Options:
1. We preserve this behaviour, bad luck.
2. We could remove sync/await-tx and friends, instead having this specified as part of the `db` call. For a remote connection, we could then opt to await for the specified timeout on _each_ call (which would still be subject to the errors above, but possibly less likely? possibly less predictable, too).
3. In addition to (2), to match the local behaviour as much as possible, we could experiment with something akin to a long-lived connection while the DB's open - i.e. encouraging using `open-db` rather than `db` for remote connections. Ironically, this would mean preserving await-tx on the HTTP API, so that the `db` call can await the transaction when it opens the connection.

**Comment by refset** [comment]
My summary from the duplicate issue (now deleted - #615) :

> An await-tx combined with a non-sticky HTTP load-balancing doesn't make any guarantees that a subsequent query will be calculated against the awaited tx. This requires the user's client code to detect the synchronisation issue and retry the query.

Possible solutions:
* Add an await parameter to all read interfaces over HTTP (same as the proposal above)
* Allow the user to await a tx high-watermark maintained somewhere outside the Crux database

Related reading about read consistency, isolation levels, and "Online Event Processing": https://queue.acm.org/detail.cfm?id=3321612

> if a client reads from two different data stores that are updated by two different consumers or log partitions, then the values read by the client may be inconsistent with each other. For example, reading the source and destination accounts of a payment may return the source account after the payment has been processed, but the destination account before it has been processed. Thus, even though the accounts will eventually converge toward a consistent state, they may be inconsistent when read at one particular point in time.
> 
> Note that in an ACID context, preventing this anomaly falls under the heading of isolation, not atomicity; a system with atomicity alone does not guarantee that two accounts will be read in a consistent state. A database transaction running at "read committed" isolation level—the default isolation level in many systems including PostgreSQL, Oracle DB, and SQL Server—may experience the same anomaly when reading from two accounts.3 Preventing this anomaly requires a stronger isolation level: "repeatable read," snapshot isolation, or serializability.
> 
> At present, the OLEP approach does not provide isolation for read requests that are sent directly to data stores (rather than being serialized through the log). Hopefully, future research will enable stronger isolation levels such as snapshot isolation across data stores that are updated from a log.

EDIT: sticky sessions is the other approach, related discussion https://github.com/juxt/crux/issues/87

**Comment by jarohen** [comment]
blocked on #410 for now, the HTTP endpoints will use the same structure as the Clojure API

**Comment by jarohen** [comment]
Assuming two main use cases:

* I want to submit a transaction and then read the state of the world after that transaction's committed
* For audit, I want to run a query at a tx-time I've used previously, and I want to make sure the node I'm hitting has that transaction.

Assuming also that the first is more common than the second, we could consider adding a run-after query to the `submit-tx` endpoint to handle that case - the behaviour would be the same as a submit-tx, await-tx, then query.

**Comment by jonpither** [comment]
As discussed I favour 2, so that normal db/q calls are consistent with each other, and you're not at risk of hitting an intermittent exception. 

3 is a further optimisation, so that you don't have to suffer subsequent nodes having to catch-up. If the cluster is in a good shape, the optimisation shouldn't be needed, if the cluster is in a bad shape... there's other problems to worry about (that ideally the load-balancer would've taken of)

**Comment by jonpither** [comment]
There's an orthogonal (arguably) card lurking, about making `db` block as it used to, once upon a time in Crux. This would have the benefit of potentially allowing us to remove await-tx from the external API.

As @jarohen mentions, there's some devil in the detail in this card about managing timeout config/options.
