### ISSUE TITLE
Running the ts-devices benchmark on ECS

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#541]
* [x] Script to download the dataset for local development (dataset gitignored)
* [x] Adding the ts-devices dataset to the Docker image created in #539 
* [x] Moving the ts-devices code to the crux-bench module
* [x] Running the benchmark directly, creating a Crux node from `-main` (i.e. not depending on clojure.test fixtures, nor the env var flag)
  * use embedded Kafka + RocksDB for now
* [x] After ingest, output a log message, containing:
  * `:crux.bench/bench-type :crux.bench.ts-devices/ingest`
  * how many documents/transactions we ingested
  * how long ingest+sync took
  * KV store size
  * was it successful? (separate `log/error` for any exceptions)
* [x] For each query, output a log message:
  * `:crux.bench/bench-type :crux.bench.ts-devices/<sensible-query-id>`
  * how long it took
  * any errors?
  * were the results correct?
- [x] Test on ECS with a number of different CPU/Memory values, figure out most cost effective option

**Comment by danmason** [comment]
- [ ] Test on ECS with a number of different CPU/Memory values, figure out most cost effective option
