### ISSUE TITLE
Decide default topologies & whether users should depend on crux-core

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#558]
1. There's an open question about whether a user should be encouraged to depend on `crux-core` for anything other than prototyping. If a user does depend on `crux-core`, can we assume they want an in-memory topology?
2. To help promote a new default standalone topology we might want to create a dedicated module (e.g. `crux-standalone`) that can be depended on by itself - should it bring in `crux-rocksdb` and `crux-jdbc (+H2)` by default, instead of using moberg?

This is somewhat prompted by PR #523 (which is proposing changes that arguably might not need to exist).

Related (might deserve independent issues):
- H2 would be preferred to SQLite due to questions over SQLite threading.
- Tied together with retiring moberg

**Comment by jarohen** [comment]
covered by #322 and #619
