### ISSUE TITLE
Process of running benchmarks should be documented in the bench README

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#572]
* How to get started (i.e. download the bench files)
* How to run benchmarks locally
* How the benchmarks are deployed

**Comment by danmason** [comment]
Alongside this, I would like to bring in a sort of workflow for testing on AWS - the docker script currently pushes an image tagged `:latest` (rather than `master`), would like to create a specific task to run `:latest` and use that within the `run-task` script.
