### ISSUE TITLE
Bench metrics can be analysed in Cloudwatch

### ISSUE THREAD

**Issue by t-taylor** [xtdb/xtdb#597]
Using some dropwizard -> aws convertor

- [x] ~we shouldn't submit derived metrics (e.g. percentiles) to CloudWatch~ see #648 
- [x] we should give the user the option to include/exclude metrics to be sent to CW, either by specifying a set of metric keys in `::cw/include-metrics` or `::cw/exclude-metrics`

**Comment by jarohen** [comment]
@t-taylor have updated the description here as discussed, because the acceptance test still fits with what we want to do next - will drop it back in 'in progress'

**Comment by t-taylor** [comment]
Currently the library used to export metrics to cloudwatch doesn't allow percentiles to be stripped out. I've submitted a pr, but until that happens, unless we fork and build it, this is blocked.
https://github.com/azagniotov/codahale-aggregated-metrics-cloudwatch-reporter/pull/34
