### ISSUE TITLE
Get cljr-clean-ns working for kafka-test

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#600]

**Comment by jonpither** [comment]
Found another bug - do it on crux.moberg

It takes out `[crux.moberg.types]` from the require, but then you can't compile the ns, because of stuff in imports. Looping in @benedekfazekas

**Comment by benedekfazekas** [comment]
https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L238 `cljr-libspec-whitelist` might provide a good workaround

**Comment by jarohen** [comment]
`crux.moberg` was removed long ago - `cljr-clean-ns` looks good now given we no longer have any requires-for-side-effects
