### ISSUE TITLE
Crux shouldn't need to go to the object store for primitive-like attributes

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#603]
Primitive values are already reversibly encoded in the triple indices, so we needn't go to the object store to decode them (especially if the object store moves off-node)

**Comment by hraberg** [comment]
Copied from #843 :

It's worth noting that chars will be decoded to single char strings using this, which would change the behaviour in the -unlikely- case someone stored a document with a character in it. If we want to support this properly we need to introduce a special type id for char so we can detect it and turn it back into a char.

On a similar note, Crux encodes say byte, short, int and long all as longs, similarly float and double. This will decode long and doubles only, but this is unlikely to be an issue as this is semi-normal Clojure behaviour.

**Comment by jarohen** [comment]
this is coming as part of #868, will close
