### ISSUE TITLE
Fix MemDB warnings

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#605]
We get quite a lot of `crux.kv.memdb - Using fsync on MemKv has no effect.` warnings during tests.

Don't know whether this a genuine misconfiguration or not - but let's either fix the misconfiguration or drop the warning?

**Comment by refset** [comment]
Proposal: we convert the existing ambiguous fsync-with-memdb warning: https://github.com/juxt/crux/blob/bd54020fdda13e4578778381cded269ed2652642/crux-core/src/crux/kv/memdb.clj#L70
...to be a much stronger warning, e.g. "Do not use memdb in production!" warning

Then also provide an option to disable the warning for people that know what they're doing (such as when we use memdb in our fixtures).
