### ISSUE TITLE
Renaming `crux.*/topology` to `crux.*/module`, after #568/#818

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#607]
see #568. strictly speaking, these are all now 'modules'

n.b. keeping the root `:crux.node/topology`, because a topology is a set of modules, but chances are most (if not all) other occurrences of `topology` should be `module`.

also, we should update the configuration documentation with definitions of topologies and modules

**Comment by jonpither** [comment]
My only beef was that you'd have a config like:

```
crux.topology = crux.jdbc/module
```

Which felt jarring. But TBH I'm over it now :-) People need to know you can build a topology using multiple, comma separated modules.

I'm not overly concerned by the break at this stage, it's a trivial config fix for users, in our alpha process.

**Comment by jarohen** [comment]
Parking this til we've looked at #818, we might well change up the topology

**Comment by jarohen** [comment]
no longer applicable, closing
