### ISSUE TITLE
Alpha Java API: CruxId cannot be used in Document

### ISSUE THREAD

**Issue by kosiakk** [xtdb/xtdb#636]
New alpha API (`20.01-1.6.2-alpha`) fails with an exception `Unfreezable type: class crux.api.alpha.CruxId` when I try to put an instance of `CruxId` into a `Document` to represent a foreign-key reference. Unfortunately `CruxId` is not transparent, so it's not even possible to properly unbox it in client code.

I guess, a quick patch would be to delegate encoding of this type to its inner field `id`. A drawback would be that such values will be *decoded* into a different type (actual Keyword, UUID, or a Map in our case), which might be quite confusing.

**Comment by danmason** [comment]
Thank you for the find! I've addressed this in the PR above, extending the serializer within `crux.codec` to handle **CruxIds**.

**Comment by jarohen** [comment]
Cheers @kosiakk :smile: just a heads-up that we're currently iterating on that Java Alpha API before we head into beta - hoping to incorporate it more into the current Java API to help with interoperability between the Clojure API and the API for the wider JVM, so there may be some changes in the area. Will of course keep you all informed!

As you've alluded to, it'll take some thought about the right place to convert between the two - knowing that you're currently working in the area, we'll see what we can do to best fix it both shorter- and longer-term.

Thanks again :smile:

**Comment by kosiakk** [comment]
Hi, James! :-) No hurry on this one. I finally got time to look into your _spoc_ code, and it seems that I'd better stick to existing Clojure-typed APIs even when calling Crux from Java/Koltin. (As we are trying to translate spoc to Kotlin for better understanding and knowledge sharing within the team).

I'm very open to participate in that API sub-project should you need a non-Clojure point of view.

**Comment by jarohen** [comment]
Hey Alex, hope you're keeping well :)

Closing this one as we're planning to fold the crux.api.alpha into the main Crux Java API. Will let you know when that happens and get your feedback.

Cheers!

James
