### ISSUE TITLE
We shouldn't submit derived metrics (e.g. percentiles) to CloudWatch

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#648]
see #597, https://github.com/juxt/crux/issues/597#issuecomment-585227706

CloudWatch derives percentiles etc for us, so we shouldn't submit them - if we do, CloudWatch might then try to calculate percentiles on the percentile metrics :boom: 

Depends on azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#34 being merged

**Comment by azagniotov** [comment]
@jarohen @t-taylor the azagniotov/codahale-aggregated-metrics-cloudwatch-reporter#34 is merged and `v2.0.5` was stage for live sync with Maven

**Comment by jarohen** [comment]
cheers @azagniotov :smile:

**Comment by azagniotov** [comment]
No worries, @jarohen :D
