### ISSUE TITLE
Duplicate documents submitted to standalone node cause 'incorrect doc state' error

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#653]
Repro:
* on standalone node (Kafka is unaffected)
* submit transaction T1 containing doc with content-hash C1
* submit loads more transactions (more than the Moberg batch size)
* submit another transaction T2 containing doc with content-hash C1
* if T1 hasn't been indexed by the time T2 is submitted (can simulate either with a bulk ingest, or by starting a second node and reindexing), you'll get an error like `ERROR crux.tx - Put, incorrect doc state for: #crux/id 91ef073d59b7ba3f52dbb6f6f58181dcfc2f44a4 tx id: 1619646077277186`

cheers @kosiakk for the report :smile: does this repro look like it'd affect your use case?

**Comment by jarohen** [comment]
test case: https://github.com/jarohen/crux/blob/moberg-compaction-bug-653/crux-test/test/crux/moberg_test.clj#L191

**Comment by kosiakk** [comment]
Awesome ^_^ thank you for the investigation.
It's probably the case for us as well, because indexing from the previous run did not finish when we've started another ingestion. So the queue might have contained duplicate copies of the same object, indeed.

**Comment by jarohen** [comment]
righteo, fix merged - I'll deploy a snapshot version in the morning :smile:

**Comment by jarohen** [comment]
@kosiakk new snapshot deployed, let me know how it goes :smile:

**Comment by kosiakk** [comment]
It seems okay now... although indexing seems to be faster now, and the backlog does not build up.
Every time I restart the processes it reports `:crux.tx/event-log {:lag 0 }`. This is great, of course, but probably won't stay that awesome when we switch to Kafka.

**Comment by jarohen** [comment]
that's an interesting metric in itself - implies that the indexing part might not be the bottleneck after all, definitely not what I'd've predicted (assuming the lag: 0 is correct, obv) - I wonder why... :thinking:
