### ISSUE TITLE
Test still leaving a 'data' directory

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#680]
There's one pesky test still leaving a 'data' directory behind - it should use `f/with-tmp-dir` like the others

**Comment by danmason** [comment]
After spending some time reading through and running the tests, I didn't have a single run where I had a leftover data folder. Doing some digging, I think I know why:

On the `bitemporal_tale_test`, where the node is [started](https://github.com/juxt/crux/blob/master/crux-test/test/crux/bitemporal_tale_test.clj#L7), it uses `crux.standalone/topology`. If `lein build` hasn't recently been ran on Crux (post the merge of #659), it would start a node with the old standalone topology defaults (a `rocksdb` kv-store with `data` directory).
