### ISSUE TITLE
Sorting maps adding a 10-20% performance overhead on ingest

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#685]
See comments from @kosiakk on https://github.com/juxt/crux/commit/f768fd4573881b89a21c10b78b46520ba08a536a.

Background: sorting maps was introduced so that maps consistently hash to the same value regardless of the key ordering within the map implementation. It needs to be consistent for anything that uses indices rather than documents - e.g. using maps as keys/values, but also CaS (which compares document hashes in the bitemp indices)

**Comment by kosiakk** [comment]
We ran 30 minutes of ingestion in 8 threads (on Linux), and `sort-maps` seems to take `30%` of time, 2'600 seconds:
![image](https://user-images.githubusercontent.com/368248/75537617-ab207480-5a17-11ea-83a7-890ab94c71ec.png)

Ping me, if you want to get the complete snapshot file.
