### ISSUE TITLE
CPU thread using 50% in idle state

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#688]
(from email)

Some non-JVM thread is using 50% CPU (4 cores) in completely idle state.

Tested both stable (1.6.2) and newest snapshot (1.6.3-alpha-SNAPSHOT) version.

RocksDB was not doing anything either, according to logs - both halves did no compaction, not any writes.

(I have further details)

**Comment by kosiakk** [comment]
So far it only happens on Windows machines. We ran it on Linux in Docker and `top` did not show that problem. The same still happens in version 1.7.0.

**Comment by kosiakk** [comment]
Good news, everyone!
The bug seems to be the problem of RocksDB itself. I've just updated version from `6.2.2` to `6.5.3`, and the problem on Windows disappears. Performance also doubles, magically.
Although `6.6.4` does not start due to some missing dll dependency :(

**Comment by jarohen** [comment]
oh, that _is_ good news - cheers @kosiakk :smile: will check our versions here

**Comment by jonpither** [comment]
Closing, as we have bumped RocksDB to solve.
