### ISSUE TITLE
Crux.newIngestClient starts indexing node and local store

### ISSUE THREAD

**Issue by kosiakk** [xtdb/xtdb#699]
It seems that local DB is created even if Crux is open using `Crux.newIngestClient` call.

Config:
```
{:crux.node/topology crux.kafka/topology, 
:crux.kv/db-dir "../dev-crux-database/db", 
:crux.kafka/bootstrap-servers "localhost:9092", 
:crux.kafka/tx-topic "crux-transaction-log", 
:crux.kafka/doc-topic "crux-docs", 
:crux.kafka/create-topics true, 
:crux.kafka/doc-partitions 7, 
:crux.kafka/replication-factor 1}
```

Tested in 20.01-1.6.2-alpha and 20.02-1.7.0-alpha

**Problem 1:** unclear config 
If we add `:crux.node/kv-store crux.kv.rocksdb/kv` option, the `newIngestClient` starts indexing. This problem is present in both versions.

**Problem 2:** possible regression
If `:crux.node/kv-stor` is not specified, version 1.6.2 works correctly, while 1.7.0 seems to start indexing anyway. I guess, it might be related to the new default MemDB indexer settings.

The problem is observable in thread dumps (there are two indexing threads) and log (messages from crux.kafka). DB files are created, and CPU load is different.

**Comment by jarohen** [comment]
hey Alex :) - could you try eliding the `crux.node/topology` key? looks like it's including that that's causing the other components to start up

James

**Comment by kosiakk** [comment]
Hello!
Do you mean not specifying anything for `:crux.node/topology`? Should it work? I guess, Kafka is not the default.

Or are referring to `:crux.node/kv-store`? Then it's a problem 2 - it starts anyway, but only in the latest release.

**Comment by jarohen** [comment]
Yes - I'd try removing the key entirely. Kafka's currently the _only_ tx-log we support for ingest-only clients - I'd like to make it so that you can use any tx-log, certainly!
