### ISSUE TITLE
Store attributes in content indices using a dictionary rather than a full hash

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#715]
We currently allocate 20 bytes for attributes in the two content indices, allowing for 2^160, ~10^48 potential attributes - we hash the attribute to ensure uniqueness.

This could instead be implemented by a dictionary of attributes maintained by the indexer (and stored in a new index).

We could use 4 byte ints (2^32, 4B) for these attributes and save ourselves 16 bytes in each 80 byte key, and accept that there'll be a slight overhead in translating between ints and attributes in indexing and querying.

(potentially 2 byte shorts if we're prepared to accept that 'users won't ever have more than 65536 attributes', although this seems a little small for a hard upper limit)

**Comment by jonpither** [comment]
> accept that there'll be a slight overhead in translating between ints and attributes in indexing and querying.

Hopefully an overhead in query parsing, not the actual query invocation. We could find that by shuffling a bit less data, there is a small performance boost waiting for us.

**Comment by kosiakk** [comment]
Awesome! A variable-length integer encoding might get you the best of both. Hashing not only eats up some space, it also ruins compression and cache coherence by being perfectly random.

**Comment by jarohen** [comment]
this only saved 0.5-1% disk space in practice (compared to 80->60 byte keys), so we decided to park this one, given we have other disk space optimisations in the pipeline.
