### ISSUE TITLE
New console deployed on console.crux.cloud

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#717]
* SSL cert's expired - let's use AWS's SSL certs so that they keep them up to date?
* let's migrate it up to the current version of Crux
* bonus points for CloudFormation'ing the infrastructure
* even more bonus points if it can re-use as much of the deployment work as possible (#719)
* decomm existing console app

**Comment by danmason** [comment]
Upon further inspection, I don't believe the SSL certs nor the domain are actually outdated. Will need to check this some more.

**Comment by danmason** [comment]
May need a load balancer, implementing some of the templates created for soak.
