### ISSUE TITLE
Unable to poll the tx-log on a remote (confluent.cloud) kafka

### ISSUE THREAD

**Issue by danmason** [xtdb/xtdb#726]
My Crux nodes were unable to read from a confluent.cloud hosted Kafka instance, `latest-completed-tx` would always return nil alongside all other queries on the node. With DEBUG logging, I could see that the `crux-doc-consumer` would poll documents successfully from the `doc-topic`, but `crux-tx-consumer` was unable to poll anything. 

Looking at Kafka's DEBUG logging I could see that `crux-tx-consumer` would start it's Kafka consumer (within `open-tx-log`) and would fail during the `poll` operation. The following line was outputted multiple times in the console:

```17:14:47.513 [crux-tx-consumer] DEBUG org.apache.kafka.clients.consumer.internals.Fetcher - [Consumer clientId=consumer-216, groupId=null] Leader for partition crux-transaction-log-0 is unknown for fetching offset```

Alongside this in the console, there were also the steps of a TLS handshake which doesn't get a chance to finish, the likely cause of the problem. (As the `poll` has a timeout of 100ms, this makes sense).

**Comment by danmason** [comment]
One initial idea (which did indeed fix the issue and allow tx-consumer to correctly poll its' documents) was the increase the tx-consumer `poll` timeout to 1 second (the same as that within the `doc-consumer`), though this may be a potential negative hit to performance.

Another pass at this was to do an initial `poll` operation with a longer timeout (in order to establish the TLS handshake) though this, unlike the above, failed to fix the issue.

**Comment by danmason** [comment]
Some further explorations on this - I'm unsure on my previous conclusion (of it being necessarily related to the TLS handshake). It does still appear to die during the call to `poll`, though I am not entirely sure why (and why it is the tx-consumer specifically).

Certainly seems related to the metadata request in general.

**Comment by jarohen** [comment]
@danmason this one resolved or still an issue?
