### ISSUE TITLE
Move tests into modules

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#784]
For example `crux.calcite-test` should be moved into crux-sql. There will be other tests that fall into this category. As part of this, we should move the relevant/needed fixture code into crux-test/src.

**Comment by jarohen** [comment]
wait for @jonpither's Calcite work before moving these about

**Comment by jarohen** [comment]
Currently moving a lot of this stuff around as part of #818 - let's hold fire on this one til that's done
