### ISSUE TITLE
Users can see the history of an entity

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#790]
- Same entity URL, add query params for including history
- Users can view diffs of entities over time (wikipedia history, commit logs)

**Comment by adam0z** [comment]
How will the diffs of entities look like?

**Comment by jarohen** [comment]
Good question - not 100% sure yet. On the API, I'd probably not include diffs (although I could be convinced); within the console UI we've got a lot more flexibility to render them based on the previous/next history entry.
