### ISSUE TITLE
Crux can restrict access to documents based on a user's permissions (ABAC)

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#798]

**Comment by refset** [comment]
@malcolmsparks and I are experimenting with a set of authorisation decorator capabilities covering:
1. RDF-like property and class inheritance using Datalog rules
2. Using those same rules for implementing primitive authz
3. XACML-inspired ABAC modelling
4. High-level EQL with embedded Crux Datalog resolvers  (i.e. unrelated to `(eql/project ?e ...)`)
5. Authz-aware EQL resolvers

WIP (across various branches): https://github.com/crux-labs/crux-auth (note: this is private, for now)

**Comment by refset** [comment]
Datalog can be used to implement all kinds of interesting and powerful authz schemes however there are no active roadmap plans to bake such schemes into the core offering at this stage.

For future relevant work by JUXT in this area see https://github.com/juxt/site - which uses XT behind the scenes.
