### ISSUE TITLE
REST API /history/[:key] endpoint does not allow to pass a map as the :key

### ISSUE THREAD

**Issue by adam0z** [xtdb/xtdb#803]
According to docs, this works:
```bash
curl -X POST $nodeURL/history/:ivan
```

Proposal:
Take data like POST /entity endpoint - in the request body:
```bash
curl -X POST \
     -H "Content-Type: application/edn" \
     -d '{:eid :ivan}' \
     $nodeURL/history
```

**Comment by jarohen** [comment]
Thanks @adam0z for the report :) 

@luciodale, @danmason could you ensure that your updated `/_entity` endpoint accepts map keys as part of your work on #790? cheers!
