### ISSUE TITLE
Search by valid time and transaction time in queries

### ISSUE THREAD

**Issue by adam0z** [xtdb/xtdb#817]
Question:
Is there any way to search by the metadata of an entity where valid time and transaction time are stored?
Something like this:
https://github.com/replikativ/datahike/blob/master/doc/time_variance.md#meta-entity

It would be useful to find an entity with an attribute value valid before/after/between some dates.

**Comment by jarohen** [comment]
We don't currently store any queryable metadata about the transactions, I'm afraid. Thanks for the suggestion, though :)

**Comment by jonpither** [comment]
@adam0z thank-you for this issue and the linked-in example. I'm closing this in favour of #968 where we will be tracking this.
