### ISSUE TITLE
Standalone event-log-kv-store configuration is confusing

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#818]
We've now had a number of support reqs related to the standalone event-log-kv configuration. If the user doesn't explicitly provide a value for `:crux.standalone/event-log-kv-store`, it has its own memdb default, which leads to some counter-intuitive behaviour - when the node's restarted, the indices are persisted but the tx-log isn't.

* We can't 'just' use the same KV store instance for both - because we'd like to be able to delete the indices' KV store (on an index version bump, for example) but not the tx-log's KV store instance.
* The topology system doesn't currently support being able to create multiple instances of the same component, so we can't just use the value under the `:crux.node/kv-store` key.

**Comment by refset** [comment]
There has been additional confusion resulting from the likelihood of accidentally typing `:crux.standalone/event-log-kv-store` instead of `:crux.standalone/event-log-kv` - perhaps this can somehow be solved at the same time.

**Comment by refset** [comment]
Regardless of how the mechanism works, I see two options:

1. Prevent use of kv persistence without a persisted event-log OR
2. fix:
2.a. event-log-dir not configured causes open-tx-log to throw as no protocol on ingest client AND
2.b. entity API not working on node restart when event-log-dir not configured
