### ISSUE TITLE
HTTP/2 support for HTTP API

### ISSUE THREAD

**Issue by jorinvo** [xtdb/xtdb#844]
While http2 support in Clojure is not very widespread yet, it is definitely well-supported in many languages which might be potential consumers of the HTTP API. Not paying for the overhead of establishing a new TCP connection for every database query would potentially speedup things a lot for applications and I think it is worth supporting it already before the Clojure ecosystem has completely catched up.
One day there might be support for this in Ring directly, coming with [Ring 2.0](https://github.com/ring-clojure/ring/issues/393). 
For now this Jetty9 adapter seems like a usable alternative: https://github.com/sunng87/ring-jetty9-adapter
Maybe there are other options also.

What do you think, is this something you would be interested in adding to the http-server? Thanks 🙂

**Comment by refset** [comment]
Thanks for opening this! I agree HTTP/2 is an important feature, and it is particularly relevant at the moment whilst we're working on various HTTP-related things.

It's probably worth noting that Vert.x is a strong contender (including pipelining and server push!).

We will update this with a more complete analysis & response when we find some time :)

**Comment by jorinvo** [comment]
Great to hear! Thanks @refset 🙂

**Comment by dmonay** [comment]
Is there an update on this? I can only use Crux via the HTTP API and this feature would assist with the case I'm building to use Crux in the critical path of our application. Conversely, lack of it somewhat weakens the case.

**Comment by refset** [comment]
Hi @dmonay, the nudge is appreciated! I'm happy to report that this will be receiving attention again fairly shortly - with the recent addition of JSON support it now makes a lot more sense to resolve this soon :slightly_smiling_face:

**Comment by jarohen** [comment]
Hey @jorinvo, @dmonay - PR's merged now, will go in with the next release :)
