### ISSUE TITLE
Basic Getting Started Docs

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#86]
Catch all card for the docs we need at launch. Doesn't need to capture or explain everything, but it needs to be possible to get started without reaching out to JUXT. We'll add comments here as we go.

**Comment by jonpither** [comment]
- [x] Customize nav, so we have a 'home' item
- [x] Don't render everything on the one page, users can use the nav structure to get around

I've been looking at https://nrepl.xyz/nrepl/index.html, but it seems they abandon the auto toc generation AFAICS. This means more work obv.

**Comment by jonpither** [comment]
- [x] We need to rework the README to drive people to the manual, which is where we should invest.

**Comment by jonpither** [comment]
Need to expand the getting started guide with examples of bringing up the individual components such as embedded Kafka, and how you then might wire these together using Component.

**Comment by refset** [comment]
@jonpither @hraberg Requesting help with the "Write a transaction" step...
```
user=> (db/submit-tx
 (:tx-log system)
 [[:crux.tx/put :http://dbpedia.org/resource/Pablo_Picasso
   {:crux.db/id :http://dbpedia.org/resource/Pablo_Picasso
    :name "Pablo"
    :last-name "Picasso"}
   #inst "2018-05-18T09:20:27.966-00:00"]])
IllegalStateException Attempting to call unbound fn: #'crux.hash/id-hash  clojure.lang.Var$Unbound.throwArity (Var.java:45)
```

**Comment by hraberg** [comment]
@refset the above commit should hopefully solve this.

**Comment by jonpither** [comment]
We have basic docs - it's a continuous job to improve them.
