### ISSUE TITLE
Transaction function impls are passed a context

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#865]
Currently, transaction functions are passed a database value at the current vt/tt and their args - we'd like to offer more:

* Ability to get a database at any vt/tt
* Details about the current transaction - transaction-time/transaction-id, other operations, etc - replacing the current dynamic var
* Anything else?

**Comment by refset** [comment]
* Ideally, in addition to the context of the start of transaction, also a "current" view of the db/context at the point of the operation in processing the transaction vector
