### ISSUE TITLE
Clarifying the on-disk index structure

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#868]
Context: we're currently debating the extent of the Indexer/IndexStore protocols (see #867)
Will keep this within the _current_ protocol.

The IndexStore exposes three index-related fns: AVE, AEV, and entity-as-of.

We need to support the following use cases efficiently:

1. User wants the full document for an entity at a given vt/tt
2. Given an A, give me all the entities with that attribute (AEV-E)
3. Given an AE, give me the current values (AEV-V)
4. Given an A, give me all the Vs (AVE-V)
5. Given an AV, give me all the current Es (AVE-E)
6. Given an E, give me the ETx at a given vt/tt (entity-as-of)
7. Given an ETx, give me the decoded V for a given A (bound-result-for-var)
8. Given a transaction, for each E, ensure all the documents have been indexed before I mark the transaction committed
9. Evict me an entity

## Current indices:

* EVT -> C
* AECV
* AVEC
* C -> Doc (object store)

With these indices, there's a lot of duplication in both the content indices.
For documents that have lots of incremental changes over time, we store all of the AV pairs every time.

### 'Removing C' (#754)

* EVT -> C
* AE
* AVE
* C -> Doc (object store)

Worked well at reducing disk space (~60-70%) and saw a corresponding decrease in ingest time (purely because there was less to ingest, presumably). Query time was bad, though, 80% increase in Watdiv - caused by needing to go to the object store much more frequently to check the current AVs for an entity.

### 'CAV' (#821)

* EVT -> C
* AE
* AVE
* CAV -> decoded V

Worked reasonably well at reducing the disk space (~40%) while keeping the query time down (Watdiv was comparable). Ingest time was 20% higher, though, and there was still plenty of duplication in the CAV index.

## Next iteration

(proposal)

Adding another level of indirection - a 'hash cache' - storing decoded values where we can't immediately decode them from the values in the index keys.

* `EVT -> C` (unchanged)
* `EV -> decoded V` (only for V not decodeable from the value)
* `AECV`
* `AVE`

Notes:

* We're ensuring that everything the query engine needs is local; all of the other APIs (entity, full-results, history docs, etc) can go to the doc-store
* No (on-disk) object store

Running through those reqmts again:

1. User wants the full document for an entity at a given vt/tt: EVT -> C, doc-store
2. Given an A, give me all the entities with that attribute (AEV-E): scan `AEV`
3. Given an AE, give me the current values (AEV-V): scanning `AECV`
4. Given an A, give me all the Vs (AVE-V): scan `AVE`
5. Given an AV, give me all the current Es (AVE-E): AVE gives us an E, EVT gives us C, check against AECV.
6. Given an E, give me the ETx at a given vt/tt (entity-as-of): `EVT` -> `C`
7. Given an ETx, give me the decoded V for a given AV (bound-result-for-var): `AECV` -> V, try decode it directly, or use `EV` -> `V`
8. Given a transaction, for each E, ensure all the documents have been indexed before I mark the transaction committed: check `AECV` for `:crux.db/id` for that content-hash.
9. Evict me an entity: this one isn't quite as efficient - scan AECV for all attributes to get all content-hashes for that entity, can then remove from AECV (have the full key), AVE and EV.

**Comment by hraberg** [comment]
As discussed, we will need access to the content hash at times as the TxLog will still use it. The IndexStore itself can talk EntityTxs though and not explicitly deal with it. We might be able to get away from ever needing it on the query side.

That said, if we move towards a more opaque version identifier concept (which now happens to be the content hash), we could in the future move towards having this being the hash of the bitmap itself, which wouldn't require sorting. Haven't analysed this deeply though!

**Comment by hraberg** [comment]
That is, it wouldn't be a breaking change I think to change the hashing on the ingest side from one day to another, the data in the document store is just keyed by some hash. This would result in duplication there though, but not likely the end of the world.

Another reason we still need to be able to access an entities old content hashes is to evict it properly, as old documents would been ingested under such a hash.

**Comment by hraberg** [comment]
Latest iteration:

* EVT -> C (still unchanged)
* AECV
* AVE -> decoded AV
* EA
* no object store

> User wants the full document for an entity at a given vt/tt

EVT gives C, EA gives #{A}, scan AECV for V, values of AVE give us decoded doc
Given an A, give me all the entities with that attribute (AEV-E)
AECV

> Given an AE, give me the current values (AEV-V)

AE (and implicit C) -> AECV

> Given an A, give me all the Vs (AVE-V)

AVE

> Given an AV, give me all the current Es (AVE-E)

AV gives us Es, we have Cs for those Es, cross-check against AECV

> Given an E, give me the ETx at a given vt/tt (entity-as-of)

EVT -> C

> Given an ETx, give me the decoded V for a given A (bound-result-for-var)

If we can't decode it from the index V, AECV gives us V, look up in AVE to get decoded V

> Given a transaction, for each E, ensure all the documents have been indexed before I mark the transaction committed

look up :crux.db/id E C E in AECV

> Evict me an entity

EVT gives us all Cs, AECV gives us all Vs, can then evict from all four tries

**Comment by jarohen** [comment]
Got the doc-index removed from the KVIndexer - going to park it til I've had chance to pair with @hraberg regarding the Standalone and Kafka document stores
