### ISSUE TITLE
Ensure Nodes Have Recent Data When Serving

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#87]
When providing transaction time during a query, one can ensure a query times out if the expected time isn't there. When a node is starting, or during high ingest load, nodes will be far behind the latest data.

All this mainly applies to the HTTP API, as if you're a local node, you might be behind, but at least your view of the world would be consistent. What we really want to avoid is subsequent queries to produce inconsistent results due to going to nodes with different positions in the log.

There are several aspects to this. In normal operation, the node can avoid serving queries until it has  "caught up". More generally, one wants to have sticky sessions for the nodes, so a client keep seeing at least the same latest data, and doesn't back and forth in time when not supplying transaction time (which is likely the normal case).

How to decide if a node is caught up or not is a matter of interpretation, as it will always by definition lag behind. The simplest case it decides that it has caught up the first time it cannot read more data from Kafka, and then let it be.

In a more complex case it can fall behind again during high load and should potentially stop serving queries. You basically accept that nodes need to be at least X ms from the latest transaction in Kafka, but this is harder to keep track of and get right, and also fuzzy as it can still lead to inconsistent queries. 

Falling behind is also a factor of the transaction time - if the client requests old data, a lagging node might still be able to respond to the request, but this would complicate things.

One other, potentially cleaner approach, is to push this problem to the client, and enforce the client to -always- have to provide a timestamp (which it can update as it goes) and block based on it. This can be done by having the remote API client defaulting transaction time to now.

Requires some analysis for what is the simplest acceptable solution for Phase 2. I think that the minimum would likely be to use a combination of sticky sessions (push the problem to the load balancer) while also waiting to serve data until the first time it manages to catch up. This can be done by asking Kafka for the latest known transaction id, and store it in the KV store, and subsequently update it once the consumer has caught up. The API would use this to check if a node is considered caught up. This is obviously not perfect, but might strike a balance between complexity and acceptance.

**Comment by danielcompton** [comment]
> More generally, one wants to have sticky sessions for the nodes, so a client keep seeing at least the same latest data, and doesn't back and forth in time when not supplying transaction time (which is likely the normal case).

Could the driver have the capability built-in to keep track of the latest time seen?

> This can be done by having the remote API client defaulting transaction time to now.

I would imagine you would only need to query the latest TX time initially, and then the client would keep track of it from there. I might be missing something here though?

**Comment by hraberg** [comment]
@danielcompton as you can see in recent commits, I've fallen back to simply forcing the user to supply the timestamps. While not optimal, it's easy to reason about. One problem with this is that if the node is validly old - there's no new data, it will time out unless one provides a transaction time it has seen.

The client could read the latest time from the status page, but this won't (yet) tell you if this is recent data or not. As you say, Crux's own client implementation could in theory keep track of this and more, but it would be nice if it's easy to use from Curl as well. Crux could provide various headers back so one can see at what timestamp one actually did a read.

I'm currently focusing on trying to get the right state out of Kafka and then see what we'll do about it, see latest commit above. Once this works, it should be possible to do client reads which waits for a timeout for the data to be recent, without having to know what "recent" is in absolute dates, and we can remove the need for the client to always supply the timestamps.

**Comment by hraberg** [comment]
It might be worth mentioning - now that there's a wider audience here, that the main intended use case initially for Crux is that you embed it in your application and benefit from running queries locally.

While data may still be stale, it will always be the most recent to the local node. We have as we're getting closer to launch starting to look a bit more closely at what the minimum remote API requirements are, as it can be easier to use Crux that way, like a normal remote service. In time, we expect this part to evolve.

**Comment by hraberg** [comment]
This has now moved in the direction so when using the public API, it will always wait for any lag to 
disappear (first awaiting the transaction time, if applicable). If using the lower-level APIs it will never block for just calling `crux.query/db`.

This also means the remote API doesn't need to specify the business and transact time anymore, blocking will just happen server side via the public API.

**Comment by hraberg** [comment]
This is arguably done in the public API now, so closing this card. We are sure to revisit this entire space as we go.
