### ISSUE TITLE
Submitted `put` not showing up in subsequent query. Possibly related to changing node configuration.

### ISSUE THREAD

**Issue by eihli** [xtdb/xtdb#871]
I ran into this shortly after completing the tutorial. I ran a `submit-tx` followed by a query for every `crux.db/id` in the database and the document I submitted did not show up.

The following `submit-tx` and `q` were run several minutes apart. It wasn't related to a sync or await-tx issue.

```
app.pathom> (crux/submit-tx db/conn [[:crux.tx/put {:crux.db/id :person/test :email "test@example.com(opens in new tab)"}]])
;;
;; => #:crux.tx{:tx-id 12, :tx-time #inst "2020-05-12T21:00:02.538-00:00"}
;;
;; Looks like that submitted. 
;; I expect to see a `:person/test` entity on this next query.

app.pathom> (crux/q (crux/db db/conn) '{:find [e] :where [[e :crux.db/id v]]})
;;
;; => #{[:commodity/Pu] [:person/johanna] [:manifest] [:person/ilex]
  [:commodity/borax] [:commodity/CH4] [:commodity/Au] [:commodity/C]
  [:tombaugh-resources] [:gold-harmony] [:person/thadd]
  [:blue-energy] [:encompass-trade] [:commodity/N]}
```

This was my config at the time of the issue. This config may have changed at some point between the first time I ran the code and the data directories were created and the time I ran the code when I experienced the issue.

```
(def config
  {:crux.node/topology '[crux.standalone/topology
                                     crux.kv.rocksdb/kv-store]
   :crux.standalone/event-log-dir "crux-store/eventlog-1"
   :crux.kv/db-dir (str (io/file "crux-store" "db"))})
```

I added a `println` in each `crux/api.clj`  `PCruxDatasource/q` and `crux/standalone.clj` `StandaloneDocumentStore/submit-docs`.

`crux/submit-tx`  prints that it's using a `CachedObjectStore` that is using a `KvObjectStore` with a `CachedSnapshotKvStore` with `crux.kv.memdb.MemKv`.

`crux/q` prints that it's using a `CachedObjectStore` that is using a `KvObjectStore` with a `CachedSnapshotKvStore` with `crux.kv.rocksdb.RocksKv`.

I renamed the data directory so that it would create a new one when I re-ran the code. The fresh data directory works fine. So I expect the problem to be that the data directory became corrupt and I expect that to have happened due to me using the same data directory while changing the config. That's my guess.

I'm attaching the broken data directory so that the problem can be reproduced and maybe someone can spot what in the directory is causing the problem.

[broken-data-dir.tar.gz](https://github.com/juxt/crux/files/4623185/broken-data-dir.tar.gz)

**Comment by refset** [comment]
Hi @eihli - I just spotted that this issue inadvertently fell off our Project board last year and consequently never got reviewed, despite me still showing as an assignee...I'm very sorry about that :disappointed: I hope it didn't block you from getting to grips with Crux.

Given the various bugfixes, API, & under-the-hood changes that have happened over the last 13 months we should probably close this now. Please feel free to disagree though!

Thank you for your efforts in reporting and carefully documenting the issue.
