### ISSUE TITLE
Unused arg bound to false causes query to not return any results

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#882]
(reported by Toyam Cox (@Vaelatern) on [Slack](https://clojurians.slack.com/archives/CG3AM2F7V/p1589946575361300))

* Including an unused argument with a value of `true` returns results (correctly?)
* Including an unused argument with a value of `false` no longer returns results (bug)

```clojure
dxpb-clj.db=> (crux/q (crux/db  @node) {:find ['e] :where '[[e :pkgname a]] :args [{'a "st"}]})
#{[:st:x86_64:x86_64:cross:false] [:st:x86_64:x86_64-musl:cross:false]}
dxpb-clj.db=> (crux/q (crux/db  @node) {:find ['e] :where '[[e :pkgname a]] :args [{'a "st" 'c false}]})
#{}
dxpb-clj.db=> (crux/q (crux/db  @node) {:find ['e] :where '[[e :pkgname a]] :args [{'a "st" 'c true}]})
#{[:st:x86_64:x86_64:cross:false] [:st:x86_64:x86_64-musl:cross:false]}
```

**Comment by Vaelatern** [comment]
Whether the argument is used or not seems to be irrelevant. If I use `c` then I still get the same results.

**Comment by Vaelatern** [comment]
@SevereOverfl0w pointed me at https://github.com/juxt/crux/blob/b13b4da988ed7e91dc7685e5d5ab5c374194895f/crux-core/src/crux/query.clj#L271-L273

**Comment by SevereOverfl0w** [comment]
Don't have time to open PR right this second, but this fixes it for me:

```
(defn- arg-for-var [arg var]
  (second
    (or (find arg (symbol (name var)))
        (find arg (keyword (name var)))
        [])))
```

**Comment by Vaelatern** [comment]
Cool. As a non-crux dev, how might I use the HEAD version of this code to verify that it fixes my issue?

**Comment by refset** [comment]
@Vaelatern hey, you can clone the repo and do a `lein sub install` in the project root to create a local snapshot version that you can depend on temporarily from your other project.

**Comment by Vaelatern** [comment]
To be clear, you want me to run that command in `./crux/` after checkout, yes? Do you happen to have the doc necessary for me to depend on an arbitrary project path? I'm afraid I've never done so before, and google turned up nothing quickly (too many quick-start guides). Thank you!

**Comment by Vaelatern** [comment]
Seems to work for me, thanks!
