### ISSUE TITLE
Optimising UnaryJoinVirtualIndex

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#905]
We've identified `UnaryJoinVirtualIndex` as one area of the query engine that would particularly benefit from optimisation - any performance improvements to this index will likely result in a decent speed-up in the overall engine.

**Comment by hraberg** [comment]
It doesn't seem like it's actually unary join itself that's the slow part, it's more the fact that it performs a join along several close to identical indexes it has to scan, having to read out the data n times.

**Comment by hraberg** [comment]
A potential option here is to fold down the left-hand side of the E to a single index, more or less ignoring the clauses with the lower attribute count, and then point all right-hand side V indexes to the same left-hand peek state. This might require some cleanup in crux.index, and some changes to crux.query, but worth spiking.

An option is also to make indexes in general aware of the parent join keys, as that removes the need for peek state and coupling between them in this case.

**Comment by hraberg** [comment]
Note that the smallest left hand side might still be a super set of a real intersection, but this would be pruned down later down in the join as the attribute values are bound.

**Comment by hraberg** [comment]
Closing this, related work will be done as part of #907. The unary join step itself can be tweaked a bit, but isn't the bottleneck for most queries.
