### ISSUE TITLE
Optimising equals/range constraints

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#906]
We currently treat equals/inequalities as range constraints if one side's a literal; if both are logic-vars we treat it as a predicate (once both are bound). This means (for example) that queries using args as one side of a range/equals constraint don't make the best use of indexes - we have to fully realise the values before we can apply the constraint. We'd like to 

* Even if we do have two logic vars, we only need to wait until we have one side bound, and then apply a range constraint to the second index further down the join depth. 
* `=` would then be a special case of this - as soon as we bind one side, we can bind the other side. 
* We could take advantage of this in the query planning, too - if we know one side is a small relation, we bind that first, then immediately get the other side bound.
* We could consider deprecating/removing `==` (unify) once this change is in.

**Comment by hraberg** [comment]
This is related to #348.
