### ISSUE TITLE
StandaloneDocumentStore fetch-docs always creates a snapshot

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#918]
Regardless of a cache hit/miss on the oft wrapped `CachedObjectStore`.

**Comment by hraberg** [comment]
The real solution to this is to get rid (or fold in) the object store and its cache, and add a CachedDocumentStore instead.

At a related note, you could recycle the snapshot inside the KvObjectStore, as you only need to update the snapshot when new docs are written as you don't care about other data in the store. In some stores, like LMDB, the snapshot is a read transaction, so not something one would want to keep around.

We could also re-add get-value on KvStore itself, if you don't care about snapshot versioning, which might be the case in the document store.

**Comment by jarohen** [comment]
Done with #961
