### ISSUE TITLE
Query Stress Test

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#927]
Whilst tackling a recent memory leak (see https://github.com/juxt/crux/pull/924), I found this test setup was a good stress test to bring about an OOM: https://github.com/juxt/crux/blob/jp/calcite/dev/jon.clj.

My proposal in this issue, is to have a dedicated nightly stress test - beginning with using the above code,  running the bottom query ~25 times, against a single node setup using RocksDB. This will stress-test the Crux query engine. In the future we could have similar stress-tests for ingest and other areas if need be.

The existing bench setup in my mind, is to show relative timings to other databases and to track ingest/query speed across node variants. The point of this stress-test is to ensure we don't OOM again, testing a particular target area (querying against Rocks).

**Comment by jonpither** [comment]
If we were to implement this, we would want to prove a stress-test can capture the OOM that #924 fixed - before/after. Might also want to tweak the number of times you run the query (25 is a figure that feels right to me, but could also be too high or low).

**Comment by jarohen** [comment]
Stress test passed on (current) [first known bad](https://github.com/juxt/crux/commit/7f043f456b212761c1216d8b1129a9e396c6932a), see [CloudWatch](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/crux-bench-dev/log-events/james-$252Fbench-container$252F51627cad-2e49-4a79-98cd-db25d8cf2e6c)

Can use [this commit](https://github.com/jarohen/crux/tree/post-index-store-recycling) as a base for further commits
