### ISSUE TITLE
In crux-http-server, SimpleDateFormat isn't thread-safe

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#930]
Investigate Java 8 date formatters, which are more likely to be thread-safe

**Comment by hraberg** [comment]
As mentioned on call, there's a `crux.io/format-rfc3339-date` which might be useful to look at.

**Comment by danmason** [comment]
Taking a look at https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html, also

**Comment by danmason** [comment]
Using DateTimeFormatter - got it working properly. Committed and will be brought in as part of #899
