### ISSUE TITLE
Can we prevent 'tag' builds running on non-JUXT CircleCI instances?

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#948]
Just noticed I had a release build waiting on my own CircleCI instance: https://app.circleci.com/pipelines/github/jarohen/crux/915/workflows/8fb3c871-5c8c-4413-b317-24e944f183ab. Repro is to push a tag to your own fork - shouldn't see a release build started on your CircleCI fork.

**Comment by danmason** [comment]
In short (at least for the moment)  - I don't think so. We can't prevent the job itself running - the only two real mechanisms to do so are not currently part of CircleCI:

- https://ideas.circleci.com/ideas/CCI-I-356 Filtering by `owner`
- https://discuss.circleci.com/t/may-i-use-if-else-in-the-cicleci-v2-0-workflows-not-in-the-job/26240 Using `if else` in workflows.

We can have conditional steps in jobs themselves, but I can't think of a way to prevent the initial job getting triggered.

**Comment by jarohen** [comment]
no worries - thanks for looking into it :)

**Comment by danmason** [comment]
Worth keeping an eye on circleci releases, see if any of the above get added :+1:
