### ISSUE TITLE
tx-fn breaks indexing

### ISSUE THREAD

**Issue by nivekuil** [xtdb/xtdb#956]
Following up from slack, here's some test code:
```
(ns rhizome.core
  (:require [clojure.java.io :as io]
            [crux.api :as crux]
            ))

(defn start-standalone-node ^crux.api.ICruxAPI [storage-dir]
  (crux/start-node {:crux.node/topology '[crux.standalone/topology crux.http-server/module]
	                :crux.kv/db-dir (str (io/file storage-dir "db"))
                    :crux.http-server/port 8080}))

(def node (start-standalone-node "crux-store"))

(def tx
  (crux/submit-tx node
                  [[:crux.tx/put
                    {:crux.db/id :delete-where-from
                     :crux.db/fn
                     '(fn [ctx from-id]
                        (let [edges (crux.api/q
                                     (crux.api/db ctx)
                                     {:find [e] :where [[e :from from-id]]})]
                          (mapv (fn [edge-id] [:crux.tx/delete (first edge-id)]) edges)))}]]))
(crux.api/tx-committed? node tx)
(def tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae06"}]]))
(crux.api/tx-committed? node tx)
(def tx (crux/submit-tx node [[:crux.tx/fn :delete-where-from #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae06"]]))
(crux.api/tx-committed? node tx)
(def tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae07"}]]))
(crux.api/tx-committed? node tx)

```
The first and second tx-committed? are true, the subsequent ones return a `crux.api.NodeOutOfSyncException`. I'm not sure if the third one should happen but the fourth one probably shouldn't.

I'm running this through `cider-jack-in`. My deps.edn:
```
{:paths ["src/clj"]
 :deps {org.clojure/clojure {:mvn/version "1.10.1"}
        juxt/crux-core {:mvn/version "20.06-1.9.1-beta"}
        juxt/crux-http-server {:mvn/version "20.06-1.9.1-alpha"}
        }
 :aliases {:run {:jvm-opts ["-Xmx512m"]}}}
```

**Comment by refset** [comment]
Hi @nivekuil thanks for identifying and reporting the issue so thoroughly.

I believe the problem here is happening during the reading of the function, rather than the execution, and I can't see that our existing tests have accounted for this level of error. The underlying issue is that the `e` logical variable needs quoting.

This version with the (nested) quoted `e` doesn't break the indexer:
```clojure
(def tx
  (crux/submit-tx node
                  [[:crux.tx/put
                    {:crux.db/id :delete-where-from
                     :crux.db/fn
                     '(fn [ctx from-id]
                        (let [edges (crux.api/q
                                     (crux.api/db ctx)
                                     {:find ['e] :where [['e :from from-id]]})]
                          (mapv (fn [edge-id] [:crux.tx/delete (first edge-id)]) edges)))}]]))
```
We will hopefully be able turn around another release with a fix for this very soon. Sorry for the rough edges...your patience in the meantime is very appreciated :)

**Comment by jarohen** [comment]
Hey @nivekuil,

Those ran ok for me at the REPL when I ran them as individual forms, which suggests that the `tx-committed?` calls are running before the node has had chance to index the transaction. Adding `await-tx` before the call to `tx-committed?` seems to make the test case run through:

```clojure
(def tx
  (crux/submit-tx node
                  [[:crux.tx/put
                    {:crux.db/id :delete-where-from
                     :crux.db/fn
                     '(fn [ctx from-id]
                        (let [edges (crux.api/q
                                     (crux.api/db ctx)
                                     {:find [e] :where [[e :from from-id]]})]
                          (mapv (fn [edge-id] [:crux.tx/delete (first edge-id)]) edges)))}]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)

(def tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae06"}]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)

(def tx (crux/submit-tx node [[:crux.tx/fn :delete-where-from #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae06"]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)

(def tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae07"}]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)
```

Crux indexes transactions asynchronously so, in order to reliably read your writes, you'll need to `await-tx` before you read - you _might_ get lucky, particularly at the REPL if they're small transactions and you're executing forms one at a time, but best to `await-tx` to be sure.

Could you check this works for you and let me know?

Cheers!

**Comment by nivekuil** [comment]
The quoted `'e` works, but without it await-tx still crashes. Literal output from the cider repl: 
```
rhizome.core> (def tx
  (crux/submit-tx node
                  [[:crux.tx/put
                    {:crux.db/id :delete-where-from
                     :crux.db/fn
                     '(fn [ctx from-id]
                        (let [edges (crux.api/q
                                     (crux.api/db ctx)
                                     {:find [e] :where [[e :from from-id]]})]
                          (mapv (fn [edge-id] [:crux.tx/delete (first edge-id)]) edges)))}]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)

(def tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae06"}]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)

(def tx (crux/submit-tx node [[:crux.tx/fn :delete-where-from #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae06"]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)

(def tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id #uuid "d84df13d-dc3c-4554-869e-1d01cd77ae07"}]]))
(crux/await-tx node tx)
(crux.api/tx-committed? node tx)
#'rhizome.core/tx#:crux.tx{:tx-time #inst "2020-06-20T07:36:22.370-00:00", :tx-id 5}true#'rhizome.core/tx#:crux.tx{:tx-time #inst "2020-06-20T07:36:22.476-00:00", :tx-id 6}true#'rhizome.core/txExecution error at crux.tx/->tx-fn (tx.clj:191).
Unable to resolve symbol: e in this context
Execution error (NodeOutOfSyncException) at crux.node.CruxNode/hasTxCommitted (node.clj:84).
Node hasn't indexed the transaction: requested: Sat Jun 20 00:36:22 PDT 2020, available: Sat Jun 20 00:36:22 PDT 2020
#'rhizome.core/txExecution error at crux.tx/->tx-fn (tx.clj:191).
Unable to resolve symbol: e in this context
Execution error (NodeOutOfSyncException) at crux.node.CruxNode/hasTxCommitted (node.clj:84).
Node hasn't indexed the transaction: requested: Sat Jun 20 00:36:22 PDT 2020, available: Sat Jun 20 00:36:22 PDT 2020
```

**Comment by jarohen** [comment]
I see what you're seeing on 1.9.0; on 1.9.1 I see the following (without line breaks, at my REPL)

```clojure
#'user/tx
#:crux.tx{:tx-time #inst "2020-06-20T15:19:42.869-00:00", :tx-id 0}
true
#'user/tx
#:crux.tx{:tx-time #inst "2020-06-20T15:19:43.025-00:00", :tx-id 1}
true
#'user/tx#:crux.tx{:tx-time #inst "2020-06-20T15:19:43.137-00:00", :tx-id 2}
false
#'user/tx#:crux.tx{:tx-time #inst "2020-06-20T15:19:43.252-00:00", :tx-id 3}
true
```

Will keep digging...

**Comment by nivekuil** [comment]
Weird; if it helps, I'm using Java 14 openj9.  cider-doc confirms that I'm using crux 1.9.1:
```
crux.api/submit-tx
 [node tx-ops]
  Writes transactions to the log for processing
  tx-ops datalog style transactions.
  Returns a map with details about the submitted transaction,
  including tx-time and tx-id.

crux.api/submit-tx is defined in
jar:file:/home/nivekuil/.m2/repository/juxt/crux-core/20.06-1.9.1-beta/crux-core-20.06-1.9.1-beta.jar!/crux/api.clj.
```

**Comment by nivekuil** [comment]
I'm seeing some more weird behavior that I don't think should happen: a tx is committed but it doesn't show up in queries. This is with the rocksdb backend and something similar also happened when I was trying the lmdb backend. Behavior persists after restart. The effect is that the entire database appears to be silently read-only at this point.
```
rhizome.core> 
(def tx
  (crux/submit-tx node
                  [[:crux.tx/put
                    {:crux.db/id #uuid "89250a85-99fa-4700-96dd-dd9b861cabb9"}]]))

#'rhizome.core/tx
rhizome.core> (crux/tx-committed? node tx)
true
rhizome.core> (crux/entity (crux/db node) #uuid "89250a85-99fa-4700-96dd-dd9b861cabb9")
nil
rhizome.core> (crux/entity (crux/db node) "89250a85-99fa-4700-96dd-dd9b861cabb9")
nil
```

**Comment by jarohen** [comment]
I can't repro that one locally either I'm afraid - here's an example project:

deps.edn:
```clojure
{:deps {juxt/crux-core {:mvn/version "20.06-1.9.1-beta"}
        juxt/crux-rocksdb {:mvn/version "20.06-1.9.1-beta"}}}
```

src/foo.clj:
```clojure
(ns foo
  (:require [crux.api :as crux]))

(defn -main [& args]
  (with-open [node (crux/start-node {:crux.node/topology ['crux.standalone/topology
                                                          'crux.kv.rocksdb/kv-store]
                                     :crux.kv/db-dir "/tmp/crux-956/db-dir"
                                     :crux.standalone/event-log-kv-store 'crux.kv.rocksdb/kv
                                     :crux.standalone/event-log-dir "/tmp/crux-956/event-log-dir"})]
    (let [tx (doto (crux/submit-tx node
                                   [[:crux.tx/put {:crux.db/id #uuid "89250a85-99fa-4700-96dd-dd9b861cabb9"}]])
               (->> (crux/await-tx node)
                    (prn :tx)))]
      (prn :tx-committed? (crux/tx-committed? node tx))
      (prn :uuid-entity (crux/entity (crux/db node) #uuid "89250a85-99fa-4700-96dd-dd9b861cabb9")))))
```

I run it with `clj -m foo`, and get:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
:tx #:crux.tx{:tx-time #inst "2020-06-26T09:50:34.779-00:00", :tx-id 0}
:tx-committed? true
:uuid-entity #:crux.db{:id #uuid "89250a85-99fa-4700-96dd-dd9b861cabb9"}
```

Is that what you're seeing?

**Comment by nivekuil** [comment]
To clarify, the read-only behavior I'm seeing happened after a period of use. I assume I must have done something, probably involving the transaction function, to break the database state. Your example works fine.

I've actually kept the broken database around and confirmed that it's still in that broken, read-only state. I can zip up the rocksdb folder and send it to you for debugging. Nothing seriously private but I'd appreciate some discretion regardless :) Is the email in your github profile acceptable?

**Comment by jarohen** [comment]
> I can zip up the rocksdb folder and send it to you for debugging. Nothing seriously private but I'd appreciate some discretion regardless :)
 
Thanks - and of course :) 

> Is the email in your github profile acceptable?

Could you send it to jms@juxt.pro?

**Comment by nivekuil** [comment]
Let me know if you need more cases of broken databases. Currently I've got 4 broken rocksdb folders lying around.

**Comment by jarohen** [comment]
Hey @nivekuil, sorry for the delay - I suspect your second issue here is related to #818. 

#818 is caused when the golden store tx-log and document-store are in-memory, but the indices (stored in RocksDB, in your case) are persisted between node restarts, which means that the node only has half the data it needs to serve queries.

To repro:

```clojure
(let [node-config {:crux.node/topology '[crux.standalone/topology
                                         crux.kv.rocksdb/kv-store]
                   :crux.kv/db-dir "/tmp/rocksdb-indices"}]

  (with-open [node (crux/start-node node-config)]
    (let [tx (crux/submit-tx node [[:crux.tx/put {:crux.db/id :foo, :foo 42}]])]
      (crux/await-tx node tx))

    (prn (crux/entity (crux/db node) :foo))
    ;; => {:crux.db/id :foo, :foo 42}
    )

  ;; restart the node, check the entity
  (with-open [node (crux/start-node node-config)]
    (prn (crux/entity (crux/db node) :foo))
    ;; => should be same as above, but is `nil`
    ))
```

Replacing the `node-config` with the following does print out `{:crux.db/id :foo, :foo 42}` twice, as you'd expect.

```clojure
{:crux.node/topology '[crux.standalone/topology
                       crux.kv.rocksdb/kv-store]
 :crux.kv/db-dir "/tmp/rocksdb-indices"
 :crux.standalone/event-log-kv-store 'crux.kv.rocksdb/kv
 :crux.standalone/event-log-dir "/tmp/crux-event-log"}
```

We're aware that this is quite a rough edge in Crux at the moment and are discussing the best way to solve it.

I wonder whether there's another issue at play here - but it'd be good to rule this one out to begin with!

If you can still repro this issue after this node configuration change, could you send me through both the indices RocksDB (from `:crux.kv/db-dir`) and the event-log RocksDB (from `:crux.standalone/event-log-dir`)?

Cheers

**Comment by jarohen** [comment]
Hi @nivekuil - would you mind checking the transaction function issue against 1.9.2?

**Comment by nivekuil** [comment]
It looks like using the tx-fn with unquoted logical variables no longer stops indexing, and I think persisting the other stores has fixed the read-only behavior, so that's all great news :). However, I think I still need to continue using the quoted logical vars, otherwise calling `submit-tx` with a vector of txs on an empty database, like so:
```
(def x (crux/submit-tx node [[:crux.tx/fn :delete-where-from #uuid "e9aebbfd-0402-42e0-b35d-09df55e760fa"]
[:crux.tx/put 
{:crux.db/id #uuid "e9aebbfd-0402-42e0-b35d-09df55e760fa"
 :type :vertex
 :name "foo"
 :org/category "inbox" }]
[:crux.tx/put 
{:crux.db/id #crux/id {:from #uuid "e9aebbfd-0402-42e0-b35d-09df55e760fa" :to #uuid "8cb8404e-8379-440c-a290-edf0df18cb80"}
 :type :edge
 :name ""
 :from #uuid "e9aebbfd-0402-42e0-b35d-09df55e760fa"
 :to #uuid "8cb8404e-8379-440c-a290-edf0df18cb80"
}]]))
```
seems to stop the entire tx from committing, so the database remains empty:
```
(crux/await-tx node x)
#:crux.tx{:tx-time #inst "2020-07-13T22:26:45.664-00:00", :tx-id 3}
(crux.api/tx-committed? node x) 
false
```

I don't know if this is intended, but regardless it veers out of the scope of this issue, so I think it can be closed.

**Comment by jarohen** [comment]
> It looks like using the tx-fn with unquoted logical variables no longer stops indexing, and I think persisting the other stores has fixed the read-only behavior, so that's all great news :).

Excellent! Thanks for helping us out with this one.

> However, I think I still need to continue using the quoted logical vars, otherwise calling submit-tx with a vector of txs on an empty database [...] seems to stop the entire tx from committing, so the database remains empty

Yes, that's correct - if there's any kind of error in the tx-fn invocation, the whole transaction atomically rolls back.
