### ISSUE TITLE
Console styling 2020-06-19

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#959]
- [x] Console - arrows for dropdown
- [x] VT/TT dropdown arrows
- [x] Query/Entity tabs need to look like tabs
- [x] Query history as another tab
- [x] Empty state for queries - have a look at GraphIQL
  - [x] Clojure comment for the 'Getting started'?
- [x] Add status endpoint
  - [x] Flesh out status endpoint, decide on appearance.
  - [x] Add some of the metrics to /status.
- [x] Remove footer
- [x] Edit header, add useful links to elsewhere in the SPA
- [x] Empty states - Finish contents of the tutorial, what default query to use, etc.
- [x] Home page - create a homepage which gives a good summary of what the console does, perhaps including a getting started video etc.
- [x] Add 'help' dropdown to header.
- [x] Topology on the node status
- [x] Submitting a UUID id to entity
- [x] Timezones - seems to be submitting +0100 as UTC
- [x] Ensure logo works on chrome

**Comment by danmason** [comment]
For a later version: Bring in spec for query checking.

**Comment by danmason** [comment]
Still an issue - clicking an entity from the query table no longer navigates to the entity (as it does not select the 'entity' header). Need to sort out the behaviour when navigating to a page in general.
