### ISSUE TITLE
Temporal range queries

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#968]
The easiest way to implement this is to add a vt-index, which only contains the times vt has changed (by anything), and then scan this index from start-vt to end-vt and do a normal point-in-time query for each step. This can obviously get a bit slow for some cases, but might be usable enough for others. We can then present the result in a few ways:

1. a single massive set, without time visible.
2. a per vt-change set, preferably with diffing, pruning empty change-sets. `{#inst "2020" #{...} #inst "2021 #{... diff-to-previous}]`

There are other, better, but harder ways to implement this, but those require changes to the query engine itself, and ability to perform interval-joins, where the join order will affect the result set.

**Comment by hraberg** [comment]
Actually, just doing the diffing like suggested above is way to simplistic for various reasons. So getting the result out is quite straight forward, assuming you know which valid-times to query (as suggested via an index above). How to represent it is not. In theory one could see each tuple as having a valid-time, which would be the max valid-time of the entities of that tuple, that is, this is the valid-time when this specific join and tuple could first be produced.

More analysis definitely needed. It doesn't stop us from coding up the first part and returning all tuples. Often for these queries that might be enough, assuming that often one of the selected attributes is some reasonable date that one can group or order by to make sense of the results.

**Comment by jonpither** [comment]
See https://github.com/juxt/crux/issues/776 to add a bitemporal dataset to the bench.

**Comment by jarohen** [comment]
Fixed in 2.x :wink:
