### ISSUE TITLE
Fix RocksDB Iterator Performance

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#97]
After running the WatDiv suite, see xtdb/xtdb#85, and comparing Rocks with LMDB, and also looking at various issues regarding the RocksJava implementation, it looks like the iterator API, especially the call to seek is more costly than necessary.

This issue has a summary:
https://github.com/facebook/rocksdb/pull/4302#issuecomment-424512437

The issue most interesting (but doesn't look likely to be merged) for us is the PR here:
https://github.com/facebook/rocksdb/pull/2283

Instead of waiting for upstream, or forking and having to maintain native builds, one alternative can be to depend on the native libraries unpacked by RocksJava (like now) but actually call them via JRA, the FFI bridge used by JRuby, see https://github.com/jnr/jnr-ffi.

What we would call is the subset of the Rocks C interface we use. This wraps the C++, see:
https://github.com/facebook/rocksdb/blob/master/include/rocksdb/c.h
https://github.com/facebook/rocksdb/blob/master/db/c.cc
https://github.com/facebook/rocksdb/blob/master/db/c_test.c

Assuming this gives us the expected performance, we could back this out once (and if) it's fixed upstream. It might also be possible to mix the interfaces, using RocksJava for everything apart from iteration, and grab its pointers via reflection and use them in JRA for iterating, but this might be messier.

Related, we could explore using the Java LevelDB port as well, avoiding JNI:
https://github.com/dain/leveldb

Note that the API-compatible JNI wrapper for LevelDB also seems to have performance issues related to iterators:
https://github.com/fusesource/leveldbjni
https://github.com/fusesource/leveldbjni/issues/38

**Comment by hraberg** [comment]
It's worth noting that while LMDB is faster (and often much faster) on subsequent queries, the first time a query gets issued it can be around the same speed (or slower) than Rocks, likely due to the OS paging in the relevant data.

LMDB also tends to be slower to ingest into, especially once the mapped data starts exceededing available memory.

**Comment by hraberg** [comment]
A more established alternative to JNR is JNA, which we could also try:
https://github.com/java-native-access/jna

For this there also exists various helpers to generate the Java interfaces and classes from the C headers. But JNR was written explicitly to overcome shortcomings of JNA, see presentation:
https://www.oracle.com/technetwork/java/jvmls2013nutter-2013526.pdf

JNR might also be base of JEP 191: Foreign Function Interface:
https://openjdk.java.net/jeps/191

**Comment by hraberg** [comment]
Made a spike for this, a commented out version lives here:
https://github.com/juxt/crux/blob/c848d6e37fcdb1360c434789179ab88d49eb6f1a/dev/hakan.clj#L970

Could not get any difference in speed compared to the normal RocksJava version. JNR has a set of annotations to control the amount of copying or sharing back and forth between native and Java, but with our byte array based API none of them seemed to make a difference.

The patch above, https://github.com/facebook/rocksdb/pull/2283, is based on using direct off heap `ByteBuffer`s. I did try this briefly, but could again not see any difference in speed, but I only changed our usage in a a few places, as the current byte array based API is prevalent.

That said, LWJGL's LMDB implementation is also JNI based of course, and we use the same code to interact with it, passing byte arrays in and out of the `KvStore` implementation. But from there, the final step across into LMDB is always done via a direct buffer managed by LWJGL.

It's inconclusive if this is the actual issue or not, or if LMDB simply is faster than Rocks here by design. Will need some further exploration. As several others have complained about the iterator performance in RocksJava I would not yet rule it out fully.

**Comment by hraberg** [comment]
Worth adding that as LMDB, once the OS cache has been filled (usually during the first query to some data) and the query is served from it, it's usually quite fast. This means that there's not likely much need for micro tweaks of the Clojure code itself that processes this.

What is needed though, is ensuring the join order and query plan is sensible and sensibly executed, as this still is a bottleneck for certain queries, but that work is still covered by xtdb/xtdb#85.

**Comment by hraberg** [comment]
I've been studying https://github.com/lmdbjava/lmdbjava a bit, which is backed by JNR.

By trying to emulate their usage patterns, which involve declaring arguments as `jnr.ffi.Pointer` and have these pointers be backed by direct allocated memory, I managed in a synthetic test which wrote 1000000 keys and then randomly performed a seek for each of them gain about 12.5% performance gain compared to RocksJava.

While that's a nice improvement, it might not warrant maintaining our own mapping layer for Rocks, though it's not very big. If one would go down this path it would make sense to consider switching to the above LMDB wrapper as well, so we were using JNR for both native dependencies. This would make it easier to reason about their respective behaviour, and one could move the `KvStore` interface to have the same usage patterns based on direct buffers.

**Comment by hraberg** [comment]
The test above was taking 1.6s in Rocks, 1.4s in Rocks via JNR and 0.7s in LMDB to seek 1000000 times.

Writing a similar test directly in C it takes about 1s.

**Comment by hraberg** [comment]
I wrote a experimental JNI wrapper and managed to get it close to C for this micro-benchmark which writes 1000000 20 byte hex strings as both keys and values. It takes about 0.8-0.9s to do the seeks, but this test isn't exactly the same as the test I ran above which did also shuffle the keys to get random access patterns. In these new tests I read the keys in backwards order.

Regardless, the main interesting thing is how close the JNI and native versions are in speed. This might of course change with larger dbs, keys, values or other factors.

**Comment by hraberg** [comment]
The wrapper uses `jlong` and passes pointers between Java and C, using https://github.com/real-logic/agrona to wrap direct `ByteBuffer`s.

**Comment by hraberg** [comment]
I've added the JNR version properly as an experimental KV store. It's about 15-20% faster for reads in the micro bench than RocksJava, but it still maintains the byte array contract currently used inside Crux. For further speed up one would consider passing through some form of buffer instead of arrays.

**Comment by hraberg** [comment]
Performance of micro bench, inserts 1000000 20 byte keys with themselves as values and reads them back in reverse order 10 times.

First is our in-memory backend. This is backed by a `clojure.lang.PersistentTreeMap`:
```
crux.kv.memdb.MemKv
Writing
"Elapsed time: 1248.745815 msecs"
Reading
"Elapsed time: 1480.90996 msecs"
"Elapsed time: 1265.900292 msecs"
"Elapsed time: 1247.004836 msecs"
"Elapsed time: 1242.153748 msecs"
"Elapsed time: 1240.533288 msecs"
"Elapsed time: 1245.671421 msecs"
"Elapsed time: 1241.765523 msecs"
"Elapsed time: 1241.778165 msecs"
"Elapsed time: 1239.150531 msecs"
"Elapsed time: 1252.271036 msecs"
Done
"Elapsed time: 12698.667257 msecs"
```

Then we have our "main" Crux backend for RocksDB, which is backed by the official Java API, https://github.com/facebook/rocksdb/wiki/RocksJava-Basics One of the motivating factors for this issue is the feeling that this is slow for seeks, see other comments above.
```
crux.kv.rocksdb.RocksKv
Writing
"Elapsed time: 660.600668 msecs"
Reading
"Elapsed time: 1230.303612 msecs"
"Elapsed time: 1224.769686 msecs"
"Elapsed time: 1219.023972 msecs"
"Elapsed time: 1222.04968 msecs"
"Elapsed time: 1217.185407 msecs"
"Elapsed time: 1217.33759 msecs"
"Elapsed time: 1221.326072 msecs"
"Elapsed time: 1219.514941 msecs"
"Elapsed time: 1229.558406 msecs"
"Elapsed time: 1230.505295 msecs"
Done
"Elapsed time: 12232.778127 msecs"
```

Then we have a backend using the same native library as RocksJava, but binds straight to the RocksDB C API, see https://github.com/facebook/rocksdb/blob/master/examples/c_simple_example.c

We do this to avoid copying byte arrays back and froth over the JNI boundary, and use JNR, which is a FFI library for Java, primarily used by JRuby:
https://github.com/jnr/jnr-ffi
```
crux.kv.rocksdb.jnr.RocksJNRKv
Writing
"Elapsed time: 416.01519 msecs"
Reading
"Elapsed time: 1007.195711 msecs"
"Elapsed time: 984.466632 msecs"
"Elapsed time: 982.46386 msecs"
"Elapsed time: 980.928584 msecs"
"Elapsed time: 981.608239 msecs"
"Elapsed time: 979.968217 msecs"
"Elapsed time: 980.172762 msecs"
"Elapsed time: 984.644946 msecs"
"Elapsed time: 976.536499 msecs"
"Elapsed time: 978.500102 msecs"
Done
"Elapsed time: 9837.439043 msecs"
```

To get a better feeling for the JNR overhead, I wrote an actual JNI binding to the same native library and C interface. We'll return to this below.
```
crux.kv.rocksdb.jni.RocksJNIKv
Writing
"Elapsed time: 367.861605 msecs"
Reading
"Elapsed time: 988.666579 msecs"
"Elapsed time: 969.105031 msecs"
"Elapsed time: 980.65317 msecs"
"Elapsed time: 978.297641 msecs"
"Elapsed time: 965.902276 msecs"
"Elapsed time: 963.412953 msecs"
"Elapsed time: 960.450897 msecs"
"Elapsed time: 954.825588 msecs"
"Elapsed time: 960.107519 msecs"
"Elapsed time: 965.040262 msecs"
Done
"Elapsed time: 9687.566933 msecs"
```

Finally, we have our LMDB backend, backed by the https://github.com/LWJGL/lwjgl3 LMDB module. As can be seen, this is 2-3 times faster than any other backend for this test, including native RocksDB.
```
crux.kv.lmdb.LMDBKv
Writing
"Elapsed time: 418.575761 msecs"
Reading
"Elapsed time: 331.68767 msecs"
"Elapsed time: 302.200642 msecs"
"Elapsed time: 296.639882 msecs"
"Elapsed time: 300.122596 msecs"
"Elapsed time: 301.059602 msecs"
"Elapsed time: 296.589158 msecs"
"Elapsed time: 299.854363 msecs"
"Elapsed time: 297.56731 msecs"
"Elapsed time: 295.091945 msecs"
"Elapsed time: 298.6591 msecs"
Done
"Elapsed time: 3020.585332 msecs"
```

These two final tests don't use Crux, but try to gauge performance at the lower level. That also means that the tests themselves aren't exactly the same, as they are different implementations of the test code, though they're meant to do the same thing.

This first one is the JNI wrapper used by the JNI backend, but used on its own from Java, with direct buffers from https://github.com/real-logic/agrona and no byte arrays, see also xtdb/xtdb#2009.
```
crux.Crocks JNI Java
Writing
497
Reading
880
876
866
1120
868
865
864
863
873
864
Done
8942
```

Finally we have the test written directly in C against the RocksDB C API:
https://github.com/facebook/rocksdb/blob/master/examples/c_simple_example.c
```
RocksDB Native C
Writing
486
Reading
845
836
836
834
838
838
835
834
835
Done
7531
```

**Comment by hraberg** [comment]
As can be seen in the above comment, the time gained by moving to off heap buffers isn't massive, but this test is quite small and simple, so it's hard to extrapolate the effect of moving away from byte arrays for the entire query engine internals. The difference between the C and raw JNI version might be possible to tune a bit more, but in any effect, the number for the C API is likely a bottleneck regardless for RocksDB.

LMDB is faster than any other option here for this test. The JNR backend is 15-20% faster than RocksJava here, while the JNI backend is just a bit faster, but insights from implementing it helped tune the JNR one. The likelyhood that it's worth the effort to build and provide our own native libraries isn't there as it looks.

This means that we'll be keeping the JNR backend around, potentially phasing out the RocksJava one.

**Comment by hraberg** [comment]
As we have a feeling for the lower bound that RocksDB in C can reach, I'm closing this. There's a potential other 25% to squeeze out, some of that might be gained by using buffers, see xtdb/xtdb#2009. The non-Crux Java JNI test is using buffers, and is about 10% faster than our JNR implementation, which might give us a hint of what to expect. The final 15% to C would be due to JNI tuning, which might not be possible as there's always an overhead.

It's also worth remembering that LMDB is also using byte arrays while using it's own buffers, while still being 2-3x times faster than even native RocksDB in this test.

LWJGL has done quite a bit of interesting work in this area:
https://blog.lwjgl.org/memory-management-in-lwjgl-3/

**Comment by mad** [comment]
Hi there

Could you provide some tuning about rock performance for seek operation?

https://groups.google.com/g/rocksdb/c/NVMQr97D_Bc

Benchmark rocks vs berkeleyje https://gist.github.com/mad/2556f6e3af2b30c0099780eb4aac6afe
