### ISSUE TITLE
Users can find documents using full-text search

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#977]
Plenty to consider here:
* node-local Lucene indices? (PRIORITY)
* opt-in on certain attributes?
* temporal/atemporal Lucene?
* integration with ElasticSearch for independent clustering?

## Elasticsearch

Possible modes for integration:

1. ES as remote "golden" doc-store (possible but not generally desirable)
2. ES embedded, like Lucene, but used only to augment indexes (per-node scaling would be 1:1 which has limited benefit)
3. ES as remote cluster, used only to augment indexes

Index-store augmentation should support regular bitemporal filtering.

Functionality could be exposed via `(crux.api/es-search db ...)` or within queries using a predicate like `[(crux.es/search ...) ?search-result]` (preferred)

Option 3:
![image](https://user-images.githubusercontent.com/456658/88930148-fc58bc80-d272-11ea-9ebe-f05b5bd33662.png)

It is unlikely we would decide to use a Clojure client library like https://github.com/clojurewerkz/elastisch or https://github.com/mpenet/spandex

**Comment by jonpither** [comment]
References:

* https://github.com/juxt/crux-rnd/blob/master/src/crux/datalog/lucene.clj
* https://www.toptal.com/database/full-text-search-of-dialogues-with-apache-lucene
* https://lucene.apache.org/core/8_6_0/core/index.html
