### ISSUE TITLE
Devs can refresh their environment easily without bouncing a REPL

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#98]
It can be quite easy to get the dev environment into a state where some things refuse to reload, or you need to know the exact order of namespaces to reload for a small change. This is mainly due to redefined records or protocols.

**Comment by hraberg** [comment]
One way to potentially achieve this is to move all the protocols and records to their own namespaces without any actual code, and extend the records with the protocols in other implementation namespaces. The drawback is that this creates a lot of extra files and structure. One also has to decide how many of these namespaces there should be etc. We have some of this already, but it's not consequently done.

This card is less of an issue if one always resets the system when doing changes, but I like to evaluate individual files as I change them, preferably without getting any `ClassCastExceptions` from different record versions, but might not be worth making that work. The above scheme should only require a reset when one is actually changing the protocols or record definitions themselves.

**Comment by jonpither** [comment]
Can reproduce by adding a new method to a Java interface, such as `ICruxAPI`.
