### ISSUE TITLE
Tx ops are fully documented

### ISSUE THREAD

**Issue by lgrapenthin** [xtdb/xtdb#997]
While the docs mention that there is an "end valid-time" arg for "put", such an arg is not explained for delete, but exists according to space adventure tutorial. Also, it should be noted for other ops, if its accepted. Also, it should be documented how to unassert an " end valid-time" of a previous put operation, for example to extend an user access pass.

**Comment by jarohen** [comment]
Thanks @lgrapenthin, and apologies that this isn't clear currently.

We're currently running through significant changes to our documentation that should cover this issue - will add it as a link.
